### ISSUE TITLE
Design a Wireframe

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy#1]
Wireframe needed for one page Web-Application
Appropriate Design for Explanation of Steps and Solution

For more clarification: [See Working](https://sairish2001.github.io/makesmatheasy.github.io/)

### Point to be Noted:
- It is one Page Application so design accordingly
- Should be Mobile friendly as going to release a Android App for the same
- Only Dark Mode (`#232a36`)-> Color Code

**Comment by nandini7637** [comment]
Hello I would like to contribute to it being a part of GSSOC. Can you please elaborate the issue.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by sairish2001** [comment]
If you want any changes in UI then create a wireframe for it, and do tell me before implementing, to which part you are going to change

**Comment by nandini7637** [comment]
yeah sure sir, I am a bit new to wireframe I'll tell u a soon as  I need to do any implementation

**Comment by sairish2001** [comment]
Deadline 14 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
Any Update? @nandini7637
