### ISSUE TITLE
"XYZ operation is not possible with these inputs" gets displayed in between the matrix

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#1000]
## **Describe the bug**

In matrix operation, on clicking "XYZ operation is not possible with these inputs" it gets displayed in between the matrix

## **Possible solution**

I will remove this text from the dropdown and will place it somewhere out of it.

## **Screenshots**
![drop](https://user-images.githubusercontent.com/57946528/114351702-99048580-9b88-11eb-8079-10d7136f5e4f.png)

**Comment by shonali2600** [comment]
Please assign me this issue as a gssoc participant.

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST
