### ISSUE TITLE
Add about LCM/HCF/Factors

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1009]
Hi ! I would like to add definition, concept with an example, relation between HCF and LCM, for numbers in `LCM/HCF/Factors` section of `General Maths`.

Kindly assign this to me under GSSoC.

**Comment by sairish2001** [comment]
You should wait for assignment before making PR

**Comment by mehabhalodiya** [comment]
Okay, sorry for the inconvenience!
