### ISSUE TITLE
Adding calculator for pentagonal prism

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1010]
I would like to add a calculator for finding different parameters of pentagonal prism. I would also like to add different types of prisms and pyramids as subcategories of prism and pyramid respectively.
Please assign this issue to me.

**Comment by RaveenaBhasin** [comment]
@sairish2001 Can I work on this issue?

**Comment by sairish2001** [comment]
Go ahead
Deadline 18 April,2021 11:59 PM IST

**Comment by RaveenaBhasin** [comment]
I have made the PR #1033. Kindly review it @sairish2001
