### ISSUE TITLE
Bug in Addition of any Number System

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#1013]
## **Describe the bug**

- The answer is not displaying in the result, even there is no button to get answer
 
## **Screenshots**

![image](https://user-images.githubusercontent.com/75009990/114394474-e13b9c00-9bb8-11eb-9dbb-99e583069720.png)

**Comment by ShrutiOmer** [comment]
Please assign this issue i want to work on this.

**Comment by sairish2001** [comment]
i think instead of adding button,
remain it as it is i.e oninput() triggering of function

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST

**Comment by ShrutiOmer** [comment]
Thankyou, I will do as suggested
