### ISSUE TITLE
Enhancing application of derivatives by adding more stuff

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1016]
Right now the application of derivatives page has only documentation and no image for visualizing the points written over there.
I would like to design images for the applications mentioned and add Rolle's theorem and Lagrange's mean value theorem along with proper images in this section.
Please assign this issue to me.

**Comment by RaveenaBhasin** [comment]
@sairish2001 Can I work on this issue?

**Comment by sairish2001** [comment]
Go ahead
Deadline 18 April,2021 11:59 PM IST

**Comment by RaveenaBhasin** [comment]
I have made the PR #1039. Kindly review it
