### ISSUE TITLE
Add geometric results on proportionality

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1022]
Hi! I would like to add :

Geometric results on proportionality :-
- Fundamental Theorem of Proportionality
Using the fundamental theorem on proportionality, I will obtain some results which are very useful to solve examples.

- Converse of the fundamental theorem of proportionality

I will add this under `Graphs and Shapes` section in `Congruence and similarity of triangle` category as this is a part of similarity of triangles.

Kindly assign this to me under GSSoC.

**Comment by mehabhalodiya** [comment]
I will add images too for these theorems.

**Comment by mehabhalodiya** [comment]
@sairish2001 Can I work on this?

**Comment by sairish2001** [comment]
try to add Calculators, for the same

**Comment by mehabhalodiya** [comment]
In this concept, there is understanding with diagrams.
As for example, you can see the `coordinate geometry theorem` section and `congruence and similarity of triangle` itself!

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 (11:59 PM IST)
