### ISSUE TITLE
the search bar is now expanding to left rather than from center

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1028]
## **Describe the bug**

- A clear and concise description of what the bug is.
- the search bar is now expanding to left rather than from center that's why it is getting more aligned to the left side

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![mathnewissue](https://user-images.githubusercontent.com/61223163/114490797-14227600-9c33-11eb-8fe7-3cc7a845411a.png)
can you please assign me this issue 
- If applicable, add screenshots to help explain your problem.

**Comment by sairish2001** [comment]
Go ahead
Deadline 18 April,2021 11:59 PM IST

**Comment by sairish2001** [comment]
Go ahead
Deadline 18 April,2021 11:59 PM IST
