### ISSUE TITLE
Bug in torus shape calculator

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1034]
The indentation of the fields to be filled is not correct because of which the answer coming is not completely visible. I would like to resolve this issue.
![Screenshot (1736)](https://user-images.githubusercontent.com/73697080/114499530-e4c83500-9c43-11eb-87f9-204320a4b209.png)

**Comment by RaveenaBhasin** [comment]
@sairish2001 Can I work on this issue?

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST
