### ISSUE TITLE
Adding calculator for hexagonal prism

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1035]
Under calculator of 3D shapes in the prism section I would like to add the calculator for hexagonal prism. Please this to me under GSSoC.
![Capture](https://user-images.githubusercontent.com/70858557/114502561-9ae24d80-9c49-11eb-9359-f1d96db45259.PNG)

**Comment by RaveenaBhasin** [comment]
@madihamallick I guess rectangular prism is cuboid only right?

**Comment by madihamallick** [comment]
> @madihamallick I guess rectangular prism is cuboid only right?

yeah, my mistake. No worries, I'll change the issue :)

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST
