### ISSUE TITLE
Adding calculator for pentagonal pyramid

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1036]
Under calculator of 3D shapes in the pyramid section I would like to add the calculator for pentagonal pyramid. Please this to me under GSSoC.
![Capture](https://user-images.githubusercontent.com/70858557/114502929-265bde80-9c4a-11eb-8919-d4876ac9edc2.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST
