### ISSUE TITLE
Adding calculator for octagonal prism

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1037]
Under calculator of 3D shapes in the prism section I would like to add the calculator for octagonal prism. Please this to me under GSSoC.
![Capture](https://user-images.githubusercontent.com/70858557/114502561-9ae24d80-9c49-11eb-9359-f1d96db45259.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 18 April,2021 11:59 PM IST
