### ISSUE TITLE
Two scroll bar in properties of probability section

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1041]
## **Describe the bug**

-There are two scroll bar present in properties of probability

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/114521009-a2acec80-9c5f-11eb-8d6e-1f160e6b5fcc.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST
