### ISSUE TITLE
Two scroll bars

### ISSUE THREAD

**Issue by manisha-27** [sairish2001/makesmatheasy#1044]
![Screenshot (269)](https://user-images.githubusercontent.com/67019423/114544488-50c49080-9c78-11eb-8281-7630eb2e392a.png)

whenever chosen a particular topic then it shows 2 scroll bars instead of one and also takes a a lot's of space, can you please assign me this issue.

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST

**Comment by abhijeet141** [comment]
@sairish2001 This issue has already been resolved you can close this issue .
