### ISSUE TITLE
Putting the search bar in center

### ISSUE THREAD

**Issue by satcasm** [sairish2001/makesmatheasy#1049]
On mobile devices the search bar is not in center.
Would like to fix it under GSSOC' 21.
Thanks!
![Screenshot_2021-04-13-20-15-02-90](https://user-images.githubusercontent.com/56315878/114573071-ae1b0a80-9c95-11eb-896f-4ad69a095e13.jpg)

**Comment by sairish2001** [comment]
Go ahead
Deadline 18 April,2021 11:59 PM IST

**Comment by sairish2001** [comment]
This issue is already created by someone
