### ISSUE TITLE
Add properties of shapes

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#1054]
## Proposal

Instead of having different section for properties of each shape in graphs and shapes, we can make a option called " Properties of shapes" in which I want to add properties of square , rectangle, parallelogram, triangles and will also add the already existed properties of circles and parallel line under this section.

I will add page for each shape.
The structure will be like:
Properties of shapes(by clicking on this new window have following options)
                                 --->Parallel Lines---->new window
                                ---->Parallelogram---->new window
                                ----->square---->new window
                                         ''''
                                         ''''

Please assign this issue to me, I want to work on this.

**Comment by sairish2001** [comment]
Instead of adding new window/ html page

implement in the index.html, in few days, I will create a new issue for the same to shift all the Theory to a new html
