### ISSUE TITLE
Want to add explanation of complex number calculation

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#1055]
## **Is your feature request related to a problem? Please describe.**

- In operations of complex numbers no step wise solution is given ,I want to step wise solution to it.
![image](https://user-images.githubusercontent.com/75009990/114667753-7f487700-9d1d-11eb-9423-676cd5d0542b.png)

Here no step wise solution is given, i want to add that.

**Comment by ShrutiOmer** [comment]
Please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST
