### ISSUE TITLE
Enhancing the search so option in the index menu.

### ISSUE THREAD

**Issue by nitinjaiswal7537** [sairish2001/makesmatheasy#1058]
## Enhancing the search so option in the index menu.

- The bug is so that a new user shall find it difficult to what he need to do in order to get the result.
   It shall give one proper knowledge of what needed to be done.

## **Possible solution**

- It can be solved simply just by giving some message onto the search box like " search for the type of addition, subtraction or something else".

**Comment by shrey27tri01** [comment]
You mean some placeholder text inside the search bar in index, instead of just "Search", right? If so, can you give us the exact text you are planning to add?

**Comment by nitinjaiswal7537** [comment]
Message such as " Enter the operation to perform". Could I use that??

**Comment by shrey27tri01** [comment]
A message like "Search for operation or equation" would be more suitable. Go ahead with this :)
