### ISSUE TITLE
Get the perfect background picture .

### ISSUE THREAD

**Issue by nitinjaiswal7537** [sairish2001/makesmatheasy#1059]
## Proposal

Attaching with certain kind of background pictures could made it look more fascinating.
Further this kind will make it more attractive.

**Comment by shrey27tri01** [comment]
We had already gone through this issue at #13. Please have a look at that so that you get an idea of what we expect for the homepage. And please let us know about what image you will be using as the background before creating the PR.

**Comment by nitinjaiswal7537** [comment]
Can I make some kind of background design using graphic designing technique,
And later adding it to web app.

**Comment by sairish2001** [comment]
We don't have any proper mindset on this, so leave this issue
