### ISSUE TITLE
Sum of n numbers in AP and GP.

### ISSUE THREAD

**Issue by nidhivanjare** [sairish2001/makesmatheasy#1060]
## **Is your feature request related to a problem? Please describe.**

- Sum of n numbers in Arithmetic Progression and Geometric progression. 

## **Describe the solution you'd like**

- It will return the sum of n number in a particular sequence. 

I am a GSSOC'21 participant and would like to work on this issue.

**Comment by apekshamanchanda** [comment]
Sure, go ahead
Deadline : 20 April 2021

**Comment by apekshamanchanda** [comment]
That feature is already there

**Comment by shrey27tri01** [comment]
Since the feature is already there, I am closing the issue.
