### ISSUE TITLE
Adding distance of point from line calculator

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1069]
I would like to add calculator for finding distance of point from line in coordinate geometry calculator section.
Please assign this issue to me @sairish2001

**Comment by RaveenaBhasin** [comment]
Can I work on this issue @sairish2001 ?

**Comment by shrey27tri01** [comment]
@RaveenaBhasin Go ahead with this :)
Deadline 20th April 2021 11:59 PM IST

**Comment by RaveenaBhasin** [comment]
I have the PR. Kindly review it @shrey27tri01 @sairish2001

**Comment by shrey27tri01** [comment]
@RaveenaBhasin I have reviewed the PR. Kindly look at the review and make necessary changes.
