### ISSUE TITLE
bug in favourite button

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1071]
![image](https://user-images.githubusercontent.com/60147732/114748209-4df89700-9d6f-11eb-971a-7b8db2706f6b.png)
IN THIS pic when we click on favourite button on addition/sub/multiplication of any system it add binary/hexadecimalconvertor to favourite and not the corresponding

**Comment by shrey27tri01** [comment]
@khareyash05 Go ahead with this :)
Deadline 18th April 2021 11:59 PM IST
