### ISSUE TITLE
to find greatest integer and fractional part of a number

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1077]
The user will enter a number and i will performthe greatest integer function and also the fractional part function

**Comment by sairish2001** [comment]
can you show me a example

**Comment by khareyash05** [comment]
@sairish2001 FOr example - 
the greatest integer function applied for 8.3 will be 8 i.e. the nearest integer left to the number
and fractional part will be 0.3 
there are also some of their properties
We also have to know that greates integer function of -1.7 will be -2 and not -1
and similarly its fractional part will be 1 - 0.7 = 0.3
So it works differently for both negative and positive parts

**Comment by sairish2001** [comment]
Go ahead
Deadline 21 April, 2021 11:59 PM IST

**Comment by khareyash05** [comment]
@sairish2001 Could you suggest me a place to fit this in please? I am bit confused

**Comment by sairish2001** [comment]
add under general maths category
