### ISSUE TITLE
adding law of cosines calculator

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1079]
I would like to add a calculator for finding angles of a triangle when sides a, b, c are given using the cosine formula.
Please assign his issue to me @sairish2001

**Comment by RaveenaBhasin** [comment]
Can I work on this issue @sairish2001 ?

**Comment by shrey27tri01** [comment]
Go ahead with this issue :)
Deadline 21 April 2021 11:59 PM IST
