### ISSUE TITLE
Adding searchbar recommendation for coordinate geometry calculator

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1080]
I would like to add a search bar recommendation for the coordinate geometry calculator and its theorems.
Please assign this issue to me @sairish2001

**Comment by RaveenaBhasin** [comment]
@shrey27tri01 Please assign this issue to me.

**Comment by shrey27tri01** [comment]
Can you please elaborate on what exactly it is you are trying to add, and where will it be? Are you implying that we add a recommendation to the main search bar of the home page?

**Comment by RaveenaBhasin** [comment]
When we open the search bar present in the top and type coordinate geometry calculator it will lead us to Google search because till now we have not given recommendation of it. U can check this out by searching more items present in web-app and it will lead us to that particular section. 
Hope u got my point @shrey27tri01

**Comment by shrey27tri01** [comment]
Oh! Okay I got what you are implying. You can go ahead with this :)
Deadline 20th April 2021 11:59 PM IST
