### ISSUE TITLE
Bug in pentagonal prism calculator

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1086]
- The answer of surface area of pentagonal prism is incorrect.

![pentaprism](https://user-images.githubusercontent.com/73488906/114824269-48886480-9de2-11eb-8851-ce8b20007722.png)

For example: a = 2, h = 5
The correct answer is 63.76 and above it is displayed 84.4.

I will solve this.
Kindly assign to me under GSSoC.

**Comment by apekshamanchanda** [comment]
Go ahead 
Deadline: 20 April 2021
