### ISSUE TITLE
Adding exponent calculator

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1088]
I would like to add a calculator for finding exponent in general maths section 
x^n=y Required fields to be filled are x and y and the calculator will be telling value of n. 
Eg: 3^n=81 n=4
Please assign this issue to me

**Comment by RaveenaBhasin** [comment]
@shrey27tri01 Please assign this issue to me

**Comment by shrey27tri01** [comment]
Go ahead with this :)
Deadline 20th April 2021 11:59 PM IST
