### ISSUE TITLE
Adding calculator for Dodecahedron

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1089]
Under calculator of 3D shapes, I would like to add the calculator for Dodecahedron. Please assign this to me under GSSoC.

**Comment by shrey27tri01** [comment]
Go ahead with this :)
Deadline 20 April 11:59 PM IST

**Comment by shrishti-c** [comment]
If there's no update on this issue, may I work on this issue? @sairish2001  @shrey27tri01  @mehabhalodiya  @apekshamanchanda

**Comment by mehabhalodiya** [comment]
Hey! I am working on this. Sorry for some delay as I am having my semester exams. 

I will submit a PR for this within 1-2 days.

**Comment by shrishti-c** [comment]
Cool. No worries.  ;)
