### ISSUE TITLE
Adding Regular decagon in Calculator for Shapes

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1095]
I Want to add Regular decagon in calculator for shapes.
Please assign this to me under GSSoC.

**Comment by madihamallick** [comment]
Please assign this to me @sairish2001 @shrey27tri01 @apekshamanchanda

**Comment by shrey27tri01** [comment]
Go ahead :)
Deadline 22 April 2021 11:59 PM IST
