### ISSUE TITLE
Plotting Bar Graphs

### ISSUE THREAD

**Issue by nidhivanjare** [sairish2001/makesmatheasy#1096]
## **Is your feature request related to a problem? Please describe.**

- To plot a graph according to the input(data) given. 

## **Describe the solution you'd like**

- The user will enter the values and a graph will be displayed accordingly on the XY plane.

**Comment by sairish2001** [comment]
Great
Go ahead Deadline 21 April,2021 11:59 PM IST

**Comment by nidhivanjare** [comment]
I am getting a bug in the code. Can you please extend the deadline?
