### ISSUE TITLE
 Adding calculator for Trapezoidal Prism

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1098]
Under calculator of 3D shapes in the prism section I would like to add the calculator for Trapezoidal Prism . Please assign this to me under GSSoC.

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline: 21 April 2021 11:59 PM IST

**Comment by shrishti-c** [comment]
@apekshamanchanda @mehabhalodiya @sairish2001 @shrey27tri01  If there's no update on this issue, may I work on this issue?

**Comment by mehabhalodiya** [comment]
Hey! I am working on this. Sorry for some delay as I am having my semester exams.

I will submit a PR for this within 1-2 days for sure!

**Comment by shrishti-c** [comment]
Sorryyy!!!

**Comment by shrishti-c** [comment]
I genuinely thought you aren't interested. was trying my luck
