### ISSUE TITLE
Bug in 15's 16's complement 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1112]
![image](https://user-images.githubusercontent.com/71064674/114931767-48c14800-9e54-11eb-84e0-bfe990a8d057.png)

answer must be - 
15's comp = e
16's comp = f

**Comment by AB-san** [comment]
plz assn me this issue

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline: 22 April 2021
