### ISSUE TITLE
legendre,bessel and chebyshev differential eqn

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1125]
Hi I would like to add legendre,bessel and chebyshev differential eqn

**Comment by apekshamanchanda** [comment]
Legendre differential eqn is already there but you can add other two.
Deadline : 23 April 2021

**Comment by khareyash05** [comment]
I am sorry but that was legendre for linear and this is for power series

**Comment by apekshamanchanda** [comment]
No worries, you can work on it

**Comment by khareyash05** [comment]
@apekshamanchanda Just a suggestion could you pls increase the level of the label if possible because i feel that level 1 is not apt for the same. Just a suggestion
Thanx

**Comment by apekshamanchanda** [comment]
Ya sure, I added it according to initial description
