### ISSUE TITLE
geometric mean for negative numbers

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1127]
The geometric mean isn't defined for negative numbers but it is giving an answer
I would like to add condition that numbers shouldnt be negative
![image](https://user-images.githubusercontent.com/60147732/115037264-ed429900-9eeb-11eb-8d23-619e802080bd.png)

**Comment by AB-san** [comment]
Hello @khareyash05  actually GM is defined for negative numbers , but the condition is both numbers have to be negative.
GM doesn't exist for numbers with opposite signs like -> -1 and 4

**Comment by khareyash05** [comment]
Oh thanx @AB-san for info.
