### ISSUE TITLE
show proper message instead of NaN

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1128]
## **Is your feature request related to a problem? Please describe.**

- show proper message instead of NaN in any base to any base
-  I would like to work on this issue, under gssoc2021

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

![image](https://user-images.githubusercontent.com/59261812/115054039-6696b780-9efd-11eb-88ec-de731f77c9f3.png)

**Comment by AB-san** [comment]
I would like to work on this issue
