### ISSUE TITLE
showing +- simultaneously

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1129]
## **Describe the bug**

- in conjucate of complex number showing +- simultaneously
- I would like to work on this issue, under gssoc2021

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/59261812/115054535-efadee80-9efd-11eb-951c-d65e0bfc81e3.png)

**Comment by AB-san** [comment]
Hey @satyampgt4  do you wanna work on this issue or else i can take it !!

**Comment by satyampgt4** [comment]
yes I want lto work on this issue

**Comment by AB-san** [comment]
> yes I want lto work on this issue

@satyampgt4 then you have to ask em to assign you

**Comment by satyampgt4** [comment]
> @satyampgt4 then you have to ask em to assign you

usually i ask in comments or ask in issue itself 
but due to some internet problem i was not able to comment 

so can i work on this issue please .....

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 April, 2021 11:59 PM IST
