### ISSUE TITLE
Modify UI of subtraction of binary numbers

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1132]
![image](https://user-images.githubusercontent.com/71064674/115057929-43bad200-9f02-11eb-80fe-d20b7519d9f7.png)

I would like to Modify subtraction of binary numbers and show the working steps just the way it is shown for complement of binary no.s

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Will you provide a stepwise solution to it?

**Comment by AB-san** [comment]
> Will you provide a stepwise solution to it?

Yes

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline: 23 April 2021
