### ISSUE TITLE
Modify UI  of subtraction of octal numbers

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1133]
![image](https://user-images.githubusercontent.com/71064674/115058290-be83ed00-9f02-11eb-8fa6-a5b4b81b78a5.png)

I would like to Modify subtraction of octal numbers and show the working steps just the way it is shown for complement of octal no.s

**Comment by AB-san** [comment]
plz assign me this issue

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline : 23 April 2021

**Comment by AB-san** [comment]
> @apekshamanchanda @sairish2001 I would like to work on it please assign it to.

@Samridhi-98  I have already completed this issue , I m just waiting for my previous pr to get merged so that i can push this one , so that i dont face conflicts
i hope you understand

**Comment by Samridhi-98** [comment]
> > @apekshamanchanda @sairish2001 I would like to work on it please assign it to.
> 
> @Samridhi-98 I have already completed this issue , I m just waiting for my previous pr to get merged after that i can push this one , so that i dont face conflicts
> i hope you understand

Okay, no problem.
