### ISSUE TITLE
Modify UI of subtraction of hexadecimal numbers

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1134]
![image](https://user-images.githubusercontent.com/71064674/115058756-2f2b0980-9f03-11eb-81b4-5931398565ec.png)

I would like to Modify subtraction of hexadecimal numbers and show the working steps just the way it is shown for complement of hexadecimal no.s

**Comment by AB-san** [comment]
plz assn me this issue

**Comment by sairish2001** [comment]
Go ahead 
Deadline 24 April,2021 11:59 PM IST
