### ISSUE TITLE
Modify any base to any base converter to calc frac part also

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1141]
Modify any base to any base converter to convert the fractional part also

![image](https://user-images.githubusercontent.com/71064674/115099128-8bb51580-9f51-11eb-9422-c454bc9a3978.png)

expected answer - 
4.2076207

**Comment by AB-san** [comment]
please assign me this issue

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline : 23 April 2021
