### ISSUE TITLE
Repeated rules in SPI/CGPA calculator

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#1151]
## **Describe the bug**

Repeated rules in SPI/CGPA calculator

## **Screenshots**

![cgpa](https://user-images.githubusercontent.com/57946528/115105318-d8154b00-9f7b-11eb-94c0-8f999d832565.png)

Please assign me this issue

**Comment by apekshamanchanda** [comment]
Go ahead 
Deadline: 22 April 2021
