### ISSUE TITLE
Adding calculator for square prism

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1153]
Under calculator of 3D shapes in the prism section I would like to add the calculator for square prism. Please assign this to me under GSSoC.

![p](https://user-images.githubusercontent.com/70858557/115109502-a90ad380-9f93-11eb-80ce-21c6f9b80881.PNG)

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline: 23 April 2021
