### ISSUE TITLE
Pythagorean triplets

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1154]
## **Describe the bug**

The calculation part to get the Pythagorean triplet is wrong. For example, if **number is odd**. Eg: **3** the output should be **3, 4, 5** and when the **number is even**. Eg: **4** the output should be **8, 15, 17**. But here it is showing output for both even and odd. Please assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![b1](https://user-images.githubusercontent.com/70858557/115109916-35b69100-9f96-11eb-84e7-0db23c4f848d.PNG)
![b2](https://user-images.githubusercontent.com/70858557/115109917-36e7be00-9f96-11eb-926e-7c3a8d74d85f.PNG)

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline: 23 April 2021
