### ISSUE TITLE
Angle Converter

### ISSUE THREAD

**Issue by shrishti-c** [sairish2001/makesmatheasy#1156]
![Screenshot (171)](https://user-images.githubusercontent.com/73748606/115110224-e1acac00-9f97-11eb-89ff-754fdca6d76f.png)

**Comment by apekshamanchanda** [comment]
Sounds great, Go ahead
Deadline: 23 April 2021

**Comment by RaveenaBhasin** [comment]
It is already there in the unit convertor section. You can close this issue @apekshamanchanda @shrishti-c

**Comment by apekshamanchanda** [comment]
Oh, I missed it 
Will close it
