### ISSUE TITLE
Enhance UI of Logarithmic calculator

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1158]
## **Is your feature request related to a problem? Please describe.**

- enhance UI of Logarithmic calculator

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
- 
![image](https://user-images.githubusercontent.com/59261812/115112218-1cb3dd00-9fa2-11eb-9141-ffd48058d4bd.png)

**Comment by apekshamanchanda** [comment]
Can you explain a little more how will you make it more clear as it is pretty much understandable already

**Comment by satyampgt4** [comment]
the two input seem odd i will make two separate input field with label base and number

![image](https://user-images.githubusercontent.com/59261812/115116762-0bc29600-9fb9-11eb-92bd-f17ce5f96026.png)

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline : 23 April 2021
