### ISSUE TITLE
Adding "00" in empty cell in calculator

### ISSUE THREAD

**Issue by satcasm** [sairish2001/makesmatheasy#1166]
In the calculators, we often see a cell containing `00` , not sure if it is needed, but it would improve the calculator.
As of now it is missing and a empty cell is available too.
Would like to implement this under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/115115743-afa94300-9fb3-11eb-9a4c-fd8319246d05.png)

**Comment by apekshamanchanda** [comment]
Go ahead
deadline: 23 April 2021
