### ISSUE TITLE
Sector of a Circle

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1169]
## **Is your feature request related to a problem? Please describe.**

I would like to add the picture of sector of a circle and add the steps for the calculation of area. Please assign this to me under GSSoC.

## **Describe the solution you'd like**

![1](https://user-images.githubusercontent.com/70858557/115118436-c2764480-9fc0-11eb-9b1c-e81f13b9e982.PNG)

**Comment by apekshamanchanda** [comment]
Go ahead
Deadline : 23 April 2021
