### ISSUE TITLE
Searchbar bug in mobile view

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1179]
## **Describe the bug**

- A clear and concise description of what the bug is.
- In mobile view the search bar is right align and also going outside the screen .

## **Possible solution**

- Describe the solution you thought of.
- 

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- 
![image](https://user-images.githubusercontent.com/61223163/115132867-9c34c100-a021-11eb-9507-f4dd83476bd8.png)
Please assign me this issue under gssoc

**Comment by sairish2001** [comment]
Go ahead 
Deadline 24 April,2021 11:59 PM IST
