### ISSUE TITLE
find equation of line perpendicular to a line and pass through a point

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1188]
## Proposal
add a calculator to
find equation of line perpendicular to line and  pass through a point
(A clear and concise description of what the proposal is.)

**Comment by satyampgt4** [comment]
@sairish2001 i would like to work on it

**Comment by sairish2001** [comment]
Go ahead 
Deadline 24 April,2021 11:59 PM IST
