### ISSUE TITLE
 Improper Fraction to Mixed Fraction Calculator  

### ISSUE THREAD

**Issue by shrishti-c** [sairish2001/makesmatheasy#1191]
Improper Fraction  to Mixed Fraction Calculator helps to convert the fraction . This calculator also simplifies proper fractions by reducing to lowest terms and showing the work involved.

**Comment by sairish2001** [comment]
Go ahead 
Deadline 24 April,2021 11:59 PM IST

**Comment by ShrutiOmer** [comment]
Improper to mixed fraction is already added in general maths (operation in fractions).
![image](https://user-images.githubusercontent.com/75009990/115697919-ab996e80-a381-11eb-8e09-c0c528b5f99b.png)

**Comment by sairish2001** [comment]
@ShrutiOmer Thanks for pointing out

**Comment by sairish2001** [comment]
@shrishti-c You can skip this issue
