### ISSUE TITLE
Cone under Calculator for 3-D Shapes not working

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1197]
## **Describe the bug**

- A clear and concise description of what the bug is.

I would like to work on this issue please assign this to me under GSSoC.

- Describe the solution you thought of.

## **Screenshots**
![22](https://user-images.githubusercontent.com/70858557/115141279-f7ce7100-a058-11eb-8a59-e23c655d5e4e.PNG)

**Comment by sairish2001** [comment]
Go ahead 
Deadline 24 April,2021 11:59 PM IST
