### ISSUE TITLE
Duality Law

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1201]
I would like to add about `logical equivalence` by mentioning `duality law` under `mathematical reasoning` section.

Duality Law:
Two formulas A and A* are said to be the duals of each other if either one can be obtained from the other by replacing '∧' by '∨' and '∨' by '∧'. The connective '∧' and '∨' are also called dual of each other.

I will provide logical identities as follows:

1. DeMorgan's laws
2. Associative laws
3. Commutative law
4. Idempotant laws
5. Double negation
6. Distributive laws
7. Absorption laws

**Comment by mehabhalodiya** [comment]
Kindky assign this issue to me under GSSoC.

**Comment by mehabhalodiya** [comment]
Kindly assign this issue to me under GSSoC.

**Comment by khareyash05** [comment]
@mehabhalodiya I had opened the same issue few days earlier and it was closed because of no requirement
