### ISSUE TITLE
Rolle's and Mean Value Theorem

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1202]
Hi ! I would like to add "Rolle's Theorem" and "Mean Value Theorem" about Differentiation.
Kindly assign this to me under GSSoC.

**Comment by RaveenaBhasin** [comment]
Are u adding a calculator for it? Because theorems are already present.

**Comment by mehabhalodiya** [comment]
Okay! Got it!
Thank you.
