### ISSUE TITLE
Adding calculator for heptagon

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1209]
Under calculator of shapes, I would like to add the calculator for regular heptagon. 
Please assign this to me under GSSoC.

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 April,2021 11:59 PM IST

**Comment by khareyash05** [comment]
Is this issue still open? Shall i work on this?

**Comment by mehabhalodiya** [comment]
Hey! I am working on this. Sorry for some delay as I am having my semester exams.

I will submit a PR for this by today.
