### ISSUE TITLE
Adding calculator for nonagon

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1210]
Under calculator of shapes, I would like to add the calculator for regular nonagon. 
Please assign this to me under GSSoC.

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 April,2021 11:59 PM IST

**Comment by khareyash05** [comment]
Is this issue open ? Shall i work on this?

**Comment by mehabhalodiya** [comment]
Hey! I am working on this. Sorry for some delay as I am having my semester exams.

I will submit a PR for this by today.
