### ISSUE TITLE
Adding area calculator using Heron's formula

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1222]
I would like to add a calculator for finding the area of a triangle when sides are given using Heron's Formula.

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 April,2021 11:59 PM IST

**Comment by sairish2001** [comment]
Implement this under, Shapes Calculator -> Triangle ->Scalene Triangle

**Comment by RaveenaBhasin** [comment]
@sairish2001 I'm sorry I didn't saw that there is already implementation of heron's formula under scalene triangle so should I close this issue/

**Comment by sairish2001** [comment]
Yes, close it
