### ISSUE TITLE
adding paraboloid to conic sections

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1227]
I would like to add paraboloid in conic sections

**Comment by sairish2001** [comment]
You mean to add a Calculator?

**Comment by khareyash05** [comment]
Yes user can enter in the required inputs a,b,c for the same and i wil show them the equation latus rectum ordinate and other things

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 April,2021 11:59 PM IST
