### ISSUE TITLE
Checking prime

### ISSUE THREAD

**Issue by anjali7786** [sairish2001/MakesMathEasy#123]
Can I add one more feature to find whether a number is prime or not?
I want to work on this issue under GSSOC'21. Please assign this to me.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 17 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
I would appreciate if you add
- Print prime numbers up to **n** calculator

along with checker

**Comment by anjali7786** [comment]
Thank you for assigning me this issue. I will add that also

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by lakshita15** [comment]
can you assign this to me. I eagerly want to contribute to this

**Comment by anjali7786** [comment]
Hii sir, please tell me whether I should put both calculators under one sidebar navigation menu or different.

**Comment by sairish2001** [comment]
Single navigation menu

**Comment by anjali7786** [comment]
Ok sir, I have to show or just make a PR
