### ISSUE TITLE
bug in UI of Euclid Geometry-Axioms and postulates in the light mode also enhance the ui

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1232]
## **Describe the bug**

- In light mode the some text of Euclid Geometry-Axioms and postulates does change its color to black. And it is hard to read white text in light mode 
- also the content is placed unevenly some are aligned to center some are aligned to right.

## **Possible solution**

- I would like to fix the colour issue in light mode and
- would align the whole content of the section to center like other sections has.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- ![m1](https://user-images.githubusercontent.com/61223163/115213014-bef8cf80-a11e-11eb-8433-18df76b0f351.PNG)
- ![m2](https://user-images.githubusercontent.com/61223163/115213045-c61fdd80-a11e-11eb-9346-11ced4a7084c.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 April,2021 11:59 PM IST
