### ISSUE TITLE
Fix the table in mathematical reasoning section

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1234]
## **Describe the bug**

- In light mode the table borders get disappears 
- the items on the table are left align

## **Possible solution**

- I will fix the border problem
- and centralize the items of the table

## **Screenshots**

- ![image](https://user-images.githubusercontent.com/61223163/115217074-c02bfb80-a122-11eb-9a4c-d6fc7c3c6272.png)

**Comment by sairish2001** [comment]
Recently merged PR made some chabges in the UI,  check them
