### ISSUE TITLE
Bug in octahedron calculator

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1238]
## **Describe the bug**

Surface area in octahedron calculator.
The displayed answer in incorrect.

## **Possible solution**

I would like to solve this to get correct answer.

Along with this, I will add diagonal formula too for octahedron.
Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 25 April,2021 11:59 PM IST
