### ISSUE TITLE
Bug in Tetrahedron

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1244]
## **Describe the bug**

The value of height is calculated wrong, I would like to fix this. Also I would like to add the formula of surface area and its calculation part since it is not there now.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![bb](https://user-images.githubusercontent.com/70858557/115252025-b87f4d80-a148-11eb-817c-aec3426e0410.PNG)

Please assign this to me

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
