### ISSUE TITLE
Adding diameter & radius for Cylinder

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1246]
## **Is your feature request related to a problem? Please describe.**

![bb](https://user-images.githubusercontent.com/70858557/115253463-09437600-a14a-11eb-84d7-469c6f7b695b.PNG)

## **Describe the solution you'd like**

- I would like to add the calculation of radius and diameter also for the cylinder shape calculator. 
- And I want to change the image since it is too small and labelling are barely visible. I'll create an image for the same. 

Please assign this to me under GSSoC.

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
