### ISSUE TITLE
I would like to add "Preloader " for home page

### ISSUE THREAD

**Issue by Raj142** [sairish2001/makesmatheasy#1254]
I want to add preloader at the home page whenever we refresh the page it shows loading animation untill home page is successfully refreshed.
please assign me it as a part of GSSoC'21.

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021

**Comment by Raj142** [comment]
Sir please check this preloader . 


https://user-images.githubusercontent.com/52609526/116084724-b32b8100-a6bb-11eb-80f7-845a88749a60.mp4

**Comment by sairish2001** [comment]
Great, But if possible make overlay, which covers whole screen and hides the main window while loading.

Can you use Makes Math Easy Logo in loading?

**Comment by Raj142** [comment]
Sir i need gif of Make Math Easy if you have. I tried many but not looks good.

**Comment by Ankita297** [comment]
@sairish2001 @shrey27tri01  can i work on this ?

**Comment by shrey27tri01** [comment]
@Raj142 Any updates on this issue? Anything you're stuck on?
