### ISSUE TITLE
Third option giving "NaN" in Percentage Calculator

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#1268]
## **Describe the bug**

Third option gives "NaN" in Percentage Calculator in General Maths section

## **Possible solution**

I would like to solve the problem

## **Screenshots**

![per](https://user-images.githubusercontent.com/57946528/115385632-fa1a0200-a1f5-11eb-934e-b26888e81c42.png)

Please assign it to me

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
