### ISSUE TITLE
Add social media icons

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1269]
## **Is your feature request related to a problem? Please describe.**

-Add social media icons under the connect with us section

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021

You just add the icons, I will link them with the links in future.
Go for
- Instagram
- Email
- LinkedIn
- Discord

**Comment by gnikita432** [comment]
Okay, I will add this icons.
