### ISSUE TITLE
Change suggestion in UI of SEARCH BAR 

### ISSUE THREAD

**Issue by shubhdeep123** [sairish2001/makesmatheasy#1273]
## Proposal

I would like to make some UI changes inSEARCH BAR. I think more light colour looks more pleasant to eyes while interacting with the site.
![Screenshot from 2021-04-20 19-49-40](https://user-images.githubusercontent.com/64921946/115412647-20e63180-a212-11eb-9c15-df6eb3fcede6.png)

![Screenshot from 2021-04-20 20-17-06](https://user-images.githubusercontent.com/64921946/115416547-812aa280-a215-11eb-8602-0351e6eed426.png)

**Comment by shubhdeep123** [comment]
I would like to work on this issue. So @sairish2001 can you please assign me this issue.

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 April, 2021

**Comment by shubhdeep123** [comment]
@sairish2001  can you please review the PR?
