### ISSUE TITLE
[GSSOC' 21] [ENHANCEMENT] Improving dark mode

### ISSUE THREAD

**Issue by Aditya201551** [sairish2001/makesmatheasy#1275]
## Proposal

I would like to enhance the modes of the site i.e improving light and dark mode, below are some pictures for reference: 

**Light Mode:** 

![Screenshot (102)](https://user-images.githubusercontent.com/32588231/115416973-dbc3fe80-a215-11eb-836a-64982472437c.png)

**Dark Mode:** 

![Screenshot (103)](https://user-images.githubusercontent.com/32588231/115417057-eed6ce80-a215-11eb-91ce-a79550f1c0e6.png)

**Transitions between modes:** 

https://user-images.githubusercontent.com/32588231/115418830-6eb16880-a217-11eb-9e52-e3c321ee9470.mp4

@sairish2001 I would like to work on this issue please assig me this issue, thank you!

**Comment by sairish2001** [comment]
Go ahead
Deadline 25 April,2021 11:59 PM IST

**Comment by sairish2001** [comment]
Try to change color of light mode

**Comment by Aditya201551** [comment]
@sairish2001 sir could you please tell me what type of color u want me to use in light mode, as many colors are creating conflicts with the heading color
