### ISSUE TITLE
Enhance the UI of bayes theorem in both light and dark mode

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1290]
## **Is your feature request related to a problem? Please describe.**

- Enhance the UI of bayes theorem in both light and dark mode
- 
![m3](https://user-images.githubusercontent.com/61223163/115560169-f5c31700-a2d1-11eb-8886-efdd71b80da1.PNG)

## **Describe the solution you'd like**

- The text alignment are uneven. I will make them all the text properly aligned
- will change the text colors accordingly
- In the light mode the colors are very uneven and hard to read instead of that colors I would like to use simple colors like this
![m2](https://user-images.githubusercontent.com/61223163/115560405-2dca5a00-a2d2-11eb-93ab-394b5f7fba8a.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
