### ISSUE TITLE
I want to add no.of forks , issues, stars in readme file .

### ISSUE THREAD

**Issue by nitinshukla413** [sairish2001/makesmatheasy#1293]
I want to add no. of forks, issues, stars in the readme file.
Example:
![image](https://user-images.githubusercontent.com/50632879/115577202-d7651780-a2e1-11eb-8000-e5fe84f1d657.png)

I want to work on this Please assign me this issue.

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
