### ISSUE TITLE
Some shapes calculation part is not working

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1294]
## **Describe the bug**

Below I have mentioned exact shapes whose calculation part is not showing up. I would like to work on this issue. Please assign this to me under GSSoC. 

- Cone
- Sphere
- Hollow sphere
- Hemisphere
- Torus
- Pentagonal hexagonal octagonal pyramid
- Octahedron

**Comment by madihamallick** [comment]
Please assign this to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 30 April,2021
