### ISSUE TITLE
[FEATURE] [GSSOC' 21] Adding backend to the app with django

### ISSUE THREAD

**Issue by Aditya201551** [sairish2001/makesmatheasy#1295]
## **Is your feature request related to a problem? Please describe.**

NA

## **Describe the solution you'd like**

- Adding backend to the app with Django so in future many new features like user log in, registration, saving favourite maths formula according to a user account, login with social media(Google, Facebook....etc) and many more features can be integrated with the project in later deployment

## **Note**

the backend part can be added to this repo as a separate branch and later it can be merged with the main branch during the initial deployment

I would like to work on this issue please assign me this issue

@sairish2001

**Comment by sairish2001** [comment]
Actually I want this application, to process in the client side only, without any server side interaction.

Can you please tell are you familiar with 
`djangorestframework` ?

**Comment by Aditya201551** [comment]
yes I have knowledge about Djangorest

**Comment by sairish2001** [comment]
I have a another repo. named makesmatheasyapi

so you can work on it

**Comment by Aditya201551** [comment]
Okay I will check it out and see what I can create

**Comment by shrey27tri01** [comment]
@Aditya201551 Since we are developing this as a client-side application, we have stalled our backend plans as of now.  You can work on the frontend issues!
Thanks!
