### ISSUE TITLE
parallelepiped working

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1297]
## **Describe the bug**

- The calculation part of this shape is not showing up due to bugs in the calculation part of the calculation. I would like resolve those.
- And I would like to make an image of parallelepiped shape and add here since it is missing here. 
 
Please assign this to me under GSSoC.

## **Screenshots**

![ss](https://user-images.githubusercontent.com/70858557/115602307-68e18300-a2fc-11eb-97bb-6d7cda3a293e.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
