### ISSUE TITLE
Design Homepage

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy#13]
![PicsArt_03-04-11.24.25.jpg](https://user-images.githubusercontent.com/60106112/110007602-df242900-7d40-11eb-811c-2bd2c4deaf82.jpg)

Add some features to make it more user friendly.
like
- API to display some facts

come up with your own ideas

**Comment by DeepanshuSarswat** [comment]
I would like to solve this problem as a part of girl Script Summer of code 2021

**Comment by sairish2001** [comment]
Sure!
Thanks for showing interest in this project.

**Comment by sairish2001** [comment]
Can you please tell me your ideas before implementation

**Comment by sairish2001** [comment]
Actually, it's a web App, not a website. So design accordingly.

**Comment by DeepanshuSarswat** [comment]
Initially for static design, I will use Html css  and Bootstrap. I will do the Java script for the API later.

**Comment by sairish2001** [comment]
Great!
Try to find out good API's related to Maths and implement them in homepage

**Comment by sairish2001** [comment]
Any update?

**Comment by sairish2001** [comment]
@DeepanshuSarswat Are you able to solve this issue. Any Update?

**Comment by DeepanshuSarswat** [comment]
@sairish2001  I am trying, I will update you soon

**Comment by DeepanshuSarswat** [comment]
can you please share Discord/Slack link for this Project ?

**Comment by sairish2001** [comment]
The server will be provided by GirlScript itself. Till now we don't have any server but. You can DM me anytime on Discord (username: sairish2001#7710)

**Comment by sairish2001** [comment]
12 March ,2021 is the deadline

**Comment by kumarishalini6** [comment]
Can I work on it??

**Comment by sairish2001** [comment]
@DeepanshuSarswat Deadline is near, are you able to solve this issue?

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.

**Comment by shrey27tri01** [comment]
Hey @rk05-lenavo, if you are not able to get assigned an issue, you can play around with the codebase and explore the application, try to find bugs or more features to add, create your own issues and we can assign those to you.

**Comment by aanchalrakheja** [comment]
i would like to work on this issue.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 20 March,2021 (11:59 PM IST)

**Comment by lakshita15** [comment]
i would like to work on this issue. i'll make the static page using html,scss, and react.Just tell me the basic requirements. i would love to work on this issue and will submit before deadline....

**Comment by sairish2001** [comment]
@lakshita15 Most of our issues are already assigned, I would suggest you to explore the application find the bug, or suggest a new Calculator. Make a issue by yourself and ask for assignment

**Comment by lakshita15** [comment]
> @lakshita15 Most of our issues are already assigned, I would suggest you to explore the application find the bug, or suggest a new Calculator. Make a issue by yourself and ask for assignment

okay

**Comment by aanchalrakheja** [comment]
> Feel free to ask your doubts, if any
> Deadline 20 March,2021 (11:59 PM IST)

SURE

**Comment by aanchalrakheja** [comment]
Hey! I tried creating this. It has an animated background wherein the color of blocks changes and creates a blinking effect. 
Should I continue to merge it with the original homepage. Please give some suggestions also if anything else can be added and your views on how this looks.
![image](https://user-images.githubusercontent.com/68388581/111453990-2b586b80-873a-11eb-85e6-aa906c078023.png)

**Comment by sairish2001** [comment]
If something related to Maths can be in the  background will be appreciable

**Comment by aanchalrakheja** [comment]
Ok will add some picture in the background related to maths.

**Comment by sairish2001** [comment]
also can you please show a video or gif of the animation

**Comment by aanchalrakheja** [comment]
I have added a picture related to maths as background.
![image](https://user-images.githubusercontent.com/68388581/111528689-78aefa00-8787-11eb-8723-c009fbeb28f0.png)


https://user-images.githubusercontent.com/68388581/111579903-d28ddf00-87dc-11eb-8f41-de036e373b10.mp4

**Comment by aanchalrakheja** [comment]
Hey! Is it okay?

**Comment by sairish2001** [comment]
It looks like a music website, but the images in the background is fine.
So kindly remove this blocks along with animation.

**Comment by aanchalrakheja** [comment]
okay.

**Comment by aanchalrakheja** [comment]
what if we add some operators instead of these blocks with some animation?

**Comment by aanchalrakheja** [comment]
something like this?
![image](https://user-images.githubusercontent.com/68388581/111645494-c29aed00-8826-11eb-9a0d-77bb072e7768.png)

**Comment by sairish2001** [comment]
This looks good! Do implement it in the `<div>` having `id="home"`

**Comment by aanchalrakheja** [comment]
the one with symbols right?

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue , I have experience in css and js .

**Comment by aanchalrakheja** [comment]
I have merged the design with the existing homepage. But there are some absurd bugs i m not able to detect.
![image](https://user-images.githubusercontent.com/68388581/111810996-9ce01780-88fc-11eb-9c30-1ef910b593b2.png)

**Comment by aanchalrakheja** [comment]
The line under the facts and the solve button at the bottom are the bugs

**Comment by aanchalrakheja** [comment]
I had a word with one of the mentor regarding the same and so made a PR request so that he could verify the code once. Can i please get some time of a day or two to fix it.

**Comment by shrey27tri01** [comment]
@aanchalrakheja You can keep working on this :)
New deadline is 23rd March, 2021, 11:59 PM IST

**Comment by sairish2001** [comment]
> or simply like this
> ![image](https://user-images.githubusercontent.com/68388581/111649881-c6c90980-882a-11eb-87a2-8ecd25c72b6f.png)
> 

Actually this design looks more like website rather than webapp. Try to use some API' s to display facts, or anything related to maths. It should provide information regarding maths rather than showing the application name.
