### ISSUE TITLE
Bug in incenter calculator 

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1301]
Circumcenter and incentre calculator has overlapped each other. I would like to solve this bug.
Please assign this issue to me
![Screenshot (1853)](https://user-images.githubusercontent.com/73697080/115651717-593c5b80-a349-11eb-8227-b06bd5dfdfeb.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 25 April,2021
