### ISSUE TITLE
sum of terms of A.P. not working

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1308]
the sum of terms of A.P. is not showing outputs
all the 3 arent working
![image](https://user-images.githubusercontent.com/60147732/115659110-ac1d0f80-a357-11eb-9c6c-956bcc4141e1.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021

**Comment by madihamallick** [comment]
Hi @khareyash05  this issue is solved now under this PR #1345 
This part is working now.
