### ISSUE TITLE
leap year not working

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1312]
The leap year functionality is not working
I would like to correct it also the input is not clearly visible
![image](https://user-images.githubusercontent.com/60147732/115659711-95c38380-a358-11eb-9e69-37ef3be84662.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021

**Comment by madihamallick** [comment]
Hi @khareyash05  this issue is solved now under this PR #1345 

![bb](https://user-images.githubusercontent.com/70858557/115921519-3a4cdf00-a499-11eb-9294-7296237dda1e.PNG)

The leap year functionality part is working now.
