### ISSUE TITLE
standard deviation sticky with other items

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1313]
The standard deviation is sticky with other items and thus answers aren't being calculated correctly
![image](https://user-images.githubusercontent.com/60147732/115660297-6d885480-a359-11eb-84f4-78022cea2a05.png)
![image](https://user-images.githubusercontent.com/60147732/115660323-7711bc80-a359-11eb-99fa-70da9197298f.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
