### ISSUE TITLE
Adding calculator for angle between two planes

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1317]
I would like to add a calculator for finding angle between two planes.
Please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021

**Comment by khareyash05** [comment]
@RaveenaBhasin I am actually working on distance between line and plane 
May i know where will u be placing these so that i too can place my similar issue there

**Comment by RaveenaBhasin** [comment]
@khareyash05 We can make a separate section for 3d geometry calculator or else we can just give a heading of 3d geometry in the coordinate geometry calculator section after the 2d calculators. What's your call on it?

**Comment by khareyash05** [comment]
@RaveenaBhasin let's create new section... I can create a new section... Will make a PR by evening

**Comment by RaveenaBhasin** [comment]
@khareyash05 Ok that will be fine

**Comment by khareyash05** [comment]
@RaveenaBhasin i have created a PR #1358
