### ISSUE TITLE
Bug in addition of fractions

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#1322]
## **Describe the bug**

- In explanation of addition of subtraction variables are not replaced with their values.

## **Screenshots**

![image](https://user-images.githubusercontent.com/75009990/115696750-953ee300-a380-11eb-9d77-464a3860391d.png)

**Comment by ShrutiOmer** [comment]
Please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
