### ISSUE TITLE
Prime numbers section is very close to the footer and it is not working.

### ISSUE THREAD

**Issue by Ananya-Misra** [sairish2001/makesmatheasy#1324]
## **Describe the bug**
The prime numbers section appears very close to the footer and Primality test and primes until entered number is not working.

## **Possible solution**
The prime numbers section is appearing very close to the footer rather than below the search bar. I would like to fix that and
I would like to modify the code for the Primality test and primes till entered no. Please assign this to me.

## **Screenshots**

![prime1](https://user-images.githubusercontent.com/70848031/115954669-d3b6d800-a50f-11eb-915c-7b819697b7b7.png)
![prime02](https://user-images.githubusercontent.com/70848031/115954777-72dbcf80-a510-11eb-9fea-6413e707ecf5.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021

**Comment by madihamallick** [comment]
Hi @Ananya-Misra this issue is solved now under this PR #1345 

![b1](https://user-images.githubusercontent.com/70858557/115921209-cf9ba380-a498-11eb-907e-5cae6b423d15.PNG)

This part is working now. You can close this.

**Comment by Ananya-Misra** [comment]
@sairish2001 I have put the pull request for the following issue. Please review it.
