### ISSUE TITLE
summary of quadrilateral table

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#1325]
## **Is your feature request related to a problem? Please describe.**

- Want to add summary of quadrilaterals in form of table in properties of quadrilateral.

## **Describe the solution you'd like**
It will we like this.
Please assign this issue to me.
![image](https://user-images.githubusercontent.com/75009990/115699290-26af5480-a383-11eb-929d-b473a95bb466.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021

Use Bootstrap Table classes
