### ISSUE TITLE
Most of the calculators are not working 

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1327]
## **Describe the bug**

-Most of the calculators are not working under binary calculation and Ap,GP and many more

## **Possible solution**

- bug in logicjavascripts.js or index.html some tag or semicolon should be missing

## **Screenshots**

- 
![image](https://user-images.githubusercontent.com/67696867/115711057-b4457100-a390-11eb-884a-83705c189be4.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by madihamallick** [comment]
This issue is resolved now.
