### ISSUE TITLE
List not alligned properly

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1331]
## **Describe the bug**

- List are not alligned properly

## **Screenshots**

- 
![image](https://user-images.githubusercontent.com/67696867/115737218-8d476900-a3a9-11eb-9efd-0446ee87d424.png)

List should be 

![image](https://user-images.githubusercontent.com/67696867/115737280-9df7df00-a3a9-11eb-9d87-0fe38fe71671.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
