### ISSUE TITLE
Clear button in calculator doesn't work properly

### ISSUE THREAD

**Issue by shrishti-c** [sairish2001/makesmatheasy#1335]
On clicking clear button, calculator doesn't clear completely the input section.

![Screenshot (228)](https://user-images.githubusercontent.com/73748606/115759000-6135e300-a3bd-11eb-8b85-47f1d2608fd1.png)

![Screenshot (227)](https://user-images.githubusercontent.com/73748606/115758933-4f544000-a3bd-11eb-9ba3-43bab8c59cb1.png)

**Comment by sairish2001** [comment]
Actually I don't want Answer field to be cleared, as sometimes we need the previous answers
