### ISSUE TITLE
Modify Binary/Decimal/Hexadecimal section to work for Fraction part also

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1337]
## **Is your feature request related to a problem? Please describe.**

- In binary/decimal/hexadecimal section it is not calculating for fractional part

## **Describe the solution you'd like**

- To add code in logicjavascript.js so that it would be able to calculate for fractional part

![image](https://user-images.githubusercontent.com/67696867/115762135-c3441780-a3c0-11eb-9b40-0ee905bec088.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
