### ISSUE TITLE
Add auto label of  gssoc on PR  opened 

### ISSUE THREAD

**Issue by Ankita297** [sairish2001/makesmatheasy#1339]
## **Is your feature request related to a problem? Please describe.**

I want to add github action to Add auto label of  gssoc 21 on PR  opened 
## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by Ankita297** [comment]
@sairish2001 can i work on this ?

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021
