### ISSUE TITLE
Dynamic copyright year and enhancement

### ISSUE THREAD

**Issue by SandeepKrSuman** [sairish2001/makesmatheasy#1340]
## **Is your feature request related to a problem? Please describe.**
- Currently the copyright year is hard-coded.
- Hard-coded data will have to be changed every time it changes.
- Also the copyright text is bit smaller. 
![Screenshot (291)](https://user-images.githubusercontent.com/54541515/115836199-d1cc1680-a434-11eb-8c37-a0eacfd31d04.png)

## **Describe the solution you'd like**
- I'll set dynamic year using js functions. So that it is updated automatically.
- increase font of copyright text

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 April,2021

Don't increase font size of this text
