### ISSUE TITLE
Add github action to auto reply every time a pr is opened...

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1346]
Add github action to send auto - message every time a pr is opened -> tht to wait till the mentors review your code.

...The message would be something like -  'We got you pr , kindly wait for our team to review it :)'
Or anything else as per your wish @sairish2001 .

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 May, 2021

Use this
"Our team will soon **review** your PR. Thanks :)"
