### ISSUE TITLE
[NOT AN ISSUE BUT A REDIRECTION]

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1347]
@sairish2001 By mistakenly you have missed some of the issue #1172  #1183 #1185 #1207  #1214 #1296 #1182 and #1352 
Kindly look into them and assign me

**Comment by sairish2001** [comment]
Go ahead with all

Deadline for each 2 May,2021

**Comment by khareyash05** [comment]
Thanx @sairish2001

**Comment by khareyash05** [comment]
@sairish2001 I will make the PR for all the remaning by tomorrow
