### ISSUE TITLE
Mean Calculator is not working 

### ISSUE THREAD

**Issue by Ankita297** [sairish2001/makesmatheasy#1357]
## **Describe the bug**

Mean Calculator is not working  and also it is not alligned properly .

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Makes Math Easy - Google Chrome 24-04-2021 08_40_31](https://user-images.githubusercontent.com/67833077/115945357-0a253080-a4d9-11eb-981b-4c7d4cf18525.png)

**Comment by Ankita297** [comment]
@sairish2001 can i work on this ?

**Comment by madihamallick** [comment]
Hi @Ankita297  this issue is solved now under this PR #1345 

![nn](https://user-images.githubusercontent.com/70858557/115948585-7fe6c780-a4ec-11eb-950c-6eef1daea0cc.PNG)


This part is working now.
