### ISSUE TITLE
Contents after properties of parallel line are not properly alligned

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#1362]
## **Describe the bug**

- Contents after properties of parallel lines ,properties of circle etc are showed after so much space. 
Please assign this issue to me. 

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot_2021-04-24-11-36-51-298_com android chrome](https://user-images.githubusercontent.com/75009990/115949261-74e26600-a4f1-11eb-9820-6567651c420a.jpg)

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 May,2021

**Comment by ShrutiOmer** [comment]
This bug gets rectified by someone already.
