### ISSUE TITLE
So many tools are not working

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#1364]
## **Describe the bug**
Javascript code written for some of the tools and calculator in `logicjavascript.js` is not working.

## **Possible solution**
I would like to rectify it, please assign it to me

**Comment by madihamallick** [comment]
This issue is resolved now. Please check it once :)

**Comment by shonali2600** [comment]
@madihamallick Ohh yess I checked, it's working now. Thanks for stating
