### ISSUE TITLE
Calculator being displayed at the end of page when clicking on calculator button (it is getting displayed when clicking on bar graph calculator)

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1367]
## **Describe the bug**

Calculator being displayed at the end of page when clicking on calculator button (it is getting displayed when clicking on bar graph calculator)

## **Possible solution**

There is bug in bar graph calculator 

## **Screenshots**

Bug
![image](https://user-images.githubusercontent.com/67696867/115956851-d8ce5400-a51c-11eb-8099-7cd11f4d1325.png)
After fixing the bug
![image](https://user-images.githubusercontent.com/67696867/115956882-02877b00-a51d-11eb-956f-a295513afafb.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by shonali2600** [comment]
Hey @abhijeet141, the calculator is displayed but at the bottom so you have to scroll down to see that, I am also thinking the same why is this happening, earlier it was fine. I am too a participant and would like to see its solution as I'm not able to figure it out.

**Comment by abhijeet141** [comment]
@shonali2600 Yes i did'nt notice that there is some bug in BarGraph calculator in index.html because of which this is happening

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 May,2021
