### ISSUE TITLE
In Plot Angle section input is not visible enough.

### ISSUE THREAD

**Issue by Ananya-Misra** [sairish2001/makesmatheasy#1369]
## **Describe the bug**

In the Plot Angle section, the input by the user is not clearly visible.

## **Possible solution**
I want to change the color of the input and increase the font to make it more visible.

## **Screenshots**

![plotangle02](https://user-images.githubusercontent.com/70848031/115957130-5cd50b80-a51e-11eb-92e3-f3f6e2f26794.png)

**Comment by ShrutiOmer** [comment]
I have made the same issue #1362 and just one small change is require then this section will also look fine.

**Comment by Ananya-Misra** [comment]
@ShrutiOmer  your bug is related to parallel line section while mine is related to plot angle section. The issue is a bit similar but I hope it won't cause any inconvenience.

**Comment by ShrutiOmer** [comment]
Yes its same but when I fix my bug your bug will get fix automatically.

**Comment by Ananya-Misra** [comment]
Ok @ShrutiOmer, I changed my issue to a different and simpler one. I hope now you don't have any issues with it.
