### ISSUE TITLE
To add calculator for Vector Addition

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1379]
## **Describe the solution you'd like**

- I would like to add Vector Addition Calculator.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 May,2021
