### ISSUE TITLE
To add calculator for Rectangular Prism

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1381]
## **Describe the solution you'd like**

-I would like to add calculator for Rectangular Prism

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by RaveenaBhasin** [comment]
@abhijeet141 I think Rectangular prism is cuboid only.

**Comment by abhijeet141** [comment]
> @abhijeet141 I think Rectangular prism is cuboid only.

Yess Thanks for telling 🙂
