### ISSUE TITLE
updating UI (left margins)

### ISSUE THREAD

**Issue by freeespirit** [sairish2001/makesmatheasy#1384]
## **Updating UI (especially left margins)**

Few webpages are missing **left margins** and they are not properly aligned.
![image](https://user-images.githubusercontent.com/67463253/115966560-ce777e80-a54b-11eb-8816-0aa35dc604b4.png)

**Comment by freeespirit** [comment]
Kindly assign me this issue sir @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 May,2021
