### ISSUE TITLE
Standard deviation is still sticky

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#1388]
## **Describe the bug**

-Standard deviation is still sticky to many calculators

## **Screenshots**

![image](https://user-images.githubusercontent.com/75009990/115969554-1520a500-a55b-11eb-8aaf-2ea181f3c087.png)

**Comment by ShrutiOmer** [comment]
Please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 May,2021
