### ISSUE TITLE
Interior angle of Polygon

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#1390]
## **Is your feature request related to a problem? Please describe.**

- In shapes calculator , I want to add option of interior angle measure of that shape.
- Or I can made a different calculator which takes side as input and give sum of interior angle and measure of each interior angle 
of n-sided regular polygon.

Please assign this issue to me and suggest in which way I should  add this option.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 May,2021

Implement into the shapes Calculator
