### ISSUE TITLE
Types of Relations and Functions

### ISSUE THREAD

**Issue by Ankita297** [sairish2001/makesmatheasy#1392]
## **Is your feature request related to a problem? Please describe.**

Types of relations:
Reflexive Symmetric
Transitive
Equivalence relations 
--
One to one and onto functions
Inverse of a function
 

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by Ankita297** [comment]
@sairish2001 can i work on this ?

**Comment by Ankita297** [comment]
@sairish2001 can i work on this ?

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 May,2021
