### ISSUE TITLE
Updating readme

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1399]
I would like to update the readme file by adding new sections which are recently added also there is some unwanted text present in the whole readme file which I will remove.
![Screenshot (1889)](https://user-images.githubusercontent.com/73697080/115987591-4a68d980-a5d3-11eb-97c3-806d1ac8a8c4.png)

**Comment by shonali2600** [comment]
@RaveenaBhasin , this issue has been resolved now, please have a look

**Comment by RaveenaBhasin** [comment]
@shonali2600 Ya thanks for telling... I'll add the stuff which is not present in readme file right now.

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 May,2021
