### ISSUE TITLE
many sections and calculator have moved to bottom and left corner

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1410]
## **Describe the bug**

- Some of the sections and calculator have also moved to the left side and at the bottom. One needs to scroll a lot to find them.

https://user-images.githubusercontent.com/61223163/115992342-d5a19980-a5ea-11eb-8764-f2609bb23123.mp4

## **Possible solution**

- I would like to solve this issue

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by abhijeet141** [comment]
@gnikita432 This Issue is already made by me please check Issue Number #1367

**Comment by gnikita432** [comment]
Ohh yes , sorry for opening a duplicate issue, closing this issue.
