### ISSUE TITLE
To make social media icon functional

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1412]
## **Describe the solution you'd like**

- Now clicking on Social media icons buttons they are not functional i would like to add links to make it functional

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 May,2021
