### ISSUE TITLE
The heading colour in lightmode UI | feature request 

### ISSUE THREAD

**Issue by akshay1027** [sairish2001/makesmatheasy#1422]
The heading colour in lightmode UI doesnot look clean IMO, it would be better if we choose some secondary other colour! 

red as heading colour is not good I feel:

![2021-04-26 (1)](https://user-images.githubusercontent.com/65683151/116010905-88034c00-a63f-11eb-80ac-1d464f21a0c2.png)

**Comment by akshay1027** [comment]
I would love to work on this issue @sairish2001, please let me know!

**Comment by sairish2001** [comment]
This issue is already created by someone

**Comment by akshay1027** [comment]
Ohh sorry, my bad! Please check my other issues! @sairish2001
