### ISSUE TITLE
Hover effects in calculator!

### ISSUE THREAD

**Issue by akshay1027** [sairish2001/makesmatheasy#1424]
## **Is your feature request related to a problem? Please describe.**
At the moment it's difficult to say if we have clicked a button, so if we add hover effects, UI of calculator will be clean!

**Comment by akshay1027** [comment]
I would love to work on this @sairish2001, please let me know!

**Comment by sairish2001** [comment]
Hover effects won't works, well in Mobiles. and I want not to hinder this under mobile view
