### ISSUE TITLE
About us page |  feature request

### ISSUE THREAD

**Issue by akshay1027** [sairish2001/makesmatheasy#1425]
## **Is your feature request related to a problem? Please describe.**
About us page with the following:
1) - [x] about us new project setup, simple layout, content
2) - [ ]  Footer for this 
3) - [x]  contact us form
4) - [ ]  backend for the same 
5) - [ ]  showcasing contributors in about us page 
6) - [ ]  FAQ page
7) - [ ] About us Link in navbar

**Comment by akshay1027** [comment]
I would love to work on them all and make these improvements @sairish2001

**Comment by sairish2001** [comment]
Go ahead

But hold the backend part, as we have not such planning of adding backend to this application, and before adding all these once check out the Contact Us page

**Comment by sairish2001** [comment]
Don't add footer to the webapp, as I want it to look more like a mobile application

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 May,2021

**Comment by akshay1027** [comment]
Hey brother It would be very Tough to implement all these by may 5th, each part is a level 3 in itself..! But surely I will try my best! Also I will make separate PR for each part as I told before ( each PR is a level 3 in itself and it takes time to do them) and tick the boxes here, so that you can also see my progress and give levels for each PR. I hope you understand the situation! Thanks

**Comment by akshay1027** [comment]
regarding footer, please check this out, i made this recently.. and please let me know if we need this for about us page! Thank you! @sairish2001 

![2021-05-01 (2)](https://user-images.githubusercontent.com/65683151/116771363-761f1000-aa68-11eb-9b8a-31255f5dd4c8.png)

**Comment by sairish2001** [comment]
Great **in About section** you can add. Looks Great :)
