### ISSUE TITLE
Hyperboloid adding steps

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1427]
## **Describe the bug**

**The calculator only shows the value of volume I will to add steps to it. Please assign this to me.**  

## **Screenshots**

![1a](https://user-images.githubusercontent.com/70858557/116068368-cf252780-a6a7-11eb-8e1b-bdb624f99f81.PNG)

**Comment by abhijeet141** [comment]
@madihamallick I think now it is working fine please check it once

**Comment by madihamallick** [comment]
> @madihamallick I think now it is working fine please check it once

Yep, thanks! I'll change the issue.
