### ISSUE TITLE
Centroid calculator at a random place

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1444]
Centroid calculator is placed at a random place in graphs and section and it should be present in the coordinate geometry section. I would like to remove it from it's present place and place in coordinate geometry calculator section with proper UI.
Please assign this issue to me.
![Screenshot (1894)](https://user-images.githubusercontent.com/73697080/116189154-27ab0200-a746-11eb-941e-198dc63080d1.png)

**Comment by khareyash05** [comment]
@RaveenaBhasin I have already opened the issue

**Comment by RaveenaBhasin** [comment]
@khareyash05 Ya sure...sorry I didn't checked it before.

**Comment by khareyash05** [comment]
No worries @RaveenaBhasin
