### ISSUE TITLE
Updating Sum of n terms of AP,GP and HP

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1446]
There are 3 different sections for finding the sum of n terms of AP, GP, and HP which makes the linear algebra section messy. I would like to make one section for Sum of N terms and include sum of n terms of AP, GP and HP in that only so as to avoid unnecessary sections.
Please assign this issue to me.
![Screenshot (1896)](https://user-images.githubusercontent.com/73697080/116190021-84f38300-a747-11eb-837e-092167ecd5c6.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 May,2021
