### ISSUE TITLE
Rhombic Dodecahedron Calculator

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1450]
Under calculator of 3D shapes, I would like to add the calculator for Rhombic Dodecahedron with:
Surface area (A), Volume (V), Midsphere radius (rm) and Insphere radius (ri)

Please assign this to me under GSSoC.

**Comment by shrey27tri01** [comment]
You can go ahead with the issue :)
Deadline 3 May 2021 11:59 PM IST
