### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#1459]
## Proposal

@sairish2001 I would like to update contributing.md and add the following in it  with proper steps -
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 May,2021

**Comment by sairish2001** [comment]
There's no need of this, as this section is already there in the ReadMe
