### ISSUE TITLE
Duplicate sections present

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1468]
In the general maths section, there are 3 duplicate sections for number of perfect cubes in a range. I would like to remove two of them.
Please assign this issue to me.
![Screenshot (1910)](https://user-images.githubusercontent.com/73697080/116351273-082cdb80-a811-11eb-80fc-3480aa83ba90.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 May,2021
