### ISSUE TITLE
Updating hover color of social icons.

### ISSUE THREAD

**Issue by ansi22** [sairish2001/makesmatheasy#1471]
Updating hover color will enhance the look. 
Would like to work on it, @sairish2001 Kindly let me know.

![Screenshot (88)](https://user-images.githubusercontent.com/76901399/116373955-7d0d0f00-a82b-11eb-9518-aa5e24777ece.png)

**Comment by ansi22** [comment]
@sairish2001 sir kindly assign it to me.

**Comment by sairish2001** [comment]
How would you improve the Hover effect?

**Comment by ansi22** [comment]
by changing the grey color to pink.
![WhatsApp Image 2021-05-01 at 11 50 09 AM](https://user-images.githubusercontent.com/76901399/116773599-d6677f00-aa73-11eb-885c-83646e72159c.jpeg)

**Comment by sairish2001** [comment]
I think your codebase is not updated, Color is already there.
