### ISSUE TITLE
Bug in icosahedron

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1477]
## **Describe the bug**

- Firstly, while we enter the side of the icosahedron, it only displays volume instead of both surface area and volume.

![bug](https://user-images.githubusercontent.com/73488906/116397269-092b3080-a844-11eb-81df-b68e2cffbd64.png)

- Secondly, even there's no input in `Enter the side` bar it is showing some stuff (i.e. previous output) instead of blank space.

![bug2](https://user-images.githubusercontent.com/73488906/116398572-91f69c00-a845-11eb-9b35-b4cfa98ae771.png)

## **Possible solution**

I will solve this issue by modifying some piece of code for regular icosahedron.
After solving, it will show both volume and surface area.

Also, when there will be no input then it will show blank space.

**Comment by sairish2001** [comment]
Go ahead
Deadline 6 May,2021
