### ISSUE TITLE
Bug in tetrahedron

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1478]
## **Describe the bug**

- Firstly, while we enter the side of the tetrahedron, it only displays 4 out of 5 parameters ( i.e. volume is not displayed ).

![bug3](https://user-images.githubusercontent.com/73488906/116400018-2d3c4100-a847-11eb-9971-1e50e13bac91.png)

- Secondly, even there's no input in `Enter side` bar it is showing one parameter (i.e. related to previous output) instead of blank space.
- Additionally, surface area is having too many digits after decimal point.

![bug4](https://user-images.githubusercontent.com/73488906/116400084-3f1de400-a847-11eb-9ce8-62972a6326a5.png)

## **Possible solution**

I will solve this issue by modifying some piece of code for tetrahedron.
After solving, it will show all 5 parameters.
I will fix decimal digits of particular output.

Also, when there will be no input then it will show blank space.

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 May,2021
