### ISSUE TITLE
To add calculator for calculating cross product of a vector

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1486]
## **Is your feature request related to a problem? Please describe.**

- I would like to add a calculator for calculating cross product of a vector

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 May,2021
