### ISSUE TITLE
vector subtraction +- symbol come together

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1492]
## **Describe the bug**

vector subtraction +- symbol come together

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![image](https://user-images.githubusercontent.com/59261812/116501259-fcebb580-a8cd-11eb-9014-59a6b7dd5438.png)

- If applicable, add screenshots to help explain your problem.

**Comment by satyampgt4** [comment]
@sairish2001 i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 6 May,2021

Also convert the output equation to LaTeX Text
