### ISSUE TITLE
Commets on New Issues and PR

### ISSUE THREAD

**Issue by Sukriti-sood** [sairish2001/makesmatheasy#1511]
Reference to This issue [#74](https://github.com/sairish2001/makesmatheasy/issues/74) 

## **Describe the solution you'd like**

-  This GitHub bot will comment on Every New Issue Created. 
-  And Will also tag user  with its username

**Comment by AB-san** [comment]
"This Github bot will comment on Every PR got merged." except this feature , all other features are already available

**Comment by Sukriti-sood** [comment]
> "This Github bot will comment on Every PR got merged.
> And Will also tag user with its username"
> except theses feature , all other features are already available

Current github bot only comments on issues and users for first time contributers not for all.
![Screenshot from 2021-04-30 15-56-27](https://user-images.githubusercontent.com/55010599/116683112-c5affe00-a9cc-11eb-94d3-edec86338429.png)

**Comment by AB-san** [comment]
> > "This Github bot will comment on Every PR got merged.
> > And Will also tag user with its username"
> > except theses feature , all other features are already available
> 
> Current github bot only comments on issues and PR for first time contributers not for all.
> This issue for justification [#1516](https://github.com/sairish2001/makesmatheasy/issues/1516)

Sorry check i have edited my comment.

**Comment by sairish2001** [comment]
Go ahead
Deadline 6 May,2021

You can create a bot, which comment on every newly created issue

**Comment by Sukriti-sood** [comment]
@sairish2001Currently there are 3 files for auto comments for merging ,opening and one for greeting for first time contributors,[Auto_msg_on_pr_merge]{https://github.com/sairish2001/makesmatheasy/blob/main/.github/workflows/Auto_message_on_pr_merge.yml} ,[Auto_msg_on_pr_open]{https://github.com/sairish2001/makesmatheasy/blob/main/.github/workflows/Auto_message_on_pr_open.yml} ,[greeting]{https://github.com/sairish2001/makesmatheasy/blob/main/.github/workflows/greetings.yml} I wanted to include all of the functionality in Single  file including thr functionality of comment of every issue. Should I do that or include new file which will include single functionality.

**Comment by AB-san** [comment]
> @sairish2001 Currently there are 3 files for auto comments for merging ,opening and one for greeting for first time contributors,[Auto_msg_on_pr_merge](https://github.com/sairish2001/makesmatheasy/blob/main/.github/workflows/Auto_message_on_pr_merge.yml) ,[Auto_msg_on_pr_open](https://github.com/sairish2001/makesmatheasy/blob/main/.github/workflows/Auto_message_on_pr_open.yml) ,[greeting](https://github.com/sairish2001/makesmatheasy/blob/main/.github/workflows/greetings.yml) I want to include all of the functionality in Single file including the functionality of comment of every issue. Should I do that or include new file which will include single functionality.

Auto_msg_on_pr_merge ,Auto_msg_on_pr_open ,greeting  both actions are triggered in different events , one when pr is merged/closed and other when pr is opened.

**Comment by Sukriti-sood** [comment]
@AB-san It can be integrated in single yml file by including all events.

**Comment by AB-san** [comment]
> @AB-san It can be integrated in single yml file by including all events.

Oho sorry I didn't knew that😅
Don't mind
