### ISSUE TITLE
Add working steps of subtraction of decimal numbers

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1527]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by AB-san** [comment]
i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 7 May,2021
