### ISSUE TITLE
Adding local storage accessibility to favourite topics

### ISSUE THREAD

**Issue by ritik307** [sairish2001/makesmatheasy#1543]
## **Is your feature request related to a problem? Please describe.**

- When a user selects a topic as their favourite they can only access it with the page isn't refreshed. As soon as the user refreshes the page the favourite record is lost a.ka. the site is not persisting the user's favourite data.

## **Describe the solution you'd like**

- I would like to propose the solution by implementing local storage accessibility to store the user's favourite data so that when the user even refreshes the page the favourite data still be accessible to him/her.

**Comment by ritik307** [comment]
@sairish2001 @shrey27tri01 @apekshamanchanda I would like to work on this issue plz assign.

**Comment by ritik307** [comment]
> 
> 
> Hi 😄, thanks for creating your first issue at makemathseasy, do read and follow the [Code of Conduct](https://github.com/sairish2001/makesmatheasy/blob/main/CODE_OF_CONDUCT.md) and the [Contribution Guidelines](https://github.com/sairish2001/makesmatheasy/blob/main/CONTRIBUTING.md) while contributing.

haan haan chal chal baap ko sikha

**Comment by sairish2001** [comment]
Local storage feature to this, favourite section is already implemented, check it once

**Comment by ritik307** [comment]
@sairish2001  I checked it when I refreshed the page the data was lost.
