### ISSUE TITLE
Add a loading state to numberfact

### ISSUE THREAD

**Issue by N-Shar-ma** [sairish2001/makesmatheasy#1546]
## **Describe the bug**

- Currently, the number fact takes quite a few seconds to load up, and till then the page looks very empty

## **Possible solution**

- While it loads, a text message saying "Loading number fact..." can be in it's place for better user experience
## **Screenshots**

- On opening the page, this is how empty it looks:
![image](https://user-images.githubusercontent.com/68962290/116754242-3d762c80-a9bd-11eb-9eae-2fba193c1e56.png)

- Here is how I propose it should look instead while the number fact loads up:
![image](https://user-images.githubusercontent.com/68962290/116754365-74e4d900-a9bd-11eb-8eda-1fa90d0a843e.png)

**Comment by sairish2001** [comment]
Actually issue is created for removing the AJAX request, which is increasing the loading time
