### ISSUE TITLE
To enhance the UI of Properties of Matrices and Determinant

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1552]
## **Is your feature request related to a problem? Please describe.**

I would like to use Latex to enhance the UI of Properties of Matrices and Determinant

![image](https://user-images.githubusercontent.com/67696867/116771481-681dbf00-aa69-11eb-986a-465b01190764.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 May,2021

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 May,2021
