### ISSUE TITLE
vector sum +- symbol come together and cap over unit vector is missing in output

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1558]
## **Describe the bug**

- vector sum +- symbol come together
- cap over unit vector is missing in output

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- 
![image](https://user-images.githubusercontent.com/59261812/116774339-9c00e080-aa79-11eb-9990-f99ce658d593.png)

**Comment by satyampgt4** [comment]
@sairish2001 i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021

Use LaTeX text for output
