### ISSUE TITLE
Sector of Circle

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1560]
![bug](https://user-images.githubusercontent.com/70858557/116776710-aa55f900-aa87-11eb-8611-bcc8925b8d1c.PNG)

**The calculation part is not showing up. I would like to work on this issue please assign this to me.**

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
