### ISSUE TITLE
To add steps of calculation in sum of squares of n Natural Numbers and sum of cubes of n Natural Numbers

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1565]
## **Is your feature request related to a problem? Please describe.**

To add steps of calculation in sum of squares of n Natural Numbers and sum of cubes of n Natural Numbers

![image](https://user-images.githubusercontent.com/67696867/116779389-d2e3f000-aa93-11eb-8629-5589c3e6b6c6.png)
![image](https://user-images.githubusercontent.com/67696867/116779398-decfb200-aa93-11eb-8a52-cbc3f86beaf2.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 May,2021
