### ISSUE TITLE
bug in fav icon of vector calculator 

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1567]
## **Describe the bug**

- while select vector calculator for favorite, fav icon of vector calculus get change to red 

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/59261812/116784976-c15f1000-aab4-11eb-91a9-858351cf8b9b.png)

- If applicable, add screenshots to help explain your problem.

**Comment by satyampgt4** [comment]
@sairish2001 i would like to work on this issue

**Comment by khareyash05** [comment]
@satyampgt4 As per rules of Open Source, One should wait for assignment before creating a PR . Please look into that in the future
