### ISSUE TITLE
Make sidebar responsive

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1569]
I want to make sidebar responsive.
[GSSOC'21]

Screenshot:

![sidebar](https://user-images.githubusercontent.com/66208607/116785193-ddaf7c80-aab5-11eb-8fa2-ff24b00a248f.png)

Pleased assign me this issue @sairish2001

**Comment by Bhavya-Sehgal** [comment]
@sairish2001 Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
