### ISSUE TITLE
The calculator in mobile view should have same button sizes 

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1574]
## **Describe the bug**

- The calculator in mobile view don't have equal size of buttons.
- Also it is not properly in center.
## **Possible solution**

- I would like to work on this issue.

## **Screenshots**

![image](https://user-images.githubusercontent.com/61223163/116788386-d93f8f80-aac6-11eb-953f-6dff2a4461fc.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
