### ISSUE TITLE
Add value of area and parameter under 'Calculator for Shapes' section

### ISSUE THREAD

**Issue by anjali494** [sairish2001/makesmatheasy#158]
In the calculator for shapes section, the values for parameter and area is not displayed for isosceles, right-angled and scalene triangle.

I am a GSSOC'21 participant and would like to work on ad fix this issue.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 19 March,2021 (11:59 PM IST)

**Comment by anjali494** [comment]
@sairish2001 to find the area of a scalene triangle, the formula given is 1/2bh but we will have to do it using heron's formula. I wanted to ask if i can change the change the formula given?

**Comment by sairish2001** [comment]
Yes Sure! Change it

**Comment by anjali494** [comment]
@sairish2001 can i get a little more time then. I am also working on another issue for this project.

**Comment by lityest** [comment]
Which issue?

**Comment by sairish2001** [comment]
Which issue?

**Comment by anjali494** [comment]
#187

**Comment by sairish2001** [comment]
Deadline extended 21 March,2021 (11:59 PM IST)

**Comment by anjali494** [comment]
@sairish2001 thank you.

**Comment by janvi01** [comment]
I would like to add calculation for trapezium, parallelogram and fix bug in ellipse . 
@sairish2001 
should I create new issue?
