### ISSUE TITLE
Update modal of settings section

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1581]
I want to make it responsive and change the layout of text.

[GSSOC'21]

Screenshot:
![modal](https://user-images.githubusercontent.com/66208607/116791417-dac58380-aad7-11eb-824e-0fa7853f4419.png)

Please assign me this issue @sairish2001

**Comment by Bhavya-Sehgal** [comment]
@sairish2001 Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
