### ISSUE TITLE
Add link addresses to the icons in sidebar

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1582]
Currently the links are not working of the sidebar. I would love to add link addresses .

[GSSOC'21]

Please assign me this issue @sairish2001

**Comment by abhijeet141** [comment]
@Bhavya-Sehgal This Issue has already been made please check Issue Number #1412

**Comment by Bhavya-Sehgal** [comment]
Ohh okay
