### ISSUE TITLE
Orthocenter Calculator

### ISSUE THREAD

**Issue by shrishti-c** [sairish2001/makesmatheasy#1586]
A tool where one can easily find the orthocenter of any triangle, be it right, obtuse or acute. 
I'd like to work on it.

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021

**Comment by khareyash05** [comment]
@sairish2001 Shall i work on this?

**Comment by shrishti-c** [comment]
I've unassigned myself.. You can work on it

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 May,2021
