### ISSUE TITLE
Link in Share to Whatsapp is not updated

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1593]
## **Describe the bug**

Link in Share to Whatsapp is not updated

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by khareyash05** [comment]
@abhijeet141 Just a suggestion , You should prefer waiting for the assignment before creating a PR

**Comment by abhijeet141** [comment]
> @abhijeet141 As per rules of Open Source, One should wait for assignment before creating a PR . Please look into that in the future

@khareyash05 Thanks for pointing this i will take care of this from next time :)
