### ISSUE TITLE
Add steps to explain solution in output in vector dot product

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1602]
## **Is your feature request related to a problem? Please describe.**

- Add steps to explain solution in output in vector dot product

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by satyampgt4** [comment]
@sairish2001 i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
