### ISSUE TITLE
Bug in sum of infinite term of GP

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1610]
## **Describe the bug**

Actually any input i am taking output is same that is "Enter Numbers only.Blank inputs are not allowed"

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/116811363-8ddcbe00-ab66-11eb-96b4-26df0d1a5f7e.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 May,2021
