### ISSUE TITLE
Add Reset button to all the calculators

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1611]
I want to add reset button to all the calculators so that user can reset the value of the text he added earlier .
This will make calculators user-friendly.

[GSSOC'21]

Please assign me this issue @sairish2001

**Comment by Bhavya-Sehgal** [comment]
@sairish2001 Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 May,2021
