### ISSUE TITLE
Addition of Armstrong Number Checker

### ISSUE THREAD

**Issue by shubhdeep123** [sairish2001/makesmatheasy#1622]
## **Is your feature request related to a problem? Please describe.**

- I wanted to add a feature which is related to armstrong number checker and armstrong numbers till entered numbers.

**Comment by shubhdeep123** [comment]
@sairish2001 i am working on this issue

**Comment by khareyash05** [comment]
@shubhdeep123 I had already created the same issue before but It was closed due to irrelevance ..Kindly close this issue and PR

**Comment by khareyash05** [comment]
@shubhdeep123  As per rules of Open Source, You should wait for assignment before creating a PR .. KIndly look into it in the future
