### ISSUE TITLE
Compound Interest Calculator

### ISSUE THREAD

**Issue by shubhdeep123** [sairish2001/makesmatheasy#1636]
## Proposal

I would like to add compound interest calculator

**Comment by shubhdeep123** [comment]
@sairish2001  i would like to work on this issue

**Comment by abhijeet141** [comment]
@shubhdeep123 Please check site once compound interest calculator is already present

**Comment by shubhdeep123** [comment]
@abhijeet141 it wasn't mentioned in search bar.
