### ISSUE TITLE
Bin/dec/hex/oct no.sys under one button

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1644]
## Proposal

Although we have any base to any base converter 
but still bin,dec,hexa,oct are the widely used number systems. So i would like to move all those converters under one tab

**Comment by AB-san** [comment]
If it sounds good to u @sairish2001  i would like to work on it

**Comment by sairish2001** [comment]
Go ahead
Deadline 9 May,2021
