### ISSUE TITLE
Add working steps of binary/grey-code convert

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1645]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

![image](https://user-images.githubusercontent.com/71064674/116928039-24e66a80-ac7a-11eb-98cf-0596edb41823.png)

Add working steps for this converter

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
