### ISSUE TITLE
Add working steps for decimal/greycode converter

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1646]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

![image](https://user-images.githubusercontent.com/71064674/116928196-5f500780-ac7a-11eb-8ac2-4eec59bc23d7.png)

Add working steps under this

**Comment by AB-san** [comment]
i wud lk 2 wrk on dis isu

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
