### ISSUE TITLE
Minor bug in subtraction of any no. system

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1647]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/116928441-b35aec00-ac7a-11eb-9fcb-c9e6c718aae2.png)

On changing the number system type , the function for subtraction is being called due to which working steps is shown even if we have not yet given inputs. The function must be called only on clicking the find button

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
