### ISSUE TITLE
To Add calculator  Hamming Code generator ( Encoding a message from left to right manner)

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1651]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

Add the concept of Encoding a message in Hamming Code

in encoding a message by hamming code , different results come out when data bits are in right to left / left to right manner

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
