### ISSUE TITLE
Minor bug in documentation

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1662]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.
**
![image](https://user-images.githubusercontent.com/71064674/116935392-ec4b8e80-ac83-11eb-8e15-ccbf1c455488.png)
**

**Comment by AB-san** [comment]
i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
