### ISSUE TITLE
theorems on differentiation button under calculus isnt working

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1663]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by AB-san** [comment]
i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
