### ISSUE TITLE
tetrahexahedron calculator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1667]
## **Is your feature request related to a problem? Please describe.**

Hi I would like to make a tetrahexahedron calculator (
Edge length cube (a): |   |, Edge length pyramid (b): |   |  ,Height (h): |   |  ,Surface area (A): |   |  ,Volume (V): |   |  ,Midsphere radius (rm): |   |  ,Insphere radius (ri): |   |  ,Surface-to-volume ratio (A/V):)

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
