### ISSUE TITLE
To add table under section decimal/bcd converter  for better understanding

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1668]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/71064674/116939947-cbd30280-ac8a-11eb-9ea6-7693192836e4.png)

**Comment by AB-san** [comment]
i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
