### ISSUE TITLE
To add table under section decimal/2421 convertor for better understanding

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1669]
## **Is your feature request related to a problem? Please describe.**

To add table under section decimal/2421 convertor for better understanding

![image](https://user-images.githubusercontent.com/67696867/116940158-24a29b00-ac8b-11eb-83a8-9693dd72e361.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
