### ISSUE TITLE
To add table under section decimal/excess3 converter for better understanding

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1670]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**
| ![image](https://user-images.githubusercontent.com/71064674/116940125-1785ac00-ac8b-11eb-9286-f7708d5b2d75.png) | ![image](https://user-images.githubusercontent.com/71064674/116940174-2f5d3000-ac8b-11eb-9d81-135d834466ab.png) |

**Comment by AB-san** [comment]
i  would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
