### ISSUE TITLE
Root Mean Square Calculator

### ISSUE THREAD

**Issue by shrishti-c** [sairish2001/makesmatheasy#1678]
Root Mean Square Calculator for data analysis programmed to calculate the RMS or Root Mean Square or Quadratic Mean for set of varying data. In data analysis many situations involving Voltage, Current, Speed, Velocity, Distance, Magnitude, it is necessary to calculate the Root Mean Square Value for a set of data with varying quantity.

I'd like to work on it.

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 May,2021
