### ISSUE TITLE
bug in the heart which selects the favorite.

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1682]
## **Describe the bug**

- bug in the heart which selects the favorite.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/61223163/116984661-1be0b200-ace9-11eb-8aa5-40657f1f06ad.png)

**Comment by abhijeet141** [comment]
@gnikita432 I think now this bug has been resolved please check it once :)

**Comment by gnikita432** [comment]
Yes, It has been solved.

**Comment by abhijeet141** [comment]
@gnikita432 I think you can change your issue that on clicking on Residue Methods nothing is displayed :)
