### ISSUE TITLE
Wrong output of Diagonal of parallelepiped under parallelepiped calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1690]
## **Describe the bug**

Wrong output of Diagonal of parallelepiped under parallelepiped calculator

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/117028861-bb1e9d00-ad1b-11eb-85dc-c19d288a58ac.png)

The diagonal should be -

![image](https://user-images.githubusercontent.com/67696867/117028951-d1c4f400-ad1b-11eb-87d3-49fd95933698.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
