### ISSUE TITLE
Half life calculator

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#1706]
A calculator that calculates half life when `quantity remains`, `initial quantity` or `time` any one of them is given.
I would like to add this.

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021

**Comment by khareyash05** [comment]
@sairish2001 Shall i work on this as the dealine for the same is over

**Comment by shonali2600** [comment]
@khareyash05 , I'm working on this. It's delayed due to some health issues. I'll raise the PR in the Evening
