### ISSUE TITLE
Confidence Interval calculator

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#1707]
A calculator that calculates confidence interval when `Sample size`, `Sample Mean` and `Standard Deviation` is given.
I would like to add this tool

**Comment by khareyash05** [comment]
@sairish2001 Shall i work on this as the deadline for the same is over

**Comment by shonali2600** [comment]
@khareyash05 , I'm working on this. It's delayed due to some health issues. I'll raise the PR in the Evening
