### ISSUE TITLE
fix identities 

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#1714]
## **Describe the bug**

![image](https://user-images.githubusercontent.com/59261812/117119500-c7ecd080-adaf-11eb-987e-23deca9db991.png)

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by satyampgt4** [comment]
i would like to work on it

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021
