### ISSUE TITLE
Two duplicate calculators in different sections.

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1725]
There are two calculators for finding slope of a line situated in graphs and shapes and coordinate geometry calculator. I would like to remove it from coordinate geometry section.
![Screenshot (1944)](https://user-images.githubusercontent.com/73697080/117141520-435c7b00-adcc-11eb-8b81-953611d849ed.png)
![Screenshot (1943)](https://user-images.githubusercontent.com/73697080/117141596-58d1a500-adcc-11eb-8ae0-059ca4d3f20b.png)

**Comment by sairish2001** [comment]
Check whether they both works in same, way. 
I think Line Parallel to given line.....etc

this is not there in the shapes Calculator, so I would suggest you to delete from coordinate geometry and move the Calculator into the modal.

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021

**Comment by RaveenaBhasin** [comment]
@sairish2001 Ya sure I'll make the required changes in the modal

**Comment by RaveenaBhasin** [comment]
@sairish2001 The slope calculator in the shape section and coordinate geometry section is working exactly. So can you please elaborate on what exactly do I need to add in the shape section?
