### ISSUE TITLE
Wrong output in Sum of squares of N Natural Numbers and Sum of cubes of N Natural Numbers

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1731]
## **Describe the bug**

Wrong output in Sum of squares of N Natural Numbers and Sum of cubes of N Natural Numbers when i am taking input as negative number it is displaying result and as we know that natural numbers are positive numbers only.

![image](https://user-images.githubusercontent.com/67696867/117142745-b0244500-adcd-11eb-9eef-73209a9b7ed0.png)
![image](https://user-images.githubusercontent.com/67696867/117142826-c7633280-adcd-11eb-80df-2858298bdca0.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 May,2021
