### ISSUE TITLE
Two copyright section on Website

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1736]
## **Describe the bug**

Two copyright section on Website

## **Screenshots**
![image](https://user-images.githubusercontent.com/67696867/117162830-c091eb00-ade0-11eb-91a2-3ee79625a620.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 May,2021
