### ISSUE TITLE
fav icon bug

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#1739]
## **Describe the bug**

- There is bug in fav icon. It is showing big blue heart. I would like to solve this bug.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- 
![image](https://user-images.githubusercontent.com/61223163/117172678-a6a8d600-ade9-11eb-9f6d-2d45c3b70a28.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021
