### ISSUE TITLE
Add calculator to find vol of parallelopiped whose adjacent sides are represented by vector a,b and c

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1748]
## **Is your feature request related to a problem? Please describe.**

formula used here- 
a.(bXc) where abc are vectors

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by AB-san** [comment]
plz assign me

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021

**Comment by khareyash05** [comment]
@sairish2001 SHall i work on this as the deadline is over?

**Comment by AB-san** [comment]
> @sairish2001 SHall i work on this as the deadline is over?

m stilll working on it
