### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1753]
Links in the sidebar lacks visibility . I want to change the CSS of them. Also the order of sections should be :
Home , About then other sections leading to contact settings and links at end. I would like to make these changes.

Screenshot:
![visibilty](https://user-images.githubusercontent.com/66208607/117195238-aff26c80-ae02-11eb-97ae-f715a713d8df.png)

Please assign me this issue @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021
