### ISSUE TITLE
Make favourite section responsive

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1754]
I want to make favourite section responsive.

Screenshots:
![fav](https://user-images.githubusercontent.com/66208607/117196217-d95fc800-ae03-11eb-8772-2c2001d80149.png)
![fav2](https://user-images.githubusercontent.com/66208607/117196391-09a76680-ae04-11eb-8ebc-1ae4e513a636.png)

Please assign me this issue @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021
