### ISSUE TITLE
Adding steps for Pythagorean triplets

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1755]
Currently this tool only displays the three Pythagorean triplets when a number is entered. 
- **I would like to add a bit about Pythagorean triplets**
- **And I will add steps as how we are getting the triplets when the number entered is even or odd respectively**. 

Please assign this to me.

![fix1](https://user-images.githubusercontent.com/70858557/117198204-5ab85a00-ae06-11eb-9c49-7c9c9820c310.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021
