### ISSUE TITLE
Bug in scalar Triple Product

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1757]
## **Describe the bug**

When i take all input and click on find button nothing is visible under solution

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/117199540-ef6f8780-ae07-11eb-89ff-eb92b99185da.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 May,2021

**Comment by abhijeet141** [comment]
@sairish2001 I have resolved this issue in one of my PR so i am closing this issue :)
