### ISSUE TITLE
Direct and Indirect Proportion Calculator

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1758]
**Direct and Indirect Proportion Calculator is not working.** 

I would like to work on this issue. please assign. 

![issss](https://user-images.githubusercontent.com/70858557/117199747-3198c900-ae08-11eb-8f28-d9c7fd9a2e81.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021
