### ISSUE TITLE
Add calculator  to find area of parralallelogram whose diagonal vecotor(ex -> a and b) are given

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1763]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021

**Comment by AB-san** [comment]
@sairish2001 I just now realised theres already a calculator which calculates area of quadrilteral and this one comes under it 
so instead of that can i work on making a "age calculator" that will take birthday ,year and show the age?

**Comment by sairish2001** [comment]
> @sairish2001 I just now realised theres already a calculator which calculates area of quadrilteral and this one comes under it 
> so instead of that can i work on making a "age calculator" that will take birthday ,year and show the age?

I think this Calculator is out of from the maths topic a little bit.
