### ISSUE TITLE
[GSSoC '21] Adding Fourier Series

### ISSUE THREAD

**Issue by amrzaki2000** [sairish2001/makesmatheasy#177]
Hello,
I want to add Fourier Series in the calculus section as part of my GSSoC participation.
Thank you

**Comment by sairish2001** [comment]
You want to add Calculator?

**Comment by amrzaki2000** [comment]
> 
> 
> You want to add Calculator?

It will be like the integrals calculator one, but instead it should be able to compute fourier series coefficients.

**Comment by sairish2001** [comment]
Feel free to ask your doubts,if any

Deadline 20 March,2021 (11:59 PM IST)

**Comment by amrzaki2000** [comment]
> Feel free to ask your doubts,if any
> 
> Deadline 20 March,2021 (11:59 PM IST)

@sairish2001 Hello
Almost finished and I'll make my PR by tomorrow morning if you please.
Thanks

**Comment by sairish2001** [comment]
Sure!

**Comment by khareyash05** [comment]
Hey @sairish2001 if this issue is free.. Could you pls assign this to me

**Comment by sairish2001** [comment]
@amrzaki2000 any Update?

**Comment by amrzaki2000** [comment]
> @amrzaki2000 any Update? Today is last day

Can I get one more day, please?
I got distracted due to the beginning of my spring semester

**Comment by sairish2001** [comment]
Deadline extended 22 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
@amrzaki2000 Do want to work on this issue?

**Comment by amrzaki2000** [comment]
> @amrzaki2000 Do want to work on this issue?

Okay

**Comment by sairish2001** [comment]
Deadline 2 April,2021 11:59PM IST

**Comment by shrey27tri01** [comment]
@amrzaki2000 Any updates? Anything you're stuck on?

**Comment by Ankita297** [comment]
Can  i work on this @sairish2001 @shrey27tri01 ?

**Comment by shrey27tri01** [comment]
@Ankita297 Sure, go ahead :)
Deadline 22 April 2021 11:59 PM IST
