### ISSUE TITLE
Remove Stress and Strain Calculator

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#1771]
I would like to add a calculator for finding the Fibonacci series in the general maths section.
Please assign this issue to me.

**Comment by khareyash05** [comment]
@RaveenaBhasin I had previously opened the same issue and it was closed due to irrelevance

**Comment by RaveenaBhasin** [comment]
@khareyash05 I don't think the topic is irrelevant since many participants have added calculators such as stress, strain calculators which are even off-topics but were still added so in this way this will be a completely relevant topic....Let's see what the mentors say.

**Comment by khareyash05** [comment]
Ya me too had the same thought

**Comment by sairish2001** [comment]
> @khareyash05 I don't think the topic is irrelevant since many participants have added calculators such as stress, strain calculators which are even off-topics but were still added so in this way this will be a completely relevant topic....Let's see what the mentors say.

I understand, this is my mistake, I would like you to remove the Stress and Strain Calculator, and no need of adding Fibonacci Series Calculator

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021

**Comment by RaveenaBhasin** [comment]
@sairish2001 Can I remove hydrostatic pressure calculator section because it does not come under mathematics?

**Comment by sairish2001** [comment]
> @sairish2001 Can I remove hydrostatic pressure calculator section also because it does not come under mathematics?

Yes
