### ISSUE TITLE
Make operation on sets responsive

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1782]
I would like to work on this issue as Gssoc'21 participant.

Screenshot:
![sets](https://user-images.githubusercontent.com/66208607/117253187-8f5afe80-ae64-11eb-9ea8-381cefb92e9b.png)

Please assign me this issue @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 May,2021
