### ISSUE TITLE
Make Sets relations and functions responsive

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1783]
I would like to work on this issue as Gssoc'21 participant.

Screenshot:
![sets2](https://user-images.githubusercontent.com/66208607/117253443-d943e480-ae64-11eb-90e1-c13f6b9d2647.png)

Please assign me this issue @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 May,2021
