### ISSUE TITLE
Wrong output in scalar triple product calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1784]
## **Describe the bug**

Wrong output in scalar triple product calculator

## **Screenshots**
![image](https://user-images.githubusercontent.com/67696867/117271900-4745d700-ae78-11eb-9c8f-143f5fe28ec1.png)
Ans should be 4

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by khareyash05** [comment]
@abhijeet141  Pls also add btn-dark class to the button

**Comment by abhijeet141** [comment]
> @abhijeet141 Pls also add btn-dark class to the button

Okay :)
