### ISSUE TITLE
Add feature to find the log value of x to the base y. 

### ISSUE THREAD

**Issue by nidhivanjare** [sairish2001/MakesMathEasy#179]
Adding a section to find the logarithmic base of the number in the general math section. 
 I would like to work on this issue @sairish2001 under GSSOC 2021.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 20 March,2021 (11:59 PM IST)

**Comment by nidhivanjare** [comment]
Sure, Thanks !!

**Comment by nidhivanjare** [comment]
There are some issues in this, I would like to resolve.
