### ISSUE TITLE
Make Tranformation of functions responsive

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1790]
I want to work on this issue as GSSOC'21 participant 

Screenshot:
![tfunc](https://user-images.githubusercontent.com/66208607/117278572-824b0900-ae7e-11eb-8bfc-3b1ae3ae4b12.png)

Please assign me this issue @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 May,2021
