### ISSUE TITLE
Caluculators not collapsing after searching

### ISSUE THREAD

**Issue by shubhdeep123** [sairish2001/makesmatheasy#1807]
## **Describe the bug**

- if we search a calculator while have a calculator on screen. It slides upon that calculator.

## **Screenshots**

![Screenshot from 2021-05-06 17-12-57](https://user-images.githubusercontent.com/64921946/117293283-d1009f00-ae8e-11eb-89b7-de9dcb8d9330.png)

**Comment by shubhdeep123** [comment]
@sairish2001 I would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 May,2021
