### ISSUE TITLE
Addition of Sidebar to contact section

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [sairish2001/makesmatheasy#1820]
The home button at the top is looking not so good so I would like to add sidebar to contact section that will contain:

Home , About , Settings , share to whatsapp and the contact icons with copyright at end.
This would make the contact page more user friendly.

Please assign me this issue @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 May,2021

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 May,2021
