### ISSUE TITLE
Bug in spi/cgpa calculator 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1844]
![image](https://user-images.githubusercontent.com/71064674/117337288-d1af2a80-aeba-11eb-94fa-b23dcf0338e2.png)

![image](https://user-images.githubusercontent.com/71064674/117337356-e4c1fa80-aeba-11eb-8e4c-6e4419bc5461.png)

**Comment by AB-san** [comment]
i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 May,2021
