### ISSUE TITLE
Add search bar recommendation

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1859]
1)improper to mixed fraction(under basic converters)
in graph and shapes
2)supplementary angle calculator
3)sss triangle's angle calculator
4)ceva's and thale's theorem
5)important graph calculators

i would like to add these in the search bar recommendation

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021

**Comment by sairish2001** [comment]
It's not the right way, you created 14 issues, which are similar.
Kindly make 2 PR's covering total of 14 issues. 
and each PR will be of Level 3
