### ISSUE TITLE
To add calculator to calculate Surface Area of Icosahedron

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1874]
## **Is your feature request related to a problem? Please describe.**

To add calculator to calculate Surface Area of Icosahedron

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by mehabhalodiya** [comment]
https://github.com/sairish2001/makesmatheasy/pull/1328

Check this!
Right now there is a small bug in this icosahedron calculator and I will solve this https://github.com/sairish2001/makesmatheasy/issues/1477

**Comment by mehabhalodiya** [comment]
Kindly requesting you to close this.
I will resolve that bug too as soon as possible.

**Comment by abhijeet141** [comment]
@mehabhalodiya So sorry i missed that one issue is already present on this you can take your time i am closing this issue :)

**Comment by abhijeet141** [comment]
@mehabhalodiya Are you still working on this ?

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya Are you still working on this ?

Yes, I am slow as my university exams are there. I will solve it possibly by today.

**Comment by mehabhalodiya** [comment]
Sorry for delay

**Comment by abhijeet141** [comment]
> > @mehabhalodiya Are you still working on this ?
> 
> Yes, I am slow as my university exams are there. I will solve it possibly by today.

Okay No Problem 🙂
