### ISSUE TITLE
Output is not displayed in Ellipsoid Calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1876]
## **Describe the bug**

Output is not displayed in Ellipsoid Calculator

## **Screenshots**
![image](https://user-images.githubusercontent.com/67696867/117381318-705a7c00-aef9-11eb-9cbe-c0b8322fadf5.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021

**Comment by abhijeet141** [comment]
@sairish2001 This issue is resolved now so i am closing this issue :)
