### ISSUE TITLE
To add Working steps of Area and Perimeter of Parallelogram

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1879]
## **Is your feature request related to a problem? Please describe.**

To add Working steps of Area and Perimeter of Parallelogram

![image](https://user-images.githubusercontent.com/67696867/117382795-e8767100-aefc-11eb-932a-d09292d0c0ac.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021
