### ISSUE TITLE
Bug in ARC Length Calculator not getting answer

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1887]
## **Describe the bug**

After giving input in Arc Length Calculator it is showing all values are required to obtain answer

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/117383749-1a88d280-aeff-11eb-88b5-951a88a50ecc.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021
