### ISSUE TITLE
bug in current hamming distance calculator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1888]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

![image](https://user-images.githubusercontent.com/71064674/117383879-60459b00-aeff-11eb-99eb-73f811788f44.png)

hamming distance can calculated between 2 inputs of equal length , but still its showing ans-4  which is wrong

- If applicable, add screenshots to help explain your problem.

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 May,2021
