### ISSUE TITLE
remove extra calculator 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1890]
![image](https://user-images.githubusercontent.com/71064674/117385432-bbc55800-af02-11eb-9cd5-239a105a6f4d.png)

remove tetrahedron calculator 
->
![image](https://user-images.githubusercontent.com/71064674/117388256-0e554300-af08-11eb-8957-28485418549f.png)

this is already present under tetrahedron

i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 May,2021
