### ISSUE TITLE
To add working steps of Circumcentre Calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1894]
## **Is your feature request related to a problem? Please describe.**

To add working steps of Circumcentre Calculator

![image](https://user-images.githubusercontent.com/67696867/117385911-95ec8300-af03-11eb-9946-06ba0bb538e7.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021
