### ISSUE TITLE
Add new cases in how to find p.i

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1899]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/71064674/117398146-592c8600-af1b-11eb-9d18-36ea25eec392.png)

1)Add 5th case when Q = x.V which is a special case of case 4
2) Add case of failure

i would like to work on this

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021

**Comment by AB-san** [comment]
@sairish2001  sorry i bymistakely clicked on unassign me
