### ISSUE TITLE
Design of the Favourite Panel

### ISSUE THREAD

**Issue by anu-cn** [sairish2001/MakesMathEasy#190]
We can add a button on the top for favourite list.
By clicking the button the list will be displayed otherwise it will remain hidden and if we select a topic in the list it will be highlighted. 
![image](https://user-images.githubusercontent.com/68462316/111205719-8b8dc700-85ed-11eb-8975-5e6bf2f1cc89.png)

**Comment by sairish2001** [comment]
Great Idea!
Feel free to ask your doubts, if any
Deadline 21 March,2021 (11:59 PM IST)
