### ISSUE TITLE
Bug in decimal/gray code generator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#1905]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![image](https://user-images.githubusercontent.com/71064674/117439171-22249780-af50-11eb-918d-1a82a01579a3.png)

it is converting the input from binary to decimal , its not converting the input from grey code to decimal

here the expected output was -> 15

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 May,2021
