### ISSUE TITLE
To enhance the UI of Scalar and Vector Triple Product calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1938]
## **Is your feature request related to a problem? Please describe.**

To enhance the UI of Scalar and Vector Triple Product calculator

![image](https://user-images.githubusercontent.com/67696867/117514203-f5ed3300-afb0-11eb-9412-9cfb2a96c358.png)

![image](https://user-images.githubusercontent.com/67696867/117514385-4f556200-afb1-11eb-8551-ad520f2ae270.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021
