### ISSUE TITLE
Lemniscate Calculator

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#1948]
I would like to add calculator for Lemniscate.
Please assign this to me.

Calculations with the lemniscate of Bernoulli:
Lemniscates are figure-eight shaped or shaped like the infinity-symbol ∞. The lemniscate of Bernoulli is defined by the formula (x²+y²)² - 2a² (x²-y²) = 0. The two parts of the shape are named drops. The surface area of one drop with height 'a' is similar to that of a square with edge length 'a'.

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021
