### ISSUE TITLE
To add searchbar recommendation for Percentile rank calculator , Euler Totient function and skewness calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#1968]
## **Describe the bug**

To add searchbar recommendation for Percentile rank calculator , Euler Totient function and skewness calculator

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021
