### ISSUE TITLE
Adding steps for angle b/w two lines

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1992]
**This calculator only displays the formula and prints the answer. The calculation part of m1, m2 are not here too. I would like to add steps by putting the input values in the formula. 
Please assign this to me.** 

![f3](https://user-images.githubusercontent.com/70858557/117536355-3af88000-b018-11eb-91fb-744e38e81b87.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021
