### ISSUE TITLE
Adding steps for Intersection point of two lines

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#1993]
**This calculator only displays the formula and prints the answer. I would like to add steps by putting the input values in the formula. 
Please assign this to me.** 

![f4](https://user-images.githubusercontent.com/70858557/117536359-3f249d80-b018-11eb-8bf7-1612cdd4d611.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021
