### ISSUE TITLE
Bug in formula used in spi/cgpa calculator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2014]
formula used
![image](https://user-images.githubusercontent.com/71064674/117543973-d3086080-b03c-11eb-9c09-7b6ff77914a9.png)

Actual formula-
![image](https://user-images.githubusercontent.com/71064674/117544280-58d8db80-b03e-11eb-8fe5-e1ea13e4efbf.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021
