### ISSUE TITLE
Covariance calculator

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#2019]
When single value is given as input for each, it displays the value as NaN. 
It should given proper message to the user to give more than one value as input. 
I would like to work on this issue please assign this to me. 

![b2](https://user-images.githubusercontent.com/70858557/117545261-9b9cb280-b042-11eb-974a-4af9fabb8d2c.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021
