### ISSUE TITLE
add inverse trigonometric identities

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/MakesMathEasy#202]
Hi! @sairish2001 I would like to add inverse trigonometric identities in trigonometry section

**Comment by shrey27tri01** [comment]
@khareyash05 You can go ahead with this issue :)
Deadline: March 19, 2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@shrey27tri01 @sairish2001 Created a PR have a look!

**Comment by khareyash05** [comment]
@sairish2001 i just wanted to request a thing.... Actually this required loads of work and I don't think it should be added to level 1 .. I may be wrong.. I am happy with merging but just a small suggestion to increase the level of the issue

**Comment by khareyash05** [comment]
Thank you @shrey27tri01
