### ISSUE TITLE
Enhance the UI of joint probability and empirical probability

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#2020]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- I would like to centralize the content and add different colors to differentiate heading sub heading and paragraph or tables.

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021
