### ISSUE TITLE
Search bar and home content is overlapping

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/MakesMathEasy#205]
## **Describe the bug**

-The search bar icon and the content of the home page overlaps on scrolling ( search bar does not get scrolled up with other items on the page). Also In the mobile view, the contents are overlapping.

## **Possible solution**

- The position of the search bar can be changed with some more changes to keep that search bar stable.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- ![mi5](https://user-images.githubusercontent.com/61223163/111339920-2940cf00-869e-11eb-80ac-e2f7aa19e8a8.PNG)
![mi6](https://user-images.githubusercontent.com/61223163/111339938-2e058300-869e-11eb-9525-be38cb579f4a.PNG)

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 21 March,2021 (11:59 PM IST)

**Comment by gnikita432** [comment]
Sure, Thank you.
