### ISSUE TITLE
Change layout of input fields in Singular matrix

### ISSUE THREAD

**Issue by AmrutaKoshe** [sairish2001/MakesMathEasy#206]
## **Is your feature request related to a problem? Please describe.**

- In the single matrix section, when the size of matrix is selected, the inputs fields are all lined up vertically, which appears a bit messy and the user has to scroll down a lot. 
- This is how it currently looks like:

![image](https://user-images.githubusercontent.com/59871941/111348307-14683980-86a6-11eb-820d-39a2f74fc9f6.png)

## **Describe the solution you'd like**

- To make it user friendly, all the input fields can be arranged in the shape of the matrix so that the user can easily visualise and select the numbers required.

**Comment by shrey27tri01** [comment]
@AmrutaKoshe you can go ahead with the issue :) 
Since this is a UI issue, please show us the screenshots of your changes while creating the PR.

Feel free to ask any doubts!
Deadline: 20 March, 2021, 11:59 PM IST

**Comment by sairish2001** [comment]
Deadline is near, Any Update? @AmrutaKoshe

**Comment by AmrutaKoshe** [comment]
> Deadline is near, Any Update? @AmrutaKoshe

yes I am working on it!
