### ISSUE TITLE
Changes in UI of Euclid Geometry

### ISSUE THREAD

**Issue by RoliGautam** [sairish2001/makesmatheasy#2063]
## **Is your feature request related to a problem? Please describe.**
- The UI page of Euclid geometry is not looking good.  All content is only one side of pages and font styling is also quite dissappointing.

## **Describe the solution you'd like**
- I would like to solve this problem and can make it more attractive and also align it in center, which make its UI good.

<img width="934" alt="mathseasy" src="https://user-images.githubusercontent.com/72242893/117567181-8c684400-b0d8-11eb-9173-33a7872f770c.png">

I can solve it, can you assign me please!

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021

**Comment by RoliGautam** [comment]
Hello @sairish2001 ..
Is this good??
or Should I use list ??
<img width="862" alt="Screenshot 2021-05-15 193930" src="https://user-images.githubusercontent.com/72242893/118364276-76b1bd80-b5b5-11eb-8a77-024b5483dbf3.png">

**Comment by sairish2001** [comment]
Use List and hide the bullets

**Comment by RoliGautam** [comment]
@sairish2001 Now I used list.. Please check it.. 

<img width="939" alt="Screenshot 2021-05-16 124932" src="https://user-images.githubusercontent.com/72242893/118389016-57fb0780-b645-11eb-84bb-38eee2ff675a.png">

**Comment by sairish2001** [comment]
Great, Go ahead with PR

**Comment by RoliGautam** [comment]
sure.. Thank you @sairish2001

**Comment by RoliGautam** [comment]
I make my pr but it shows conflicts.. What can I do?? @sairish2001

**Comment by sairish2001** [comment]
> I make my pr but it shows conflicts.. What can I do?? @sairish2001 

Nothing to do, I will resolve them by myself
