### ISSUE TITLE
Cut Rectangle Shape calculator 

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#2072]
I would like to add a shape calculator that calculates 
- Slant side, 
- perimeter and 
- area of Cut Rectangle

Given input
- Long rectangle side , 
- Short rectangle side, 
- Long cut side and 
- Short cut side.

Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021
