### ISSUE TITLE
Date Calculator

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/MakesMathEasy#209]
## Proposal

Date Calculator :- find the difference between date in different formats such as (years , months ,days) or (months,days) or (days)

**Comment by satyampgt4** [comment]
I would like to work on this issue @sairish2001 under gssoc 2021

**Comment by shrey27tri01** [comment]
@satyampgt4 You can go ahead with the issue :)

Feel free to ask any doubts!
Deadline 21st March, 2021, 11:59 PM IST
