### ISSUE TITLE
Add calculator for encoding in hamming code from right to lefft usign odd parity

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2096]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
I would like to work onn this issue

**Comment by sairish2001** [comment]
Glad to share Makes Math Easy, the web app which I started with the aim of providing Stepwise solutions to Various Math Problems are now being used in Africa by MathsGee for their programs across Africa.

**Comment by sairish2001** [comment]
Deadline 15 May,2021
