### ISSUE TITLE
Bug in work and time calculator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2113]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117592936-160b2680-b158-11eb-8c9a-33175e8e9a05.png)

bug - also taking negative values 

i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 May,2021
