### ISSUE TITLE
Bug in solve for exponent n 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2114]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117593063-7a2dea80-b158-11eb-8660-8d0c2081dc01.png)

calculate button isnt working

i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 May,2021

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 May,2021

**Comment by AB-san** [comment]
@sairish2001  the calculate is working fine now 
but found a another bug in this calculator ->
![image](https://user-images.githubusercontent.com/71064674/118055039-fa489000-b3a4-11eb-8603-79d9886b328b.png)

1) bug in latex 
2) invalid output - NaN
