### ISSUE TITLE
Minor Bug in sum of square calculator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2115]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117594282-68017b80-b15b-11eb-97be-883a827cc52d.png)

2 must be on exponent(power)

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 May,2021
