### ISSUE TITLE
Add working step for effective interest rate calculator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2130]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/71064674/117633005-3e684480-b19b-11eb-8ff6-9dd0e34db612.png)
i would like to ad working steps under it

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 May,2021
