### ISSUE TITLE
Bug in pythogorean calculator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2133]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117634393-7d4aca00-b19c-11eb-9442-b03cd30831b9.png)

A pythagorean triple is defined only for positive integers. Negative numbers can't be sides of a right triangle, therefore, aren't used in Pythagorean triples

i wud like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 May,2021
