### ISSUE TITLE
enhance Ui of  scaler triple product 

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#2134]
## Proposal

**the ui of vector scaler triple product  seem odd** 
(A clear and concise description of what the proposal is.)

![image](https://user-images.githubusercontent.com/59261812/117633880-13cabb80-b19c-11eb-994c-b59e96f0ac19.png)

### **i will enhance ui to make it even with other calculators**

i like to work on it under gssoc21

**Comment by satyampgt4** [comment]
i like to work on it

**Comment by abhijeet141** [comment]
@satyampgt4 This issue is already present #1938 please close this issue
