### ISSUE TITLE
enhance ui of vector triple product

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#2135]
## Proposal

**the ui of vector  triple product  seem odd** 
(A clear and concise description of what the proposal is.)

![image](https://user-images.githubusercontent.com/59261812/117634595-aff4c280-b19c-11eb-8b1a-5df017f8aba8.png)

### **i will enhance ui to make it even with other calculators**

i like to work on it under gssoc21

**Comment by satyampgt4** [comment]
i like to work on it

**Comment by abhijeet141** [comment]
@satyampgt4  This issue is already present #1938 please close this issue
