### ISSUE TITLE
Bug in Check leap year 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2137]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117635577-9011ce80-b19d-11eb-9ebd-0d7b0bfdd1c8.png)

Negative numbers must not be accepted for inputs 
i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 May,2021
