### ISSUE TITLE
Add working steps for hydrostatic pressure calculator

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2139]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/71064674/117635901-ebdc5780-b19d-11eb-866a-571344a77228.png)
i wud like to add working steps below it

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021
