### ISSUE TITLE
To add working steps in perpendicular line checker

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#2143]
## **Is your feature request related to a problem? Please describe.**

To add working steps in perpendicular line checker

**Comment by madihamallick** [comment]
@abhijeet141 This part already has steps, it was not visible due to bugs, which is now resolved. Please check this #2406

**Comment by abhijeet141** [comment]
> @abhijeet141 This part already has steps, it was not visible due to bugs, which is now resolved. Please check this #2406

Okay
