### ISSUE TITLE
Add area calculator for general triangle

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#215]
## **Is your feature request related to a problem? Please describe.**

- I want to add a new option of general triangle in shape triangle in "calculator for shapes" under Graphs and Shapes section

## **Describe the solution you'd like**

- If a user doesn't know which type of triangle they have , then can calculate area by choosing general triangle option.

I am a GSSOC participant ,please assign this issue to me.

**Comment by shrey27tri01** [comment]
You can go ahead with the issue :)

**Comment by shrey27tri01** [comment]
@ShrutiOmer What's the update on this issue? Anything you're stuck on?

**Comment by ShrutiOmer** [comment]
Actually there was already a scalene triangle calculator in that section.

**Comment by shrey27tri01** [comment]
Oh, ok! I'm closing this issue, then!
