### ISSUE TITLE
Bug in co-ordinate geometry calculators(Valid error message) -1

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2151]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117642345-cc94f880-b1a4-11eb-897f-c217a56ecd6b.png)

![image](https://user-images.githubusercontent.com/71064674/117642375-d585ca00-b1a4-11eb-81f1-41550e43be5a.png)

![image](https://user-images.githubusercontent.com/71064674/117642425-df0f3200-b1a4-11eb-9fe2-6806a692544e.png)

![image](https://user-images.githubusercontent.com/71064674/117642446-e9313080-b1a4-11eb-91bc-6b9589e0fa6c.png)

I would like to add a valdi error message

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021
