### ISSUE TITLE
Bug in co-ordinate geometry calculators (valid error message) -2

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2152]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117643514-1d592100-b1a6-11eb-8e5d-57f4acf1acf5.png)

![image](https://user-images.githubusercontent.com/71064674/117643557-2b0ea680-b1a6-11eb-8a10-36ba192e1fb6.png)

![image](https://user-images.githubusercontent.com/71064674/117643593-32ce4b00-b1a6-11eb-954f-5b6fadc80dd4.png)

![image](https://user-images.githubusercontent.com/71064674/117643670-437ec100-b1a6-11eb-8395-464312d84343.png)

![image](https://user-images.githubusercontent.com/71064674/117643691-4a0d3880-b1a6-11eb-9b46-364d02fd5c16.png)

@sairish2001  i wont  touch other bugs as already issues are made for that , i will just add valid error message instead of NaN

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021
