### ISSUE TITLE
bug in standard deviation calculator

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#2155]
## **Describe the bug**

the standard deviation button is linking to home i want to delete that

**Comment by shrishti-c** [comment]
![Screenshot (329)](https://user-images.githubusercontent.com/73748606/117661595-294fdd80-b1bc-11eb-987d-e4b1ebc7609d.png)
Hey @khareyash05 , could you please try that once again by updating your repo cuz it's working fine.
(Just saying cuz that was added by me.)
