### ISSUE TITLE
Add styling to button ( onMouse zoom effect)

### ISSUE THREAD

**Issue by Raj142** [sairish2001/MakesMathEasy#216]
Please assign it me . i am a participant of GSSoC'21

**Comment by Raj142** [comment]
![privios](https://user-images.githubusercontent.com/52609526/111421473-0dc3db80-8713-11eb-9259-62e7dfed21b9.png)
it looks like this .!
![new](https://user-images.githubusercontent.com/52609526/111421517-246a3280-8713-11eb-9a02-367ad973de65.png)
ONMouse Zoom effect

**Comment by sairish2001** [comment]
it's not looking good

**Comment by ambivert-sam** [comment]
@Raj142  can I enhance this? Will you please assign it to me

**Comment by shrey27tri01** [comment]
Since this change is not needed as of now, I am closing this issue.
However, feel free to open or work on other issues :)
