### ISSUE TITLE
enhance the UI of Inverse, Perodicity of function

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#2169]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
![image](https://user-images.githubusercontent.com/61223163/117691406-7ee6b300-b1d9-11eb-950e-ac3ae37f5d50.png)

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021
