### ISSUE TITLE
Enhance the UI of Power series

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#2170]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- 
![image](https://user-images.githubusercontent.com/61223163/117692031-3380d480-b1da-11eb-845e-8f328dc21766.png)

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021
