### ISSUE TITLE
Enhance the UI of Hyperbolic trignometric identities

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#2173]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- 
![image](https://user-images.githubusercontent.com/61223163/117692727-eea96d80-b1da-11eb-9122-32faae1d794b.png)
![image](https://user-images.githubusercontent.com/61223163/117692850-0da7ff80-b1db-11eb-8c93-276703dd61d2.png)

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021
