### ISSUE TITLE
add binary to bcd code converter

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2192]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud liek to add this

![image](https://user-images.githubusercontent.com/71064674/117704538-937e7780-b1e8-11eb-8108-c1f305f588b2.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021
