### ISSUE TITLE
Find Factors

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [sairish2001/makesmatheasy#223]
## **Enhancing Algebraic functioning by adding factors option**

- Adding a feature to find out all the factors of a given number. for example : 12 : 1,2,3,4,6,12 (excluding extremities is as per the admin wish, but I think it should be included)

## **Solution**

Adding the functionality form scratch :
- HTML and CSS enhancement for this functionality 
- Some JavaScript coding required

**Comment by keshavgbpecdelhi** [comment]
I want to work on this @sairish2001

**Comment by sairish2001** [comment]
Go ahead!
Feel free to ask your doubts, if any
Deadline 22 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
There's a option of Calculating LCM/HCF/Prime Factors under general maths category

Do implement your code for factors in this option

**Comment by keshavgbpecdelhi** [comment]
Ok sure, thanks for telling @sairish2001.

**Comment by keshavgbpecdelhi** [comment]
This is the path - Home > General Maths > LCM/HCF/Factors 
This is the html part - 

             <li>
                <table class="table">
                    <tr>
                        <td style="border-top: none;">
                            <a id="factorsoption"
                               style="font-size:0.9375rem;cursor: pointer;background:transparent;border:none;">LCM/HCF/Factors</a>
                        </td>
                        <td style="float:right;border-top: none;">
                                <span onclick="addtofavourite('LCM/HCF /Factors','#factors','c','facimgfav')"><img
                                        id="facimgfav" src="images/unfavourite.png"
                                        style="height:1.5625rem;filter: none;"></span>
                        </td>
                    </tr>
                </table>
            </li>


I am not getting were should I do the changes ( I am not able to find the place )

Btw here is the thing which is needed for factors ( I know u also know this but still..)

Taking user input (n)
Lopping from 1 to n :
 dividing each term and collecting those nums which are giving zero when modulo(%) with input num
outputting them separating with commas like x, y, z,...a


I want to know where should I do the changes i am not able to figure out where should I found it (index.js !) exact location.

**Comment by khareyash05** [comment]
@keshavgbpecdelhi index.js is in appjs folder

**Comment by khareyash05** [comment]
@keshavgbpecdelhi look at other's PR's and see where they made changes to implement a functionality and then implement the same in your branch
I learned the same way!!

**Comment by Ankita297** [comment]
Can i work on this ? @sairish2001

**Comment by keshavgbpecdelhi** [comment]
I had done this ig🤷‍♂️
