### ISSUE TITLE
Bug in Calculator code

### ISSUE THREAD

**Issue by Karthik-Nayak98** [sairish2001/MakesMathEasy#224]
## **Describe the bug**

- When we insert the operators many times still it calculates the correct value. 
- 
## **Possible solution**

- There should some error value like  **Syntax error**.

## **Screenshots**
![calculator](https://user-images.githubusercontent.com/39642646/111456595-3365da80-873d-11eb-8a55-81d6342ca808.png)

**Comment by Karthik-Nayak98** [comment]
I would like to work on this issue as a part of GSSoC'21

**Comment by sairish2001** [comment]
But if it's working well, then we should not show such messages

**Comment by Karthik-Nayak98** [comment]
But a real calculator would show an error message. This is not the right math

**Comment by shrey27tri01** [comment]
@Karthik-Nayak98 Many calculators work differently, and ours is no exception, so we can't go ahead with this issue right now. Hope you understand!
But thanks for opening this issue! I am closing this as of now :)
