### ISSUE TITLE
Cross Multiplication Calculator

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#2264]
## **Is your feature request related to a problem? Please describe.**

- A cross multiplication calculator calculates the unknown value of one variable equation of form a/b=c/d.

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/75009990/117812892-0129b280-b280-11eb-912d-e4da0c11c46e.png)

Please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
