### ISSUE TITLE
Enhance the UI of De Moivers theorem

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#2272]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- 
![image](https://user-images.githubusercontent.com/61223163/117820934-ac3e6a00-b288-11eb-9c90-fecd7b57fa78.png)
I would like to work on this issue

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
