### ISSUE TITLE
Two answer displays in Slope calculator

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#2286]
**When the slope of line becomes infinity. Then both 0 and infinity is displayed as answer.
I would like to fix this. Please assign this to me.** 

![b2](https://user-images.githubusercontent.com/70858557/117830083-ef9cd680-b290-11eb-89a7-fe51a8cc4afb.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
