### ISSUE TITLE
Bug in Improper to mixed fraction

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#2289]
**When the denominator becomes zero. Then NaN value shows. It should either not calculate not infinity values, or display some proper msg to the user. 
I would like to fix this. Please assign this to me.** 

![b1](https://user-images.githubusercontent.com/70858557/117830563-620db680-b291-11eb-9149-2d270555e5ef.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
