### ISSUE TITLE
Want to add more in about section and more efficient in design.

### ISSUE THREAD

**Issue by aashi2912** [sairish2001/MakesMathEasy#230]
## **Is your feature request related to a problem? Please describe.**

- About section is all empty. Only contains one line. Want to add more in about section related to website. What is represents and the features, use, developed by and other information.

## **Describe the solution you'd like**

- About section of any website should be precise and clear descriptive which is not so i want to make it more concise by adding content and also it's style(UI) design good.
- 
**GSSOC21**
If you would like to please assign this to me :)
@shrey27tri01 @Nidhirajput1301 @apekshamanchanda

**Comment by shrey27tri01** [comment]
@aashi2912 You can go ahead with the issue :)
Please show us the changes you did through screenshots or any other medium, while creating the PR.
Deadline: 22 March, 2021 11:59 PM IST

**Comment by aashi2912** [comment]
Sure. Thanks!

**Comment by aashi2912** [comment]
hey, @shrey27tri01 . I just forked the project and it's about section is not working. Something is not right. It is not displaying anything. The content which is already there. **App developed by**  thing and also if I am doing something my content is ready but it is not gonna show. Please look into this matter so I can work on my issue. Whenever you click on about section nothing happens.
