### ISSUE TITLE
In matrix calculator if a negative value is entered for dimension a warning should be shown

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#232]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- In matrix calculator if a negative value is entered for the dimension there is no warning and when we click solve then the error is not explanatory.

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
When the negative value is entered at that time only a warning like "Please enter positive values only should be displayed"
![Screenshot (85)](https://user-images.githubusercontent.com/66053534/111510089-6f1b9700-8773-11eb-940d-31f714d46fb5.png)

**Comment by shrey27tri01** [comment]
You can go ahead with the issue :)
Deadline: March 21 2021, 11:59 PM IST
