### ISSUE TITLE
Bug in Perpendicular line checker not displaying Answer

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#2323]
## **Describe the bug**

Bug in Perpendicular line checker not displaying Answer

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/117909030-20aff200-b2f7-11eb-90d3-a10d0041ec74.png)

**Comment by abhijeet141** [comment]
**Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018**

**Comment by madihamallick** [comment]
@abhijeet141 this issue is now resolved under this PR #2406
