### ISSUE TITLE
Adding Name of Project and logo on home screen

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/MakesMathEasy#235]
## **Is your feature request related to a problem? Please describe.**

-when someone opens the home page there is nothing written on it like the project name, logo and user has no idea in which way this project can help him/her

## **Describe the solution you'd like**

-I would like to add the name of the project along with its logo on top so that the user can get to know the aim of this project

**Comment by shrey27tri01** [comment]
@RaveenaBhasin We already have this issue addressed [here](https://github.com/sairish2001/MakesMathEasy/issues/13), which is being worked upon. However, feel free to work on other issues!
