### ISSUE TITLE
add working steps for leap year 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2358]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/71064674/117971618-c3905c80-b347-11eb-91b6-9dca0e42c42b.png)

such working steps will be displayed

**Comment by madihamallick** [comment]
@AB-san this issue exists, #1756

**Comment by AB-san** [comment]
> @AB-san this issue exists, #1756

Oh! I am really sorry @madihamallick
