### ISSUE TITLE
Add area of ellipse under conic section 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2380]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/71064674/117991546-c7c67500-b35b-11eb-996b-00d9ada2c62a.png)

area of ellipse is already available but i would like to the formula and calculator in this section so that all the formulaes will be at one place

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
