### ISSUE TITLE
add perimeter of ellipse under conic section

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2381]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/71064674/117991819-06f4c600-b35c-11eb-80b8-0e06f23ed0da.png)
perimeter of ellipse is already there in shapes calculator but i will  again it in conic section , as i think all the formula at one place will look good

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
