### ISSUE TITLE
[GSSOC'21] Mic is overlapping with the search icon.

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/MakesMathEasy#239]
## **Describe the bug**

mic overlaps with a search icon.

## **Possible solution**

I'll align the mic to the correct place.

## **Screenshots**

![mathEasy](https://user-images.githubusercontent.com/57946528/111627138-c58ce200-8814-11eb-8119-1198c8f03245.png)

**Comment by sairish2001** [comment]
Go Ahead
Feel free to ask your doubts, if any
Deadline 23 March,2021 (11:59 PM IST)

**Comment by shonali2600** [comment]
@sairish2001 sir, I've made the changes and made the pull request with the screenshots attached. Kindly review my work.
