### ISSUE TITLE
[GSSOC'21] Improving the Home page UI

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/MakesMathEasy#240]
## **Is your feature request related to a problem? Please describe.**

The home page looks dull

## **Describe the solution you'd like**

Will make it more appealing.

**Comment by shrey27tri01** [comment]
@shonali2600 We already have this issue addressed [here](https://github.com/sairish2001/MakesMathEasy/issues/13), which is being worked upon. However, feel free to work on other issues!
