### ISSUE TITLE
[GSSOC'21] Adding styling to the important facts.

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/MakesMathEasy#241]
## **Is your feature request related to a problem? Please describe.**

The styling of facts showing on the home page is not looking good.

## **Describe the solution you'd like**

I'll add some CSS like border, background, and shadows to make it beautiful.

**Comment by shrey27tri01** [comment]
You can go ahead with this :)
Kindly provide screenshots showing the changes you did while creating the PR.

Deadline: March 22, 2021 11:59 PM IST

**Comment by ambivert-sam** [comment]
@shonali2600 I would like to work on this issue

**Comment by shonali2600** [comment]
@shrey27tri01 , I've made a pull request, kindly review it.

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue , I have experience in css and js , please assign me this issue
