### ISSUE TITLE
Adding a github action which will automatically add "GSSoC'21" label to the issue.

### ISSUE THREAD

**Issue by Karthik-Nayak98** [sairish2001/MakesMathEasy#242]
## Proposal

Adding labels to the issues are extra work for the maintainer, so we can add GitHub actions to reduce the work of maintainers.

**Comment by Karthik-Nayak98** [comment]
I would like to work on this issue as a part of GSSoC'21

**Comment by sairish2001** [comment]
Label Should be

GSSOC21

There should not be any symbol in between.

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 March,2021 (11:59 PM IST)
