### ISSUE TITLE
Add a feature to do operations on fractions

### ISSUE THREAD

**Issue by nidhivanjare** [sairish2001/MakesMathEasy#243]
## **Is your feature request related to a problem? Please describe.**

- I would like to add a feature to do arithmetic operation on fractions 

## **Describe the solution you'd like**

- addition of fractions 
- multiplication of fractions 
- division of fractions 
- subtraction of fractions 
- conversion of a mixed fraction to an improper fraction 
- conversion of an improper fraction to mixed fraction 
- reducing a fraction to the simplest form 

I am a GSSOC'21 participant and would like to work on this issue.

**Comment by sairish2001** [comment]
Can you provide step by step solution to it?

**Comment by nidhivanjare** [comment]
Yes 
I will display a step-by-step solution to all the operations.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 24 March,2021 (11:59 PM IST)
