### ISSUE TITLE
Surface area of Icosahedron

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#2434]
**I would like to add the surface area of icosahedron here. Please assign this to me.** 

![bb](https://user-images.githubusercontent.com/70858557/118088189-51ba2080-b3e4-11eb-977d-caf5f6f84428.PNG)

**Comment by abhijeet141** [comment]
This issue is already open pleas check #1874

**Comment by mehabhalodiya** [comment]
@madihamallick Kindy check this #1477  
I am slow as my university exams are there.
I will possibly solve it by today.
Sorry for delay!
Hope you will understand :)

**Comment by madihamallick** [comment]
@mehabhalodiya Okay Okay! no problem.
