### ISSUE TITLE
Add GitHub icon

### ISSUE THREAD

**Issue by Shubhrima** [sairish2001/makesmatheasy#2439]
## **Is your feature request related to a problem? Please describe.**
Add a GitHub icon, beside LinkedIn and Discord icon

- The website has no direct link to its GitHub repository.

## **Describe the solution you'd like**
The icon will help users to directly head over to the repository.

![image](https://user-images.githubusercontent.com/68013183/118125826-1d128d00-b415-11eb-8e54-e33757982957.png)

**Comment by supriyagahoi** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : supriya gahoi
Discord Tag: #2460

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
