### ISSUE TITLE
Change the style of input boxes in light mode for all the sections

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#2447]
## Proposal

(A clear and concise description of what the proposal is.)
Change the style of input boxes in light mode for all the sections to improve visibility.
![image](https://user-images.githubusercontent.com/61223163/118152975-fbc09980-b432-11eb-9bb6-09805f3465ec.png)
I would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
