### ISSUE TITLE
Bug in Multiplication table for decimal value.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#246]
## **Describe the bug**

- A clear and concise description of what the bug is.
In Multiplication table if a decimal value is entered in the number field it prints the table for the floor of that number. But it should print the table for that decimal number only.
## **Possible solution**
We can use parseFloat instead of parseInt for the number in printtable function.

## **Screenshots**

![Screenshot (90)](https://user-images.githubusercontent.com/66053534/111659543-570b4c80-8833-11eb-9501-1aea5c7dfa9c.png)

#GsSOC'21
Please assign this to me.

**Comment by sairish2001** [comment]
Go Ahead
Deadline 22 March,2021 (11:59 PM IST)

**Comment by kanishka8276** [comment]
@sairish2001 Floating point arithmetic is not exact that's why I am getting this type of output.  
![Screenshot (92)](https://user-images.githubusercontent.com/66053534/111665286-9daf7580-8838-11eb-883e-afe2911b9328.png)
![Screenshot (93)](https://user-images.githubusercontent.com/66053534/111665304-a142fc80-8838-11eb-9730-b34a0160a9d3.png)

**Comment by sairish2001** [comment]
```
var num = 5.56789;
num = num.toFixed(2);
```

you can use `.toFixed()` to set precision point

**Comment by kanishka8276** [comment]
Ok👍🏻
