### ISSUE TITLE
Bug in mean median mode calculator

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#247]
## **Describe the bug**

- A clear and concise description of what the bug is.
If all same numbers are entered in mean mode median calculator in mode it shows "All number appeared just once".
![Screenshot (91)](https://user-images.githubusercontent.com/66053534/111661880-71dec080-8835-11eb-8fd6-ccd60fc1b3a5.png)

#GsSOC'21 
Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts, if any

Deadline 24 March,2021 (11:59 PM IST)
