### ISSUE TITLE
Changing the hover icon of instagram

### ISSUE THREAD

**Issue by supriyagahoi** [sairish2001/makesmatheasy#2495]
## Proposal

Want to change the icon of instagram which apper on hover . That colour full icon is not proper  it is crop insta log.

![Screenshot (37)](https://user-images.githubusercontent.com/67188791/118257951-e0a26800-b4cc-11eb-8428-5fba5fcd639b.png)

**Comment by supriyagahoi** [comment]
Assign me this proposal

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
