### ISSUE TITLE
expansion of trigonometric functions 

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/MakesMathEasy#253]
I would like to add expansion of functions of sine,cosine,sine-inverse and other related trigonometric functions in Trigonometry section

**Comment by shrey27tri01** [comment]
You can go ahead with the issue :)
Just to be clear, by "expansion", you meant Taylor Series expansion, right?

**Comment by khareyash05** [comment]
Right

**Comment by khareyash05** [comment]
@shrey27tri01 Basically maclaurin expansion putting x=0 in taylor expansion

**Comment by khareyash05** [comment]
@sairish2001 Attached a PR Have a look
