### ISSUE TITLE
To add valid input message when no input is displayed in squares and cubes calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#2540]
## **Describe the bug**

To add valid input message when no input is displayed in squares and cubes calculator

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 May,2021
