### ISSUE TITLE
Bug in square and cubes of a given number

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#2541]
## **Describe the bug**

Bug in square and cubes of a given number most calculators buttons are not working

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
