### ISSUE TITLE
To enhance the UI of CAUCHY INTEGRAL,LIOUVILLE AND ROUCHE THEOREM

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#2564]
## Proposal

(A clear and concise description of what the proposal is.)
I would like to enhance the UI of CAUCHY INTEGRAL,LIOUVILLE AND ROUCHE THEOREM

**Comment by sairish2001** [comment]
Go ahead
Deadline 25 May,2021
