### ISSUE TITLE
Adding Data Calculator

### ISSUE THREAD

**Issue by surbhi594** [sairish2001/makesmatheasy#257]
for ex : Converting MB into KB

**Comment by surbhi594** [comment]
Please assign it to me as I'm participant of GSSOC'21.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 25 March,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
just a suggestion instead of adding new calculator add this in unit converter

**Comment by sairish2001** [comment]
> just a suggestion instead of adding new calculator add this in unit converter

Yes, add this in unit converter

**Comment by sairish2001** [comment]
Deadline extended 27 March,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
can i work on it
