### ISSUE TITLE
All calculators of coordinate geometry not working

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#2653]
## **Describe the bug**

All calculators of coordinate geometry not working

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by madihamallick** [comment]
@abhijeet141 I have fixed all bugs in this PR already
here #2650

**Comment by abhijeet141** [comment]
> @abhijeet141 I have fixed all bugs in this PR already
> here #2650

Okay then i will close my PR

**Comment by abhijeet141** [comment]
@sairish2001 As PR for this bug is already there i am closing this issue and PR🙂
