### ISSUE TITLE
Adding all information of conic sections

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/MakesMathEasy#267]
I would like to add all the important information about conic sections(parabola, ellipse, hyperbola) . 
As I'm a beginner this issue may take some time. So I would request you to kindly give me 5-6 days for completing the PR.
Please assign this issue to me.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 26 March,2021 (11:59 PM IST)
