### ISSUE TITLE
Cardioid Shape Calculator

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#2677]
cardioid is a heart-shaped curve
I would like to add a calculator that calculates the diameter, perimeter and area of Cardioid given radius
please assign this to me

**Comment by RaveenaBhasin** [comment]
I have already created issue for the same #2367.

**Comment by madihamallick** [comment]
> I have already created issue for the same #2367.

Sorry I didn't notice the issue
