### ISSUE TITLE
profit loss with profit and loss percentage

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/MakesMathEasy#269]
We can add profit and loss percentage on mentioning cost price and the selling price
Kindly assign this to me I will work on this issue as soon as i complete previously assigned issues
I will complete this by 24th

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts, if any
Deadline 25 March,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@sairish2001 Added a profit loss calculator Have look!
