### ISSUE TITLE
add sum of n-terms in geometric  progression

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/MakesMathEasy#270]
i would like to add sum of  n-terms in a G.P. 
Kindly assign this to me I will work on this issue as soon as i complete previously assigned issues
I will complete this by 26th

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 26 March,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@sairish2001 SHould i add the same to Arithmetic progression or should i create new?

**Comment by khareyash05** [comment]
@sairish2001 I am having a small doubt pls help me with that 
`var ans1 = a * (Math.pow(r,n)-1)` 
When using this and returning value of ans1 the value coming out is NaN pls help me out

**Comment by khareyash05** [comment]
@sairish2001 Created a PR Have a look!

**Comment by khareyash05** [comment]
Hi @sairish2001 is my PR ready to merge?
