### ISSUE TITLE
Adding 4d shape calculator section

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#2760]
I would like to add a new section for calculating surface area, volume, hypervolume of 4d shapes. Firstly, I want to add tesseract shape.
Please assign this issue to me.

**Comment by mehabhalodiya** [comment]
@RaveenaBhasin No need to create separate issue for adding 4D section.
I will create it while I will make first PR either for tesseract or hypersphere calculator.
#1947 #1946
