### ISSUE TITLE
diffrent color of fav icon

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/MakesMathEasy#278]
## **Describe the bug**

- the color of calculation in complex number  is blue/black
- while rest are of red / white

## **Possible solution**

- 

## **Screenshots**

![Capture](https://user-images.githubusercontent.com/59261812/111828696-afb11700-8911-11eb-892a-83ce26d4ca35.JPG)

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts, if any
Deadline 23 March,2021 (11:59 PM IST)
