### ISSUE TITLE
Bug in P/B/H trigo calculator

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#280]
## **Describe the bug**

- A clear and concise description of what the bug is.
If all 3 parameters (base, height and hypotenuse) are entered together which don't follow Pythagoras theorem then too it shows the values of trigonometric ratio instead of the warning such right angle triangle is not possible.
## **Possible solution**

- Describe the solution you thought of.
We should consider the condition that only 2 parameters are entered or all 3 follow Pythagoras theorem.

![Screenshot (106)](https://user-images.githubusercontent.com/66053534/111833684-86e05000-8918-11eb-95b3-46bed7cd68b6.png)

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 25 March,2021 (11:59 PM IST)
