### ISSUE TITLE
List of Algebraic Formulas

### ISSUE THREAD

**Issue by Maitryee-Choudhary** [sairish2001/MakesMathEasy#281]
## Proposal

Adding list of algebraic formulas. 
For eg: (a^2-b^2)=(a+b)(a-b)
            (a+b)^2=(a^2+b^2+2ab)
            (a-b)^2=(a^2+b^2-2ab) and so on..
I will be adding nearly 15-20 such algebraic formulas.

hey @sairish2001 please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Feel Free to ask your doubts, if any
Deadline 25 March,2021 (11:59 PM IST)
