### ISSUE TITLE
Gsoc'21 Bug in Changing Modes

### ISSUE THREAD

**Issue by arpit456jain** [sairish2001/MakesMathEasy#285]
## **Describe the bug**

When the website is loaded for first time there is light mode by-default , no problem its ok but when i changed it to dark mode the home page is looking like this
<img width="960" alt="prob1" src="https://user-images.githubusercontent.com/55352601/111867109-fcd7cc00-8997-11eb-81bb-bc939416d419.png">
 

## **Possible solution**

It should look like this 
<img width="960" alt="prob2" src="https://user-images.githubusercontent.com/55352601/111867125-0b25e800-8998-11eb-8e16-1e9df495907c.png">

I know its a small bug but still its a bug , I am a gsoc'21 participant ,so please assign it to me I will fix it as soon as possible.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 23 March,2021 (11:59 PM IST)
