### ISSUE TITLE
Adding all Differentiation Formula

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/MakesMathEasy#287]
I would like to add all the formula used in differentiation. I know in the project we can write the function and find the differentiation but if the user wants to see all the formulas related to differentiation there is no provision for that . So I would like to resolve this issue.
Please assign this to me

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 26 March,2021 (11:59 PM IST)

**Comment by RaveenaBhasin** [comment]
I have made the PR Differentiation Formulae Added #311  kindly review it
