### ISSUE TITLE
Adding integration formula 

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/MakesMathEasy#292]
I would like to add all the formula used in integration. I know in the project we can write the function and find the integration but if the user wants to see all the formulas related to integration there is no provision for that . So I would like to resolve this issue.
Can you please assign this to me.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 26 March,2021 (11:59 PM IST)

**Comment by bitaashna** [comment]
i have created a PR #297 
 @sairish2001 Please review it
