### ISSUE TITLE
Search bar closes while typing

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/MakesMathEasy#293]
## **Describe the bug**
Search bar remains open only when we hover on it, while typing it closes automatically if we won't hover on it

## **Screenshots**
with hover
![image](https://user-images.githubusercontent.com/60106112/111879999-e6009c00-89ce-11eb-93a7-afbbf6477df5.png)

without hover
![image](https://user-images.githubusercontent.com/60106112/111879995-e0a35180-89ce-11eb-8343-d731d4e00075.png)

**Comment by Abhisheka394** [comment]
Can I work on this, I'm a GSSOC21 participant.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 25 March,2021 (11:59 PM IST)
