### ISSUE TITLE
To add working steps in Area of largest semicircle that can be drawn inside a square

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#2979]
## **Is your feature request related to a problem? Please describe.**

To add working steps in Area of largest semicircle that can be drawn inside a square

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by khareyash05** [comment]
@abhijeet141 #2784 Kindly close the issue

**Comment by abhijeet141** [comment]
@khareyash05 Sorry i missed that

**Comment by abhijeet141** [comment]
@khareyash05 If you found any other issue of mine repeated please let me know 🙂
