### ISSUE TITLE
Inverse Trignometric identities disappear after a second.

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/MakesMathEasy#298]
on clicking on inverse trignometric formulae, it appears for a second and then disappears.
I would like to fix this bug.
Can you please assign it to me.
![Screenshot from 2021-03-21 12-23-19](https://user-images.githubusercontent.com/57864526/111896547-7dea9e00-8a40-11eb-8bfd-4bc31fef0475.png)

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 26 March,2021 (11:59 PM IST)

**Comment by bitaashna** [comment]
I have created a PR #321. Please check it!
