### ISSUE TITLE
Adding Definite integration formulae

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/MakesMathEasy#299]
Adding the following:-

-  king's rule
- integration by part
- shifting 
- periodicity
- Walli's theorem
- Labnitz Theorem

Can you please assign it to me.I would like to work on it!

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 26 March,2021 (11:59 PM IST)

**Comment by bitaashna** [comment]
@sairish2001 I have created a PR #323 .Please check it!

**Comment by khareyash05** [comment]
@bitaashna @sairish2001 I am not able to add formulae as the way they are and  get distorted . Could you pls guide me on how to mention formulae as they are . Pls provide me with some documentation or a video maybe .Thanx

**Comment by bitaashna** [comment]
@khareyash05 We have to use katex library.
You can go through the following link [https://katex.org/docs/support_table.html](url)
I hope,it might help you.
