### ISSUE TITLE
Improve code of Minors and Co-factors in Matrix Operations

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy#3]
Write a code from scratch to solve Minors and Co-factors of a Matrix, 
design a logic in the way, so that we can easily show steps of what we are doing.

Note!
No barrier of Time and Space Complexity. Feel free to write/design a code.

[Check out the previous code](https://github.com/sairish2001/makesmatheasy.github.io/blob/52f55fde909a8b4cc13f2d9ec7eb7a4831c90907/appjs/matrixlogic.js#L509)

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by sayna3311** [comment]
I would love to work on this issue. Please, assign this to me?

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by sairish2001** [comment]
Deadline 13 March,2021

**Comment by sairish2001** [comment]
@sayna3311 Any Update?

**Comment by sairish2001** [comment]
Deadline is near @sayna3311 Any update?

**Comment by Upasana1216** [comment]
I would like to contribute to this. Please assign this to me

**Comment by Upasana1216** [comment]
Okay sir

**Comment by anjali7786** [comment]
Hi, I would like to work on this issue under GSSOC'21. Kindly assign me this

**Comment by Upasana1216** [comment]
Sir, I have designed the code for finding the minor matrix and cofactor matrix. Do I need to calculate the final minor and cofactor too?

**Comment by sairish2001** [comment]
can you please Share some screenshots

**Comment by Upasana1216** [comment]
[minro.docx](https://github.com/sairish2001/MakesMathEasy/files/6181894/minro.docx)
Sir, this is code should I send the ss of the output too?

**Comment by sairish2001** [comment]
yes,send screenshot

**Comment by Upasana1216** [comment]
![2021-03-22 (1)](https://user-images.githubusercontent.com/52318225/112036979-41fe2880-8b67-11eb-9b73-37643c28e8b9.png)
[minro.docx](https://github.com/sairish2001/MakesMathEasy/files/6184377/minro.docx)

**Comment by Upasana1216** [comment]
Sir, Do I need to improve more?

**Comment by sairish2001** [comment]
Implement it, and also show steps for the same

**Comment by Upasana1216** [comment]
okay sir

**Comment by Upasana1216** [comment]
Sir explained code:
[minro.docx](https://github.com/sairish2001/makesmatheasy/files/6230167/minro.docx)

**Comment by Upasana1216** [comment]
/*
	Question: Find the minor and cofactor matrix of each element of a matrix
	Steps to find the minor matrix of each element:
		1.	Loop through each element of a matrix
		2.	Check if the element belongs to the same column and row of which we are finding the minor matrix
			If true
				Insert 0 at the position in minor matri
			Else
				Insert the element of matrix in the minor matrix
	
	Steps to find the cofactor matrix of each element:
	1.	Loop through each element of a matrix
	2.	Check if the element belongs to the same column and row of which we are finding the minor matrix
		If true
			Insert 0 at the position in minor matri
		Else
			Insert the (-1)(i+j) *element into the minor matrix

	Example:
	Matrix: 1  2  3
		   	4  5  6
		   	7  8  9
		   	
	Minor Matrix for element at position (0,0) i.e., 1:
	Insert zero if matrix element if of same row and column as of the given element else insert the element

		0	0  0
		0	5  6
		0	8  9
	Cofactor Matrix for element at position (0,0) i.e., 1:
	Insert zero if matrix element is of same row and column as of the given element else insert the (-1)(i+j) *element
	0   0   0
	0   5  -6
	0  -8  9

*/
	


//Program

#include<bits/stdc++.h>
#include<iostream>
using namespace std;

int n; //n -> size of array
int matrix[100][100]; //matrix of which we will find Minor and Cofactor
int minor[100][100];  // matrix to store minor of above matrix
int cofactor[100][100]; //matrix to store cofactor of above matrix

//Minor matrix of any element of a matrix is in  which we take all the elements of a matrix expect the elements present in that row and column
void get_Minor(int x,int y,int matrix[][100], int minor[][100]){
	
	// Looping for each element of the matrix 
	for(int i=0;i<n;i++){
		for(int j=0;j<n;j++){
			// if ith row and jth column if not the column and row in which that element is present that store that element
			//else store 0 at that position
			if(i!=x&&j!=y){
			
				minor[i][j]=matrix[i][j];
				
			}
			else
				minor[i][j]=0;
			
			
		}
	
	}
}
void print_minor(int minor[][100]){
	// Looping for each element of the matrix 
	for(int i=0;i<n;i++){
		for(int j=0;j<n;j++)
		{
			//if the element is 0 than don't print it as it is the same row and column to which our element belongs
			//else print that element
			if(minor[i][j]!=0)
				cout<<minor[i][j]<<" ";
		}
		cout<<endl;
		
	}
	//cout<<endl;
}
void getCofactor(int matrix[][100], int cofactor[][100], int p, int q) 
{ 
    int i = 0, j = 0; 
  
    // Looping for each element of the matrix 
    for (int row = 0; row < n; row++) 
    { 
        for (int col = 0; col < n; col++) 
        { 
            //  Copying into temporary matrix only those element 
            //  which are not in given row and column 
            //else insert 0
            if (row != p && col != q) 
            { 
                cofactor[i][j++] = pow(-1,col+row)*matrix[row][col]; 
  
                // Row is filled, so increase row index and 
                // reset col index 
                if (j == n - 1) 
                { 
                    j = 0; 
                    i++; 
                } 
            } 
            else
            	cofactor[col][row]=0;
        } 
    } 
    // print the cofactor of given element
    for(int i=0;i<n;i++){
    	for(int j=0;j<n;j++){
			if(cofactor[i][j]!=0)
    			cout<<cofactor[i][j]<<" ";
    	}
    	cout<<endl;
	}
} 
int main(){
	
	cout<<"Enter size of Matrix"<<endl;
	cin>>n;
	cout<<"Enter the Matrix Elements"<<endl;
	for(int i=0;i<n;i++){
		for(int j=0;j<n;j++){
			cin>>matrix[i][j];
			
		}
	
	}

	for(int i=0;i<n;i++){
		for(int j=0;j<n;j++){
			get_Minor(i,j,matrix,minor); //function to find minor of each element of a matrix
			
			cout<<"Minor matrix of "<<matrix[i][j]<<"at position "<<i<<" "<<j<<endl;
			print_minor(minor);  //function to print the minor of each element of a matrix
			
			cout<<endl<<"Cofactor matrix of "<<matrix[i][j]<<"at position "<<i<<" "<<j<<endl;
			getCofactor(matrix,cofactor,i,j); // function to find and print cofactor of each element of a matrix
			cout<<endl;
			
		}
	}
	return 0;
}

**Comment by sairish2001** [comment]
This is in C++, are you able to convert it into JavaScript?

**Comment by Upasana1216** [comment]
Yes sir

**Comment by sairish2001** [comment]
@Upasana1216 you are taking too long. Kindly tell me how many days you need, more?

**Comment by Upasana1216** [comment]
Sir due to health issues I won't be able to work for few weeks. So, may I

**Comment by Upasana1216** [comment]
Sir due to health issues I won't be able to work for few weeks.

**Comment by shonali2600** [comment]
@sairish2001 sir, I would like to work on this issue, please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
