### ISSUE TITLE
Some Operators are not visible on the calculator

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/MakesMathEasy#300]
## **Describe the bug**

- A clear and concise description of what the bug is.
-Some Operators are not visible on the calculator 

## **Possible solution**

- Describe the solution you thought of.
- I will make the operators visible on the calculator 

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- 
![mathissue4](https://user-images.githubusercontent.com/61223163/111897091-e5eeb380-8a43-11eb-8fff-bb161428f33a.PNG)

**Comment by sairish2001** [comment]
The operators are there, but their font size is so small

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 26 March,2021 (11:59 PM IST)

**Comment by gnikita432** [comment]
sure, Thank you
