### ISSUE TITLE
Add sum of Nth term of Geometric Progression under General Maths

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/MakesMathEasy#302]
## **Is your feature request related to a problem? Please describe.**

There is a calculator to find sum of nth term of a AP but no such for GP.I want to add that.

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
issue is already opened for the same

**Comment by sairish2001** [comment]
[#270](https://github.com/sairish2001/MakesMathEasy/issues/270)
