### ISSUE TITLE
add steps to aliquot sum calculator

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#3023]
## **Is your feature request related to a problem? Please describe.**

- I want to add steps in this cal please assign me this issue

**Comment by khareyash05** [comment]
@ShrutiOmer I had opened the issue before #3000 Issue So I request to kidly close the issue

**Comment by ShrutiOmer** [comment]
@khareyash05 I have opened the PR and actually worked on it, if you also worked please tell then I will close. Otherwise let me to go ahead with this issue.

**Comment by khareyash05** [comment]
Actually I have not..... So you may go ahead with the same

**Comment by ShrutiOmer** [comment]
@khareyash05  Thankyou very much for this.
