### ISSUE TITLE
Adding scroll bar 

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#303]
## **Is your feature request related to a problem? Please describe.**
There is no scroll bar in the index page. Due to which we have to use arrow keys to scroll the page.
We should add scroll bar to the page.

**Comment by Alenjojo** [comment]
Can you assign me with this issue. Without the scroll bar it is becoming a bit confusing for the users when they go down. I'll make an good scroll bar and limit the scrolling too.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 26 March,2021 (11:59 PM IST)

**Comment by kanishka8276** [comment]
@sairish2001 I am working on this issue but I am facing some problems,  If I delete the code of hidescroll then it shows 2 vertical scroll bars.
I tried many other methods like using overflow properties but in that case the scroll bar is not even visible.

**Comment by kanishka8276** [comment]
@shrey27tri01 @sairish2001 I am working on this issue but I am facing some problems,  If I delete the code of hidescroll then it shows 2 vertical scroll bars.
I tried many other methods like using overflow properties but in that case the scroll bar is not even visible. I have tried all the alternatives Which I know but couldn't solve the issue . I request you to please assign this issue to someone else.

**Comment by sairish2001** [comment]
Appreciated, you informed us earlier.

**Comment by satyampgt4** [comment]
i would like to work on please assign it to me

**Comment by sairish2001** [comment]
Go ahead!
Feel free to ask your doubts, if any
Deadline 26 March, 2021 (11:59 PM IST)
