### ISSUE TITLE
Problem in code of formulas of limits

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#304]
## **Describe the bug**
P tags are visible in the formulas in the output.
![Screenshot (108)](https://user-images.githubusercontent.com/66053534/111898491-60bbcc80-8a4c-11eb-89c1-4f2e3f8bb4a4.png)

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 23 March,2021 (11:59 PM IST)
