### ISSUE TITLE
Copyright section should not hover and should be more bold

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/MakesMathEasy#306]
## **Is your feature request related to a problem? Please describe.**

Copyright section is looking like a button.

## **Describe the solution you'd like**

- Copyright section should not hover.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 23 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
Don't increase the font size of copyright text

**Comment by abhijeet141** [comment]
Okk Sir, Thank You

**Comment by khareyash05** [comment]
@abhijeet141 if u can do - also when copyright is clicked it looks as if in the menu
Pls try to remove that also

**Comment by sairish2001** [comment]
@khareyash05 Yes!
Nice to see, you have the spirit of Open Source.

**Comment by khareyash05** [comment]
@sairish2001 Thanx

**Comment by abhijeet141** [comment]
> @abhijeet141 just a suggestion - when copyright is clicked it looks as if in the menu
> Pls try to remove that also
> I think @sairish2001 will agree with me on that point.

Thanks for the suggestion 😊
Can you please check is it right?
![image](https://user-images.githubusercontent.com/67696867/111909324-d80c5300-8a82-11eb-8e45-ce12fe1ed3ca.png)

**Comment by abhijeet141** [comment]
I have removed that hover
