### ISSUE TITLE
Kindly Read!

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy#3076]
## Certificate of OpenSource Contribution

All GSSOC'21 Participants who Contributed to Makes Math Easy, with atleast 1 PR merged.

Kindly fill the form, sent in the GSSOC makesmatheasy Discord Channel **before 10 June,2021**

**Comment by sairish2001** [comment]
@asimaries
@Sapna2001
@Itashi19
@Krishan-2000
@LalitMishra1504
@Muskan-creator
@nitinjaiswal7537
@nitinshukla413
@Pranjal-Jayaswal
@Raj142
@SurbhiRathi23
@wajeehamushtaq
@akshay399
@archijaiswal
@geniusbharti
@surbhi594

**Comment by SarthakKeshari** [comment]
@sairish2001, I don't have a link to discord server. How may I fill the form?

**Comment by sairish2001** [comment]
Participants who Contributed to Makes Math Easy Project with atleast 1 PR merged

Kindly Fill this form to receive Certificate of Contribution

https://forms.gle/3SPcsNMzhwS9k81F8
