### ISSUE TITLE
The arrows in the <Input type='number'> does not have a proper CSS

### ISSUE THREAD

**Issue by Alenjojo** [sairish2001/makesmatheasy#310]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by Raj142** [comment]
Please assign me. i want to work on it

**Comment by sairish2001** [comment]
@Alenjojo can you please elaborate this issue?

**Comment by Alenjojo** [comment]
Sorry, i think it was a typo error.
Is your feature request related to a problem? Please describe.

    When we select the <Input type='number'> to enter the number an arrow will be shown to increase or decrease it.So the arrow doesn't match the current UI experience

Describe the solution you'd like

    My solution is to hide the current arrows and add a custom arrows with additional CSS and JS.
And BTW i raised the issue first, so can you pls assign it to me

**Comment by sairish2001** [comment]
@Alenjojo
In open-source, creating an issue and asking for assignment is two different things

You just created an issue, which indicates there is a bug, or some enhancement requires. This doesn't mean you want to work on this issue.

If you want to work on issue you have to ask for an assignment.

**Comment by Alenjojo** [comment]
I did ask for that, but somehow the details got reset as you can see above

**Comment by Alenjojo** [comment]
@sairish2001 Hey its been nearly a week, if there is any further updates can you assign me this issue.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)

**Comment by Alenjojo** [comment]
Thanks, before that if i need to work on this issue I'll be needing the calculator which apparently isn't working. As you can look up to issue #613 , the calculator isn't responding to the click response. So i can only proceed this issue only after#613 have been solved.

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)

**Comment by Alenjojo** [comment]
Let me suggest something, is there a need of the arrows inside the input field type. Even thou if i add custom buttons its gonna look crowded. Anyway users will have to type in the values and the input field does look pretty with the button. 
As you can see from the image below

![Capture](https://user-images.githubusercontent.com/51394913/113096835-95314480-9213-11eb-8c11-ea2d4d67390b.PNG)

 So the solution is to remove the arrows from every test field.
![Capture](https://user-images.githubusercontent.com/51394913/113097067-f527eb00-9213-11eb-978a-4de041604762.PNG)

**Comment by sairish2001** [comment]
remove them, it looks nice
