### ISSUE TITLE
Adding Volume,CSA,TSA of 3d Solids

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/MakesMathEasy#324]
In general maths section,I would like to add the formula for volume,CSA,TSA of flollowing solids :-

1. cube
2. cuboid
3. sphere
4. cone
5. hollow sphere
6. hemisphere
7. cylinder
8. hollow cylinder
9. prism
10. pyramid
11. frustum of cone

Can you please assign it to me.I would like to work on it.

**Comment by bitaashna** [comment]
@sairish2001  I would like to work on it. Can you please assign it to me!

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts,if any
Deadline 27 March,2021 (11:59 PM IST)

**Comment by bitaashna** [comment]
@sairish2001 I have created a PR #353 .Please check it.
