### ISSUE TITLE
To add working steps in central angle of N-sided Regular polygon

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#3243]
## **Is your feature request related to a problem? Please describe.**

To add working steps in central angle of N-sided Regular polygon

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by madihamallick** [comment]
#3173 This is already there
