### ISSUE TITLE
Adding conditional identities in trigonometry section

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/MakesMathEasy#325]
I would like to add conditional identities which is valid when sum of three  angles is pie in the trigonometry section.
Can you please assign it to me.

**Comment by bitaashna** [comment]
@sairish2001 i would like to work on this issue Can you please assign it to me.

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts,if any
Deadline 27 March,2021 (11:59 PM IST)

**Comment by bitaashna** [comment]
@sairish2001 I have created a PR #350 .Please check it!
