### ISSUE TITLE
To allign inputs in matrix and also in some other section in center 

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#327]
## **Is your feature request related to a problem? Please describe.**

-Like when i click on matrix solver the inputs of matrix is allign in left.

## **Describe the solution you'd like**

-I will allign the matrix input in center and also i will allign in some other section. 
![image](https://user-images.githubusercontent.com/67696867/111921374-3ef92e80-8aba-11eb-81e3-3a03795f8f1e.png)
![image](https://user-images.githubusercontent.com/67696867/111921389-4a4c5a00-8aba-11eb-922d-7389d7aae1fd.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts,if any
Deadline 27 March,2021 (11:59 PM IST)

**Comment by abhijeet141** [comment]
By mistake i have deleted my files i will code it again and send you PR
