### ISSUE TITLE
The website link in share to whatsapp is not yet updated

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/MakesMathEasy#328]
## **Is your feature request related to a problem? Please describe.**

- In share to whatsapp the link of website is old one and is not updated.

## **Describe the solution you'd like**

- The link should be updated in share to whatsapp so that anyone can share the link and it should be opened.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts, if any
Deadline 24 March,2021 (11:59 PM IST)

**Comment by abhijeet141** [comment]
Sure Sir 🙂
