### ISSUE TITLE
To add more properties in section Properties of matrices and determinant

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/MakesMathEasy#329]
## **Describe the solution you'd like**

- I would like to add more properties of matrices and determinant.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts,if any
Deadline 27 March,2021 (11:59 PM IST)
