### ISSUE TITLE
Adding trignometric angle values for particular angles

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/MakesMathEasy#330]
I would like values of specific angle like 18 degree, 36degree...and many more which are used very frequently and one should remember those value.
Please assign this issue to me.

**Comment by RaveenaBhasin** [comment]
@sairish2001 Can I work on this issue?

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts,if any
Deadline 27 March,2021 (11:59 PM IST)

**Comment by RaveenaBhasin** [comment]
@sairish2001 I have created the PR. Kindly review it.
