### ISSUE TITLE
Add Arithmetic Progression upto n terms

### ISSUE THREAD

**Issue by nidhi-08** [sairish2001/MakesMathEasy#334]
I would like to add arithmetic progression under general maths. This will take in the initial term (a), difference (d) and number of terms (n) and print the whole list. 
Please assign this to me as a part of GSSOC'21.

**Comment by sairish2001** [comment]
You can implement this under Linear Algebra section

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts,if any
Deadline 27 March,2021 (11:59 PM IST)

**Comment by nidhi-08** [comment]
So I should just print the series before the sum of arithmetic progression is being printed right?

**Comment by sairish2001** [comment]
Yes, Right 👍
