### ISSUE TITLE
Unwanted "Currency Converter" Found.

### ISSUE THREAD

**Issue by Raj142** [sairish2001/MakesMathEasy#336]
There are two options for currency converter in which one is in Basic Converter Section and another one is in Binary Converter.
One is working properly and another is not.

Please assign this to me as a part of GSSoC'21.

**Comment by Raj142** [comment]
![1](https://user-images.githubusercontent.com/52609526/111970841-bf06af00-8b21-11eb-96f3-394c03d623f0.PNG)
![2](https://user-images.githubusercontent.com/52609526/111970853-c1690900-8b21-11eb-9f28-441935d1b310.PNG)

**Comment by sairish2001** [comment]
Your codebase is not updated! This issue is already fixed.
