### ISSUE TITLE
duplicate algebraic identities page

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/MakesMathEasy#338]
There are duplicate algebraic identities one in linear algebra section and one in equations one
I would like to delete any one on your choice I personally think it should be removed from linear algebra section

**Comment by RaveenaBhasin** [comment]
@khareyash05 It's my suggestion that if you are deleting the identities from the linear algebra section just copy the 11th identity along with its condition and paste it in the equation section because I feel that's an important identity that should be remembered.

**Comment by khareyash05** [comment]
Sure @RaveenaBhasin Thanx

**Comment by sairish2001** [comment]
> @khareyash05 It's my suggestion that if you are deleting the identities from the linear algebra section just copy the 11th identity along with its condition and paste it in the equation section because I feel that's an important identity that should be remembered.

Open Source is for helping community, Great to see you have the spirit of Open Source

**Comment by khareyash05** [comment]
@sairish2001 Can i start working on this issue?

**Comment by RaveenaBhasin** [comment]
@sairish2001 Thanks

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts
Deadline 27 March,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@sairish2001 Created a PR Have a look!

**Comment by khareyash05** [comment]
@sairish2001 Created a PR Have a look!
