### ISSUE TITLE
Add basic information and formula list for various shapes for younger audience

### ISSUE THREAD

**Issue by aanchalrakheja** [sairish2001/MakesMathEasy#343]
i would like to add a column dedicated to providing basic info about shapes and some related formula which could be helpful for younger audience.

**Comment by shrey27tri01** [comment]
Can you please elaborate on what all information and formulae you are planning to add? That would be helpful in going ahead with the issue :)

**Comment by aanchalrakheja** [comment]
The idea is to include an image with an image of the shape along with basic information about it like maybe for a triangle- I am a three shape, things that are triangle shaped and so. The basic aim is to focus on the younger age group and just act as a medium of making them familiar with the shapes.

**Comment by sairish2001** [comment]
Actually, most of the formulas for shapes is already there under Shapes Calculator
