### ISSUE TITLE
Bug in date calculator

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#346]
## **Describe the bug**
If a date before the date in from column is entered in to column it shows wrong difference.
## **Possible solution**

- Describe the solution you thought of.
It should show the right difference between the days no matter whether the date is of past or future.

![Screenshot (120)](https://user-images.githubusercontent.com/66053534/112006822-1587e380-8b4a-11eb-9a34-ce7134710f23.png)

![Screenshot (121)](https://user-images.githubusercontent.com/66053534/112006904-2cc6d100-8b4a-11eb-8380-2dccc72f3c73.png)

**Comment by shrey27tri01** [comment]
Please go ahead with the issue :)
