### ISSUE TITLE
Add Geometric Progression upto n terms

### ISSUE THREAD

**Issue by nidhi-08** [sairish2001/makesmatheasy#349]
I would like to add geometric progression series under the Linear Algebra section in the Sum of Geometric progression. This will take in the initial term (a), ratio (r) and the number of terms (n) and print the whole series. 
This will print the list before printing the sum. 

Please assign this to me as a part of GSSOC'21.

**Comment by shrey27tri01** [comment]
You can go ahead with the issue :)
Deadline 28th March, 11:59 PM IST

**Comment by nidhi-08** [comment]
Hi, I was trying to solve this when I realized there have been some errors and the AP/GP part is not displaying at all after I pulled the code. Can you please look into the matter?

**Comment by shrey27tri01** [comment]
@nidhi-08 We're looking into the matter right now, and will let you know once it gets resolved.
