### ISSUE TITLE
Update the ReadMe file 

### ISSUE THREAD

**Issue by asimaries** [sairish2001/makesmatheasy#351]
I can make a better readme file that will be easy to understand for the new beginner Opens source Contributors.
As It's difficult for the new contributor to understand Git and Github
I will make a proper stepwise Contribution Guide (for git and GitHub) for this Repo.
The old guide is very big and complex, I want to make it smaller, cleaner, and stepwise which will be easy to use

Please assign this issue to me, I would Like to work on it

**Comment by shrey27tri01** [comment]
You can go ahead with the issue, but please first show us the changes you suggest to be made before creating a PR. 
Deadline 29th March, 11:59 PM IST

**Comment by asimaries** [comment]
![image](https://user-images.githubusercontent.com/75176367/112347230-b1515500-8cec-11eb-8757-da8c9a9c2d98.png)


> You can go ahead with the issue, but please first show us the changes you suggest to be made before creating a PR.
> Deadline 29th March, 11:59 PM IST

check this https://github.com/asimaries/Awesome-JavaScript-Projects.github.io/blob/main/README.md 
I will take reference from this repo

**Comment by sairish2001** [comment]
Great!
Go ahead

**Comment by asimaries** [comment]
> Great!
> Go ahead

I have complete the work should I remove the old readme content from here 
![image](https://user-images.githubusercontent.com/75176367/112377508-da351280-8d0b-11eb-961f-670e92d1893b.png) or where should I add that

**Comment by sairish2001** [comment]
Remove it
