### ISSUE TITLE
Find entered year is leap year or not

### ISSUE THREAD

**Issue by Upasana1216** [sairish2001/makesmatheasy#352]
When a user enters any year then it will tell whether it is a leap year or not.

Using the formula to calculate leap year at the backend we can design a page where user enters any year and he gets the result as if the year entered is a leap year or not.

**Comment by shrey27tri01** [comment]
You can go ahead with the issue :)
Deadline 27th March 11:59 PM IST

**Comment by sairish2001** [comment]
Kindly do show steps for the same

**Comment by rk05-lenavo** [comment]
I am a GSSoC'21 participant @sairish2001 
Can you assign me this issue

**Comment by khareyash05** [comment]
@sairish2001 can i work on this ?

**Comment by shrey27tri01** [comment]
@Upasana1216 What are the updates on this issue? Anything you're stuck on?

**Comment by Upasana1216** [comment]
Sir, I have designed the page which tells whether the entered year is a leap year or not but I'm not getting how to show the steps

**Comment by sairish2001** [comment]
just concatenate the string with appropriate message. and at last just show the string into div tag using DOM i.e. innerHTML=<name of variable>

**Comment by Ayushgup85** [comment]
is this issue still open?if open can i work on this issue?

**Comment by sairish2001** [comment]
@Upasana1216 any update?
I think you are facing trouble with showing steps. No problem make PR without Steps

**Comment by satyampgt4** [comment]
is this issue still open?if open can i work on this issue?

**Comment by khareyash05** [comment]
Hey can i work on this issue?

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 April,2021 11:59 PM IST
