### ISSUE TITLE
Adding Statistics Formulae

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/MakesMathEasy#354]
In general maths section,I would like to add a section for statistics formulae which will include:-

- mean
- weighted mean
- Combined mean
- median
- mode
- Range
- coefficient of range
- mean deviation about mean
- mean deviation about median
- mean deviation about mode
- mean deviation about any number 'a'
- Standard Deviation
- combined standard deviation
- variance
- coefficient of variation

**Comment by bitaashna** [comment]
@sairish2001 i would like to work on it.
Can you please assign it to me

**Comment by shrey27tri01** [comment]
You can go ahead with this issue :)

**Comment by bitaashna** [comment]
@sairish2001 I have created a PR #410 Please check it.
