### ISSUE TITLE
Adding Equation of Director Circle for parabola, Ellipse, Hyperbola

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/MakesMathEasy#355]
In the respective sections of Parabola,Hyperbola and Ellipse,I would like to add Equation of their respective director circles

**Comment by bitaashna** [comment]
@sairish2001 I would like to work on it.
Please assign it to me.

**Comment by shrey27tri01** [comment]
You can go ahead with the issue :)
Deadline 27th March 11:59 PM IST

**Comment by bitaashna** [comment]
@sairish2001 I have created a PR #401 Please check it!
