### ISSUE TITLE
remove unnecessary text

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/MakesMathEasy#364]
## **Describe the bug**

unnecessary text

```
<<<<<<< HEAD=======>>>>>>> 2a361fd1b78219385ebf356d98fd63716e645970
```

## **Possible solution**

REMOVE IT

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Web capture_23-3-2021_134449_sairish2001 github io](https://user-images.githubusercontent.com/59261812/112114647-4e719800-8bde-11eb-805b-c594c2b16286.jpeg)
![Web capture_23-3-2021_134332_sairish2001 github io](https://user-images.githubusercontent.com/59261812/112114659-50d3f200-8bde-11eb-991e-4ac5986205cc.jpeg)

**Comment by Alenjojo** [comment]
Can you assign me with this issue, I'd like to work on it

**Comment by satyampgt4** [comment]
issue already exist #360
