### ISSUE TITLE
Bug in round off calculator

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#379]
## **Describe the bug**
Round off calculator does not work for decimal numbers and thus rounding off to ones place is not working.
![Screenshot (136)](https://user-images.githubusercontent.com/66053534/112149813-64468380-8c05-11eb-91f8-a863976a3b08.png)
![Screenshot (137)](https://user-images.githubusercontent.com/66053534/112149821-66a8dd80-8c05-11eb-8b52-5ca2201cb90e.png)

**Comment by sairish2001** [comment]
Can you please elaborate this issue?

**Comment by sairish2001** [comment]
You will fix the steps of roundoff?

**Comment by kanishka8276** [comment]
@sairish2001  if we enter decimal number like 7.5 and ask it to round off it is printing 7.5 only.

**Comment by kanishka8276** [comment]
> You will fix the steps of roundoff?

Yes, I will try to do it!
