### ISSUE TITLE
Adding conditions of specific inverse trigonometric functions

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/MakesMathEasy#383]
I would like to add graph and condition of inverse trigo functions 
example-sin^(-1)(2x/1+x^2) Like there are 3 conditions under which it is used and there are many more functions I would like to add.
Please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 28 March,2021 (11:59 PM IST)
