### ISSUE TITLE
UI of complex number calculation

### ISSUE THREAD

**Issue by satcasm** [sairish2001/makesmatheasy#386]
Would like to improve upon the UI of complex number calculation.(The result should contain some more text, will add that and make the input fields a bit spacious)

Also, it would be nice to shift ```calculation for 1 complex number``` into a separate page. It would make the page look clean.
Would like to work on it under GSSOC '21.

**Comment by sairish2001** [comment]
Go ahead!
Deadline 29 March,2021 (11:59 PM IST)

**Comment by satcasm** [comment]
Closing the issue as PR is merged.

**Comment by satcasm** [comment]
Closing the issue as PR is merged.
