### ISSUE TITLE
Bug in "Sum of N terms of GP calculator" when r=1

### ISSUE THREAD

**Issue by AB-san** [sairish2001/MakesMathEasy#388]
## **Describe the bug**

In sum of n terms of GP calculator When common ratio ==1 the sum comes out to 0
## **Possible solution**
Modify the javascript code for when r==1 || The formula of GP sum when r==1 is ( no. of terms * 1st term)

## **Screenshots**
![image](https://user-images.githubusercontent.com/71064674/112188331-ea27f600-8c28-11eb-84d6-c5bd5c971983.png)

**Comment by AB-san** [comment]
Please assign me this issue i will start working on it as soon as i m assigned to it !!

**Comment by sairish2001** [comment]
Go ahead
Deadline 28 March,2021 (11:59 PM IST)
