### ISSUE TITLE
state rules for divergence and convergence of series

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/MakesMathEasy#390]
Hi! I would like to add rules and tests like Raabe's test D'ALembert Test which test convergence and divergence of series

**Comment by sairish2001** [comment]
This is a calculator or just formulas?

**Comment by sairish2001** [comment]
Go ahead!
Feel free to ask your doubts, if any

**Comment by khareyash05** [comment]
@sairish2001 Attached a PR Have a look!
