### ISSUE TITLE
Bug in median calculator.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#397]
## **Describe the bug**
If odd number of space separated numbers are entered then it shows wrong median.

Please assign this to me.

![Screenshot (142)](https://user-images.githubusercontent.com/66053534/112207380-0b92dd00-8c3d-11eb-849c-1084db64598f.png)
![Screenshot (143)](https://user-images.githubusercontent.com/66053534/112207387-0cc40a00-8c3d-11eb-9d5e-938e9e4ff585.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 27 March,2021 (11:59 PM IST)
