### ISSUE TITLE
Output of Ascending/descending order calculator

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#399]
## **Is your feature request related to a problem? Please describe.**
If a user enters a different set Of numbers and finds ascending and descending order and then enter another set of numbers and finds only the ascending order then the descending order of the previous set of numbers is still displayed which can create confusion when dealing with large amount of data.

## **Describe the solution you'd like**
Instead we should use common output Field for both ascending and descending so that it only displays what the user wants to know not the past data

Please assign this to me.

![Screenshot (145)](https://user-images.githubusercontent.com/66053534/112208398-53663400-8c3e-11eb-90c4-87a59dbda7e4.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 28 March, 2021 (11:59 PM IST)
