### ISSUE TITLE
Create Inverse of Matrix Calculator

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy#4]
Design a code/logic to calculate Inverse of Matrix
Your can use either of any methods:
- Inverse of a Matrix using Elementary Row Operations (Gauss-Jordan)
- Inverse of a Matrix using Minors, Cofactors and Adjugate

Keep in mind!
Design a code in the way, so that we can easily show steps for what we are doing.

**Comment by sachinh19** [comment]
I would like to give this a go if you don't mind. I am relatively new to contribution in open source so I won't mind if you decide to do this yourself either.

**Comment by sairish2001** [comment]
should I assign this issue to you?

**Comment by sachinh19** [comment]
Yes

**Comment by sairish2001** [comment]
Thanks for showing interest, your every contribution is valuable. Feel free to ask your doubts if any.

**Comment by sachinh19** [comment]
Thanks. I will look into the codebase some more and come up with questions before I start working on the solution.

Do you have any contributing, branch naming or commit guidelines?

**Comment by sairish2001** [comment]
You can make a PR directly into **main branch** .

Kindly Read:
**[README.md](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/README.md)**
**[CONTRIBUTING.md](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)**

**Comment by sachinh19** [comment]
I might take a few days to get this done, do you have any deadline for this? Asking this because I won't be able to deliver this urgently.

**Comment by sairish2001** [comment]
Sure, I will give you next 3 days more.
Have you understood the codebase or may I help?

**Comment by sachinh19** [comment]
I will try my best to get done in three days but there is a good chance I won't be able to finish it this week as I am busy in my day job.

**Comment by sairish2001** [comment]
Take your time, I will not remove assignment, until someone else wants to work on it.

**Comment by sairish2001** [comment]
Can you please tell are you a GSSOC'21 participant?
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by sachinh19** [comment]
I am not.

**Comment by SravanKumarBattu** [comment]
Can i have this issue to solve ?

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by sairish2001** [comment]
Deadline 13 March,2021(11:59 PM IST)

**Comment by sairish2001** [comment]
@SravanKumarBattu Any Update?

**Comment by mrunalvilas** [comment]
hello!
 I am a GSSoC'21 participant, can I work on this issue.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 21 March,2021 (11:59 PM IST)

**Comment by likhitha-19** [comment]
am a GSSoC'21 participant , can i work on this issue

**Comment by sairish2001** [comment]
@mrunalvilas any update?

**Comment by anjali7786** [comment]
Hi, I would like to work on this issue under GSSOC'21. Kindly assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead!
Feel free to ask your doubts, if any
Deadline 28 March,2021 (11:59 PM IST)

**Comment by anjali7786** [comment]
Hii sir, please tell me whether I need to show the inverse of the matrix or steps too?

**Comment by Nishayadav-bit** [comment]
Hey @sairish2001 , I would like to work on this issue under Gssoc'21 participant , Please assign to me .

**Comment by anjali7786** [comment]
Hi sir, I am working on the issue but I want more time to complete it.Kindly extend the deadline.

**Comment by anjali7786** [comment]
@sairish2001, please tell me whether I need to show the steps of finding the inverse also?

**Comment by sairish2001** [comment]
Yes , you have to show steps

**Comment by sairish2001** [comment]
Deadline extended 5 April,2021

**Comment by anjali7786** [comment]
![Page1](https://user-images.githubusercontent.com/57794837/113658327-78868800-96bd-11eb-9f22-5eb4374a57b0.PNG)
![pag32](https://user-images.githubusercontent.com/57794837/113658337-7d4b3c00-96bd-11eb-9587-a40f0f031e06.PNG)
![page3](https://user-images.githubusercontent.com/57794837/113658398-99e77400-96bd-11eb-8056-2314894d6b27.PNG)


@sairish2001 please review the implementation.

**Comment by anjali7786** [comment]
Sir, please tell me that how should I add the case when the inverse doesn't exist i.e |A|=0.

**Comment by sairish2001** [comment]
Everything is fine, just use 
`.toFixed(3)` to set the precision of float number

**Comment by sairish2001** [comment]
> Sir, please tell me that how should I add the case when the inverse doesn't exist i.e |A|=0.

You can run the determinant code before it's execution, make a check using if else

**Comment by anjali7786** [comment]
Does that mean I need to write the code for determinant also or somehow I can use it from the above function? Please tell.

**Comment by sairish2001** [comment]
Make a PR ,this condition will be treated in next issue

**Comment by anjali7786** [comment]
Okay sir

**Comment by anjali7786** [comment]
![pg](https://user-images.githubusercontent.com/57794837/113686384-d37fa580-96e4-11eb-80fa-8dbd148cfb1a.PNG)

@sairish2001 sir, .toFixed(3) method is not working for some steps. Please see.

**Comment by sairish2001** [comment]
may be because it's a string
try to convert it into Float and then apply fixed precision

`parseFloat(____).toFixed(3)`
