### ISSUE TITLE
To add Properties of Logarithm

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/MakesMathEasy#400]
I would like to add all the properties of Logarithm.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 March,2021 (11:59 PM IST)
