### ISSUE TITLE
mislocation of Volume CSa tsa

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/MakesMathEasy#402]
I think Volume Csa and Tsa should be placed in Graph and SHapes area and not in general maths as all the shapes are mentioned in there . It will be best suited there

**Comment by sairish2001** [comment]
Go ahead
Deadline 26 March,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@sairish2001 Created a PR Have a look!
