### ISSUE TITLE
Bug in Rules for Roots of Quadratic Equation

### ISSUE THREAD

**Issue by AB-san** [sairish2001/MakesMathEasy#408]
## **Describe the bug**

A html tag is visible which is </p>

 

## **Screenshots**

 
![image](https://user-images.githubusercontent.com/71064674/112255213-cba51780-8c87-11eb-9b94-b76363103d84.png)

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 26 March,2021 (11:59 PM IST)
