### ISSUE TITLE
Bug in TSA of prism

### ISSUE THREAD

**Issue by AB-san** [sairish2001/MakesMathEasy#409]
## **Describe the bug**

Now -> TSA= LSA+ Area of Base || but, it must be -> TSA=LSA+2x Area of Base

## **Possible solution**

Modify the formula

## **Screenshots**

 
![image](https://user-images.githubusercontent.com/71064674/112258275-3c4e3300-8c8c-11eb-9acd-81cb1b25f2bb.png)

**Comment by AB-san** [comment]
please assign me for this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 26 March,2021 (11:59 PM IST)
