### ISSUE TITLE
Design 'Tip of the day' under the search bar

### ISSUE THREAD

**Issue by kavyamehra20** [sairish2001/MakesMathEasy#41]

**Comment by kavyamehra20** [comment]
Can I work on this issue ?

**Comment by sairish2001** [comment]
@vmk8826 Sorry! First come first server basis

**Comment by sairish2001** [comment]
@kavyamehra20 Feel free to ask your doubts, if any

Deadline 13 March,2021 (11:59 PM IST)

**Comment by vmk8826** [comment]
okay sir

**Comment by kavyamehra20** [comment]
Kindly Check!

**Comment by sairish2001** [comment]
@kavyamehra20 What to check? Have you made the PR?

**Comment by akankshaaa-08** [comment]
@sairish2001 Is this issue currently assigned to somebody? If not, can it be assigned to me?

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 20 March,2021 (11:59 PM IST)

**Comment by lakshita15** [comment]
hi , i'm gssoc'21 participant
I want to work on this issue
Can you assign issue to me ?
i'll submit before deadline
