### ISSUE TITLE
Adding Trignometric Equation and it's General Solution

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/MakesMathEasy#411]
In Trigonometry section,I would like to add a section for Trignometric Equation and it's General Solution in tabular format

**Comment by bitaashna** [comment]
@sairish2001 I would like to work on this.Can you please assign it to me.

**Comment by sairish2001** [comment]
can you please elaborate this issue?

**Comment by bitaashna** [comment]
No, not a calculator,just adding formulae section:-
as given below
![Screenshot from 2021-03-24 16-40-41](https://user-images.githubusercontent.com/57864526/112301423-edba8c00-8cbf-11eb-908a-492c8eded487.png)

**Comment by RaveenaBhasin** [comment]
@bitaashna I have already added this in the trigonometry section. You can try creating a calculator for that

**Comment by bitaashna** [comment]
ok @RaveenaBhasin .
