### ISSUE TITLE
Adding Domain and Range of Inverse Trignometric function

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#412]
In trigonometry section,I would like to add a section For Domain and range of inverse functions in table format

**Comment by bitaashna** [comment]
@sairish2001 I would like to work on this.Can you please assign it to me.

**Comment by sairish2001** [comment]
you mean to add Calculator?

**Comment by bitaashna** [comment]
No.I mean to add their range and domain like 
for sin inverse x domain is -1 to 1 and range - pie/2 to pie/2
and many more

**Comment by sairish2001** [comment]
Go ahead!
Deadline 28 March,2021 (11:59 PM IST)
