### ISSUE TITLE
Tsa, lsa of frustum of cone

### ISSUE THREAD

**Issue by AB-san** [sairish2001/MakesMathEasy#413]
## **Describe the bug**

(In frustum of cone) Declare the variable "L" just the way it is declared for cone , just for better understanding of the formula
 

## **Screenshots**

 
![image](https://user-images.githubusercontent.com/71064674/112259898-10807c80-8c8f-11eb-9064-6cfb44137e17.png)

**Comment by AB-san** [comment]
Assign me please

**Comment by sairish2001** [comment]
Go ahead
Deadline 26 March,2021 (11:59 PM IST)
