### ISSUE TITLE
Output of Decimal/Binary Converter

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#415]
## **Is your feature request related to a problem? Please describe.**

If we first perform a conversion and then remove the value to be converted it shows NaN and if we enter wrong values in Binary converter then Too it shows NaN

## **Describe the solution you'd like**

Adding conditions in the function so that if nothing is entered it should not show any output and if invalid binary number is entered it should show "Binary numbers only have 0's and 1's"

![Screenshot (148)](https://user-images.githubusercontent.com/66053534/112262440-a9b19200-8c93-11eb-91af-100a1c0c5a89.png)
![Screenshot (149)](https://user-images.githubusercontent.com/66053534/112262444-ab7b5580-8c93-11eb-8659-2334abe54cb7.png)

Please assign this to me

**Comment by sairish2001** [comment]
Go ahead
Deadline 27 March,2021 (11:59 PM IST)
