### ISSUE TITLE
adding some more properties to determinants

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/MakesMathEasy#418]
## **Is your feature request related to a problem? Please describe.**

- I would like some more properties to determinants section
![Capture](https://user-images.githubusercontent.com/70858557/112264476-f8acf680-8c96-11eb-9f58-a36a59a9470d.PNG)

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

please assign this to me under GSSoC

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 March,2021 (11:59 PM IST)
