### ISSUE TITLE
Add volume , LSA and TSA of frustum of pyramid and also for different types of prism and pyramid

### ISSUE THREAD

**Issue by AB-san** [sairish2001/MakesMathEasy#421]
There are more than one type prism for ex- pentagonal prism
There are more than one type of pyramids also ex- square pyramid, pentagonal pyramid, etc
Theres one more solid called frustum of pyramid
I would like to add the volume, tsa,lsa of those 3d objects

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 March,2021 (11:59 PM IST)
