### ISSUE TITLE
Bug in log calculator when base is <=0

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#423]
## **Describe the bug**

The base of log cannot be zero but if we enter 0 then it shows the output to be 0 instead of showing a warning. Also if a negative number is entered as a base it shows the warning enter an integer whereas a negative number is also a integer so it should show enter positive integer.

Please assign this to me.

![Screenshot (156)](https://user-images.githubusercontent.com/66053534/112269285-306b6c80-8c9e-11eb-955b-661e8000336a.png)
![Screenshot (157)](https://user-images.githubusercontent.com/66053534/112269293-319c9980-8c9e-11eb-9cc8-09b4b7e54fae.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 March,2021 (11:59 PM IST)

Also remove this alert popup as warning, try to show some text warning instead

**Comment by khareyash05** [comment]
@kanishka8276 also type the condition for the base cannot be equal to one

**Comment by kanishka8276** [comment]
> @kanishka8276 also type the condition for the base cannot be equal to one

Yes sure!
