### ISSUE TITLE
Adding Rhombus under Graphs and Shapes

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/MakesMathEasy#425]
I would like to add Rhombus also in the calculator of shapes part. Please assign this to me under GSSoC. 

![Capture](https://user-images.githubusercontent.com/70858557/112274427-7c211480-8ca4-11eb-802b-5172fd7fc0ab.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
Will you apply Working to these input fields?

**Comment by madihamallick** [comment]
Yes. I will
