### ISSUE TITLE
add location of roots and corresponding conditions

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#429]
Hi! I would like to add location of roots section under which i will state if lets say roots are +ve then what is the condition for equation or if both roots are equal but opposite in sign then what is the condition

**Comment by sairish2001** [comment]
Can you please provide an example for it?

**Comment by khareyash05** [comment]
![Screenshot_2021-03-25-06-23-52-406_com.android.chrome.jpg](https://user-images.githubusercontent.com/60147732/112402533-b76a2480-8d32-11eb-806b-0ee2a25a94be.jpg) 
@sairish2001 see this

**Comment by khareyash05** [comment]
@sairish2001 Shall I work on it?

**Comment by khareyash05** [comment]
@sairish2001 Shall I work on it?

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@sairish2001 Created a PR Have a look!
