### ISSUE TITLE
To add more Formulae in the section Definite Integration Formulae as many formulae are missing

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/MakesMathEasy#432]
Definite Integration Inequality formulae , one periodicity properties and few standard results are missing in the section Definite integration formulae.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)
