### ISSUE TITLE
Adding Tetrahedron under Graphs and Shapes

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#434]
I would like to add regular tetrahedron in the calculator of shapes part. 
It will be including : 

- volume calculation,
- height calculation,
- circumradius calculation and 
- height calculations

I will mention the formulae and along with them apply calculation part to it.

**Comment by bitaashna** [comment]
@sairish2001 I would like to work on the above mentioned issue.
Please assign it to me.

**Comment by sairish2001** [comment]
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)
