### ISSUE TITLE
Adding calculator for Hemisphere,Hollow sphere and hollow cylinder in calculators for  3d shapes

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#436]
I would like to add three calculators:
1. hemisphere
2. hollow sphere
3. hollow cylinder

**Comment by bitaashna** [comment]
@sairish2001 I would like to work on this.Please assign it to me.

**Comment by sairish2001** [comment]
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)
