### ISSUE TITLE
Bug in Calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/MakesMathEasy#437]
## **Describe the bug**

When you divide any number by 0 there is no result printed the expected output is Not Defined

## **Possible solution**

- Modify the js code for calculator

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/67696867/112304678-c5cd2780-8cc3-11eb-89e6-3ac1dfb4f127.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Actually I don't want such errors to come

**Comment by abhijeet141** [comment]
Okk Sir
