### ISSUE TITLE
To add Decimal / Hexadecimal converter 

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#438]
## **Describe the solution you'd like**

- I want to add a convertor that will convert decimal to hexadecimal and vice versa.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
Do implement in **Binary to Hexadecimal converter** under Binary Calculations
