### ISSUE TITLE
To add Decimal/Octal Converter

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#439]
## **Is your feature request related to a problem? Please describe.**

no theres no problem

## **Describe the solution you'd like**

I want to add a converter that can directly convert Decimal to Octal Number system and vice versa

**Comment by AB-san** [comment]
Please assign me this issue I will start working on it as soon as possible

**Comment by sairish2001** [comment]
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
Do implement in **Octal/ Binary converter** under **Binary Calculations** category.
