### ISSUE TITLE
Adding Kite under Graphs and Shapes

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/MakesMathEasy#440]
I would like to add **Kite** under Graphs and Shapes along with the working of input fields. Please assign this to me under GSSoC.

**Comment by sairish2001** [comment]
I think kite and rhombus are similar?
and the issue for rhombus is already opened

**Comment by madihamallick** [comment]
okay.

**Comment by madihamallick** [comment]
I don't think they are similar. Rhombus is a parallelogram whereas Kite is a quadrilateral.  Also their perimeter and side formula's are different, so it would be better if I add this too.

**Comment by sairish2001** [comment]
Go ahead
Deadline 30 March,2021 (11:59 PM IST)

**Comment by madihamallick** [comment]
Thank you.

**Comment by madihamallick** [comment]
Please assign this to me, so that I can start working.
