### ISSUE TITLE
vector calculus theorems

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/MakesMathEasy#441]
Hi! I would like to add 3 fundamental theorems of vector calculus which are Gauss Divergence Theorem,Stokes Theorem and Green's Theorem with proofs

**Comment by sairish2001** [comment]
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@sairish2001 Created a PR Have a look!
