### ISSUE TITLE
r1 denotes radius of excircle (Bug in formula)

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#446]
## **Describe the bug**

r1 is the excircle not incircle

## **Possible solution**

replace excircle by incircle

## **Screenshots**

![Screenshot from 2021-03-24 18-00-09](https://user-images.githubusercontent.com/57864526/112311001-3592e080-8ccb-11eb-9514-7d8e78dd8e2c.png)

**Comment by bitaashna** [comment]
I would like to correct it.Please assign it to me. @sairish2001

**Comment by sairish2001** [comment]
Go ahead!
Deadline 27 March,2021 (11:59 PM IST)
