### ISSUE TITLE
Adding Some more formulae in Solution of triangle section

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#448]
I would like to add some more formulae in Solution of triangle as many are missing:-
I would like to add following Formulae;-

-  radius of incircle
- length of angle bisector 
- length of median
- length of altitude
- relation between length of three medians and three sides
- relation between area of inscribed and excribed circle
- relation between angles of a triangle and its incircle radii and circumcircle radii
- incentre
- position of circumcentre for acute,right and obtuse angled triangle
- position of incentre and centroid 
- position of orthocentre for acute,right and obtuse angled triangle

**Comment by bitaashna** [comment]
@sairish2001 I would like to work on this. can you please assign it to me.

**Comment by sairish2001** [comment]
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)
