### ISSUE TITLE
Design a Header for the project with the name and logo of this project

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/MakesMathEasy#450]
## **Is your feature request related to a problem? Please describe.**

No, it's not a problem just want to make it look good by adding a header section that contains the logo and name of the project.

## **Describe the solution you'd like**
I Will design the header part.

I'm a gssoc participant please assign this issue to me.

**Comment by sairish2001** [comment]
Actually it's a webapp, I would like it to look more like an app rather than website
