### ISSUE TITLE
"%" is not changing to "DEG" on clicking more

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#451]
## **Is your feature request related to a problem? Please describe.**
"More" in the calculator should change to "less" after More is clicked and other functions are displayed and more() function is called.

Please assign this to me.

![Screenshot (161)](https://user-images.githubusercontent.com/66053534/112332962-2ec29880-8ce0-11eb-8fe1-ec18fb48cb5b.png)

**Comment by sairish2001** [comment]
On clicking more % text should change to DEG
also on clicking more change it's text to less as you said

Logic for % to DEG is already implemented, there's a bug which is not changing it's innertext

**Comment by sairish2001** [comment]
Go ahead
Deadline 29 March,2021 (11:59 PM IST)
