### ISSUE TITLE
Suggestion for AP calculator.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#452]
In Arithmetic calculator Adding an option to get a AP instead of first term and common difference from the user and find it's sum and print it to the n terms  where user have to input n and the series.

Please assign this to me.

**Comment by sairish2001** [comment]
can you please elaborate a little bit?

**Comment by kanishka8276** [comment]
@sairish2001  I mean right now the user enters the common difference, first element and n.
I am suggesting that we can add another option to the AP calculator where user can enter an AP of 3 or more numbers and n then our function will find the common difference, the sum up to n numbers and also print the series till n.

**Comment by sairish2001** [comment]
Great!
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
anyone working on this issue...?
if no can i work on it

**Comment by kanishka8276** [comment]
@satyampgt4  Yes I am working on this issue. Actually previously their were bug in the site and then I got busy with my exams. Just give me a day if I am able to solve the issue otherwise I will let you know and then you can continue with this.
