### ISSUE TITLE
Adding option to calculate inverse of square matrix.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#453]
Adding an option to calculate inverse of square matrix in single matrix calculator.
Please assign this to me.

**Comment by sairish2001** [comment]
You will add just option?

**Comment by kanishka8276** [comment]
> You will add just option?

No, the associated functions also!

**Comment by sairish2001** [comment]
Do show steps, if possible

**Comment by sairish2001** [comment]
Go ahead!
Deadline 30 March,2021 (11:59 PM IST)

**Comment by kanishka8276** [comment]
@sairish2001  I won't be able to complete this issue,so please assign this issue to someone else.
