### ISSUE TITLE
translation and rotation of functions

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#465]
I will add steps on when the function changes what should be the steps
ex - if f(x)-> f(-x) then how will the graph of function change
if f(x)->|f(x)| how will the graph change

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@sairish2001 Attached a PR Have a look

**Comment by khareyash05** [comment]
@sairish2001 Just a small request . If possible could you please increase the level of the issue because I personally feel level 1 is a level low. If possible.
Thanx
