### ISSUE TITLE
Gssoc'21 Share to WhatsApp button is not working in Desktop version.

### ISSUE THREAD

**Issue by arpit456jain** [sairish2001/MakesMathEasy#471]
## **Describe the bug**

"share to WhatsApp" button is not working in Desktop version.
I am attaching a video for better understanding my issue.

https://user-images.githubusercontent.com/55352601/112425592-58210a00-8d5c-11eb-8cbe-501a35049e96.mp4

## **Possible solution**

The link in the a tag is wrong.
I had already fixed it.
After my changes the website will look like this.

https://user-images.githubusercontent.com/55352601/112425813-bcdc6480-8d5c-11eb-91b8-a4437532775a.mp4

It is now working fine in Desktop and mobile I had rechecked it.
## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
Kindly assign me this issue

**Comment by arpit456jain** [comment]
@janvi01 @AishwaryaKaranth @Karthik-Nayak98  Please assign me this issue if possible

**Comment by Karthik-Nayak98** [comment]
I am not the maintainer @arpit456jain. He is the maintainer@sairish2001.

**Comment by arpit456jain** [comment]
ok @Karthik-Nayak98 sir .
@sairish2001 sir please assign me this issue.

**Comment by arpit456jain** [comment]
@sairish2001 sir please assign me this issue.

**Comment by sairish2001** [comment]
@arpit456jain It is working fine, I just checked.
Maybe you denied some permissions in your browser
