### ISSUE TITLE
Adding probability of a event calculator

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/MakesMathEasy#479]
## **Is your feature request related to a problem? Please describe.**

I want to implement a calculator to find probability of a event by asking no of possible trials and actual trails

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Do show steps for it

Go ahead
Deadline 31 March,2021 (11:59 PM IST)
