### ISSUE TITLE
Bug in mixed to improper fraction calculator

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#483]
## **Describe the bug**

Wrong formula for mixed to improper fraction is implemented.

## **Possible solution**

- Implement the correct formula.

## **Screenshots**

![Screenshot (172)](https://user-images.githubusercontent.com/66053534/112482541-2df03c00-8d9e-11eb-9a2d-edf581cbc170.png)

Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)
