### ISSUE TITLE
polar representation

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/MakesMathEasy#488]
## Proposal

add polar representation of complex number

(A clear and concise description of what the proposal is.)

**Comment by satyampgt4** [comment]
i would like to work on it under gssoc21

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
while solving angle i am getting my angle in decimal how can i get it in fraction

**Comment by sairish2001** [comment]
user nerdamer.evaluate, you can find this in appjs/simplecallogic.js

by evaluating using nerdamer you will get answer in fractions
