### ISSUE TITLE
Presentation Enhancement

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/MakesMathEasy#495]
## **Is your feature request related to a problem? Please describe.**

- I feel the correct way of presentation is also one of the good way to attract users. I arithmetic progression series shows extra comma(,) after the series or NaN 

## **Describe the solution you'd like**

- I want to remove that extra comma using string handling.
![Presentation Improvement](https://user-images.githubusercontent.com/55992140/112555393-1fca0c00-8dee-11eb-8588-a7e08b534cfc.jpg)

**Comment by SarthakKeshari** [comment]
Kindly assign this to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Go ahead
Deadline 30 March,2021 (11:59 PM IST)

**Comment by SarthakKeshari** [comment]
I assure you to abide by the code of conduct and complete the task before deadline
