### ISSUE TITLE
Adding calculator to conic section

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#497]
## **Is your feature request related to a problem? Please describe.**

- My feature is to add a calculator to the conic section part of the website. Since it only contains a table for user to understand parabola, hyperbola and eclipse(there is also spelling error in website).

## **Describe the solution you'd like**

- I want to add a reliable calculator for the advantage of the user in order to calculate the required conic section equations.

I am attaching an image which shows absence of calculator in the conic section part of the website
![Adding calculator to conic section](https://user-images.githubusercontent.com/55992140/112569404-1cdd1480-8e0a-11eb-8743-b650101200f4.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this to me @sairish2001

**Comment by sairish2001** [comment]
Can you show steps for it?

Go ahead
Deadline 31 March,2021 (11:59 PM IST)

**Comment by SarthakKeshari** [comment]
I will go through the concept of conic section and will get back to you regarding the steps
