### ISSUE TITLE
Function calling issue in Log Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#505]
## **Describe the bug**

- When in log calculator once a negative value is passed to the function it does not respond further for correct values

## **Possible solution**

- Altering the required function

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- 
![Log Cal_error](https://user-images.githubusercontent.com/55992140/112600032-aacef480-8e36-11eb-8d62-75def1f2a88a.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)
