### ISSUE TITLE
Adding  joint  probability of independent and mutually exclusive events in probability section

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/makesmatheasy#509]
## **Is your feature request related to a problem? Please describe.**

I want to add joint probability( events A and B occur on a single performance of an experiment, )
## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)
