### ISSUE TITLE
Adding Time and Work problems.

### ISSUE THREAD

**Issue by Kriti7744** [sairish2001/makesmatheasy#510]
I want to include a section of Time and Work problems in the general maths section as they are an essential part of any major competitive exam and will be highly beneficial for the visitors.

**Comment by Kriti7744** [comment]
Please assign me to work on this

**Comment by sairish2001** [comment]
Can you please show me an example for it?

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.
