### ISSUE TITLE
Isosceles triangle working of input field

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#512]
## **Describe the bug**

- Though there is function for working of input fields for isosceles triangle it is not working. I would like to fix this. Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![Capture](https://user-images.githubusercontent.com/70858557/112653641-a3c6d700-8e74-11eb-929f-0796ff4412f6.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)
