### ISSUE TITLE
Trignometry missing the sin x,cos x,etc. calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/MakesMathEasy#515]
## **Is your feature request related to a problem? Please describe.**

- There should be a calculator to address users trignometric calculations

## **Describe the solution you'd like**

- Add the required calculators to work on radiians and degrees

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me

**Comment by sairish2001** [comment]
These trigonometry calculations are already implemented in the calculator

**Comment by sairish2001** [comment]
![image](https://user-images.githubusercontent.com/60106112/112677253-80f5ec00-8e8f-11eb-95b5-faae31dd45ce.png)

**Comment by SarthakKeshari** [comment]
Ok sir

**Comment by SarthakKeshari** [comment]
Sir will the calculator handle both radians and degree ?
