### ISSUE TITLE
Adding circles to conic sections

### ISSUE THREAD

**Issue by anjali494** [sairish2001/makesmatheasy#521]
## Proposal

(A clear and concise description of what the proposal is.)

I would like to add circles under conic sections. I will make similar tables giving different equations of circles and their corresponding equations for tangents and normals. 

I am a GSSOC'21 participant and would like to work on this issue.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
