### ISSUE TITLE
10-excess-3 binary code

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#523]
## Proposal
excess-3 code calculator
(A clear and concise description of what the proposal is.)

**Comment by satyampgt4** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
i would like to work on it

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
