### ISSUE TITLE
Trignometry section missing calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#524]
## **Is your feature request related to a problem? Please describe.**

- Trignometry section missing the sin x,cos x,etc. calculator

## **Describe the solution you'd like**

- A calculator for providing instant calculated value for angle in radians and degrees. This can be achieved by using Math functions in js

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by SarthakKeshari** [comment]
I have raised to issue to address angles both in radians and degree

**Comment by sairish2001** [comment]
This is already implemented in Calculator.
it gives output for both radians and degrees
