### ISSUE TITLE
Its mentioned in BCD that it is converting Binary to BCD but there is typing error it should be Decimal to BCD 

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#526]
## **Describe the bug**

Its mentioned in BCD that it is converting Binary to BCD but there is typing error it should be Decimal to BCD 

## **Possible solution**

- only to replace binary with decimal 

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/67696867/112683387-7b040900-8e97-11eb-860b-61f18dc371a6.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 30 April,2021 (11:59 PM IST)
