### ISSUE TITLE
Enhancing presentation of GP Sum

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#527]
GP after taking required input from the user does't show the series its working on. So proper presentation is needed similar to that of AP series.

AP Sum Presentation
![AP Sum Presentation](https://user-images.githubusercontent.com/55992140/112684269-c79c1400-8e98-11eb-85c6-7782c5298233.PNG)

GP Sum Presentation
![Attention - GP Sum Presentation](https://user-images.githubusercontent.com/55992140/112684284-ccf95e80-8e98-11eb-9632-647058c35920.PNG)

Hence, GP Sum Presenation also needs to be enhanced for better user understanding and fulfiling expectation

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
