### ISSUE TITLE
Plot angle to be rectified

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#533]
## **Describe the bug**

- The angle plot section displays same kind of output on entering 90 and -270. Hence angle direction is disobeyed.

## **Possible solution**

- Solution to it is to rectify the mathematics involved in display function

## **Screenshots**

- Erroneous screenshot 
![Attention - Error in ploting](https://user-images.githubusercontent.com/55992140/112687404-74789000-8e9d-11eb-9fee-85e1e39f2a72.PNG)

- Right diagram should have been
![Correction to Error in ploting](https://user-images.githubusercontent.com/55992140/112687509-9a9e3000-8e9d-11eb-8040-6638d2ead1fe.jpeg)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
