### ISSUE TITLE
To add properties of Binomial Theorem 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#535]
## **Is your feature request related to a problem? Please describe.**
No problem but 
I would just like to add some useful expansions of binomial theorem and also Properties of Binomial Coefficients, under your desired section.

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)

**Comment by Ayushgup85** [comment]
is this issue still open?If open, can i work on this issue?

**Comment by AB-san** [comment]
> is this issue still open?If open, can i work on this issue?

Actually I have already sent a pr linked to this issue . Waiting for its approval.
