### ISSUE TITLE
To add properties of Probability 

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#536]
## **Describe the solution you'd like**

-I would like to add properties of probability under different section which will display all the properties

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)

**Comment by Ayushgup85** [comment]
is this issue still open?If open, can i work on this issue?

**Comment by abhijeet141** [comment]
Hi @Ayushgup85 yes this issue is open and its date has been extended because my exams are going on.

**Comment by sairish2001** [comment]
Go ahead
Deadline 6 April,2021 11:59 PM IST
