### ISSUE TITLE
Simple Probability calculator wrong answer

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#537]
## **Describe the bug**

- Simple probability calculator produces incorrect results. Eg - It work even for No. favourable outcomes > Total no. of outcomes

## **Possible solution**

- Rectifying the mathematical calculation and putting a check over incorrect inputs

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Attention - Probability wrong output](https://user-images.githubusercontent.com/55992140/112691879-f8ce1180-8ea3-11eb-8cda-c821d4c538f5.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
