### ISSUE TITLE
To add Hexadecimal/Octal Converter

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#538]
## **Describe the solution you'd like**

I would like to add a converter that can directly convert Hexadecimal to Octal Number system and vice versa.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
anyone working on this issue...?
as Deadline is over can i work on it

**Comment by abhijeet141** [comment]
> anyone working on this issue...?
> as Deadline is over can i work on it

Yes i am working on this issue actually my exam were going on i will complete it today
