### ISSUE TITLE
Right-angle triangle working of input field

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#541]
## **Describe the bug**

Though there is function for working of input fields for right angle triangle it is not working. I would like to fix this. Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

![bug](https://user-images.githubusercontent.com/70858557/112711571-65223280-8eef-11eb-90b6-36d5ff2e2c64.PNG)

- If applicable, add screenshots to help explain your problem.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)

**Comment by madihamallick** [comment]
I made a mistake. I just made a PR for fixing the bug in Rhombus part and that PR fixes this issue too, which was just merged #543. Kindly suggest what should I do now. Should I close this now? Kindly update the label
