### ISSUE TITLE
adding working of input fields in parallelogram

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#542]
There is no function for the calculation of working of input fields for parallelogram under Graphs and Shapes section. I would like to add that, kindly assign this to me under GSSoC. 
![bug1](https://user-images.githubusercontent.com/70858557/112711802-242b1d80-8ef1-11eb-922b-8689f3c504d6.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
