### ISSUE TITLE
Bug in Rhombus part under Graphs and Shapes

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#543]
## **Describe the bug**

The Area of circle is being displayed under Rhombus section. I would like to remove that. Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![bug2](https://user-images.githubusercontent.com/70858557/112711857-9439a380-8ef1-11eb-834c-88dcac255ff5.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 30 March,2021 (11:59 PM IST)
