### ISSUE TITLE
In SPI/CGPA converter.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#547]
Rules is displayed like a button with hover effect but it's a heading in SPI/CGPA converter. User may try clicking it many times but wouldn't get any other output.

![Screenshot (176)](https://user-images.githubusercontent.com/66053534/112715889-1d100980-8f09-11eb-8f92-90993d088610.png)

Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1
30 March,2021 (11:59 PM IST)
