### ISSUE TITLE
Bug in ascending/descending order.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#549]
If a floating number is entered in the set then it shows wrong output. But it should work fine for all numbers , integers and decimals both.
![Screenshot (177)](https://user-images.githubusercontent.com/66053534/112715999-cf47d100-8f09-11eb-9fb7-21117c13d7db.png)
![Screenshot (178)](https://user-images.githubusercontent.com/66053534/112716002-d1119480-8f09-11eb-98c7-88e9701efa15.png)

Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
