### ISSUE TITLE
Bug in polar representation of complex number.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#552]
In polar representation the magnitude is multiplied with both cosine and sine terms. But in the output the magnitude is multiplied only with the cosine term.

Please assign this to me.

![Screenshot (179)](https://user-images.githubusercontent.com/66053534/112717242-551b4a80-8f11-11eb-817f-287ae0ea921c.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
