### ISSUE TITLE
Changing UI of SPI/CGPA calculator.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#562]
## **Is your feature request related to a problem? Please describe.**
The UI of SPI/CGPA calculator is not user friendly. It tough for a user to think that after clicking on the text SPI/CGPA a dialogue box will open as it doesn't look like a link and it's not easily understood.

## **Describe the solution you'd like**
Instead of using a dialogue box we can show the option to convert from SPI to CGPA and vice versa in the main page only instead of a separate dialogue box.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
