### ISSUE TITLE
Bug in title of the page.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#564]
The title of the page  is showing the code for joint probability also.

Please assign this to me.

**Comment by khareyash05** [comment]
@kanishka8276 Sorry but I already opened the issue before. Kindly close this issue

**Comment by kanishka8276** [comment]
> @kanishka8276 Sorry but I already opened the issue before. Kindly close this issue

Yeah sure! Actually we both opened it within few seconds.

**Comment by khareyash05** [comment]
@kanishka8276 Yeah just a matter of few seconds. Thanx
