### ISSUE TITLE
Wrongly Wriiten formula of CSA and TSA of hollow sphere

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#567]
I would like to correct the formula.It should not be Internal surface area or external surface area, 
In that column corresponding formula for CSA and TSA shoul be written
![Screenshot from 2021-03-27 22-26-02](https://user-images.githubusercontent.com/57864526/112728133-b4964c00-8f4b-11eb-8a72-3c43a5da3ecb.png)

**Comment by bitaashna** [comment]
@sairish2001 Please assign it to me.I would like to work on it

**Comment by sairish2001** [comment]
Go ahead
Deadline 30 March,2021 (11:59 PM IST)
