### ISSUE TITLE
Title tag misplacement

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#569]
## **Describe the bug**

- Open and close <title> tag can be observed misplaced

## **Possible solution**

- Making the required changes in the doc to setup the code properly

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![WhatsApp Image 2021-03-27 at 10 32 43 PM](https://user-images.githubusercontent.com/55992140/112728343-ce845e80-8f4c-11eb-8363-0f98ab5ea010.jpeg)

**Comment by SarthakKeshari** [comment]
Kindly assign this task to me @sairish2001

**Comment by khareyash05** [comment]
@SarthakKeshari I have already created the issue #563 
Kindly close the issue

**Comment by SarthakKeshari** [comment]
@sairish2001 I am closing this issue since its already been described by @khareyash05 .
Thankyou @khareyash05 for the information
