### ISSUE TITLE
Adding straight line section to graphs and shapes with some properties and formulae

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#571]
I would like to add Staight line section in graphs and shapes section.
I would like to add following:

- Centroid of staright lines with given coordinates
- position of circumcentre 
- position of orthocentre
- angle between two lines
- area of triangle formed by 3 straight lines
- parametric equation of straight line
- length of perpendicular
- foot of perpendicular
- image of a point with respect to a line
- distance between two parallel lines
- condition for 3 lines not forming a triangle

**Comment by bitaashna** [comment]
@sairish2001 I would like to work on it.PLease assign it to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
