### ISSUE TITLE
Serious changes to whole Probability section

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#573]
## **Describe the bug**

- Since new changes have been made to probability section. Initially it was simple probabilty now it has two subheads namely
   1) Empirical Probability
   2) Joint Probabilty
   But they are generating very wrong results.
Few examples are -  
a) Showing probability greater than 1(which is mathematically impossible)
b) Showing favourable outcomes > total no. of outcomes even at times when it is not so, etc.

## **Possible solution**

- Redefining all the functions involved.

## **Screenshots**
![Attention - Empirical Probability many errors](https://user-images.githubusercontent.com/55992140/112728886-6f741900-8f4f-11eb-8829-de80af42c574.PNG)
![Attention - Joint Probability many errors](https://user-images.githubusercontent.com/55992140/112728889-70a54600-8f4f-11eb-9198-fcf08179b9ab.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
