### ISSUE TITLE
Adding Mathematical reasoning section under  General Maths section

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#574]
I would like Add Mathematical reasoning section under  General Maths section which will include:

- Table for basic logical connections
- Tautology and Contradiction
- converse
- Contrapositive
- negation
- Some other important formulae

**Comment by bitaashna** [comment]
@sairish2001 Please assign it to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)
