### ISSUE TITLE
Convergence and divergence Wrongly placed

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#577]
I think this section should be included in calculus section rather than Linear algebra

**Comment by bitaashna** [comment]
@sairish2001 PLease assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
Go ahead
Deadline 30 March,2021 (11:59 PM IST)
