### ISSUE TITLE
Statistics section calcultor need to be added

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#586]
## **Is your feature request related to a problem? Please describe.**

- Calculator needs to be added for mean, median, mode etc. in the statistics section

## **Describe the solution you'd like**

- Add the required functionality

**Comment by SarthakKeshari** [comment]
Please assign this issue to me @sairish2001

**Comment by shrey27tri01** [comment]
@SarthakKeshari Please go ahead with the issue :)
Deadline 2nd April 2021, 11:59 PM IST

**Comment by sairish2001** [comment]
@SarthakKeshari any update?

**Comment by SarthakKeshari** [comment]
Yes, I would be generating the PR atmost by 4pm
