### ISSUE TITLE
Simple interest and compound interest negative input and output error

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#589]
## **Describe the bug**

- Simple interest and compound interest calculator functioning over negative values needs to be restricted since money amount, time and interest rate can't be negative.

## **Possible solution**

- Setting up value checks at appropriate places inside the function.

## **Screenshots**

- ![Attention - Simple interest and compound interest negative values](https://user-images.githubusercontent.com/55992140/112732715-9cc9c280-8f61-11eb-9409-f1e02ee8e014.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 11:59 PM IST
