### ISSUE TITLE
Mathematical functions working on non-numeric values

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#590]
## **Describe the bug**

- Mean, Median, Mode etc. working even in case of non-numeric characters

## **Possible solution**

- Making appropriate change in the codebase

## **Screenshots**

![Attention - Mean, Median and Mode non-numeric values working](https://user-images.githubusercontent.com/55992140/112732915-d64efd80-8f62-11eb-827f-0acfe341fee7.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 11:59 PM IST
