### ISSUE TITLE
Bug in output of polar representation for negative values.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#592]
## **Describe the bug**
When either the real or imaginary part is negative the argument is negative . The output is not well formed in polar representation of complex number it seems that the argument is subtracted from pi but its actually multiplied. 
Please assign this to me.

![Screenshot (189)](https://user-images.githubusercontent.com/66053534/112733258-d2bc7600-8f64-11eb-9080-b05983792090.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April,2021 11:59 PM IST
