### ISSUE TITLE
Adding "Functions " section

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#603]
Adding functions section which will be including :

- even function
- odd function
- onto
- one one
- many one
- injective
- surjective
- bijective
- periodic
- symmetricity

**Comment by bitaashna** [comment]
@sairish2001 Please assign it to me.

**Comment by sairish2001** [comment]
So you are going to create Calculators for it?

**Comment by bitaashna** [comment]
Nope not calculators,Just writing the function and definitiens and formulae used

**Comment by bitaashna** [comment]
I thinks It's already there in sets ,relations and functon.
So, it's better to close it
