### ISSUE TITLE
Add a problem solver for Vectors.

### ISSUE THREAD

**Issue by kartikrupauliha** [sairish2001/makesmatheasy#607]
## **Is your feature request related to a problem? Please describe.**

- My feature is to add a calculator to the General Maths part of the website which goes by the name "Operations on Vectors"

## **Describe the solution you'd like**

- On entering values of two vectors and the angle between them, their scalar and vector products are calculated along with respective theory and formulae.

**Comment by kartikrupauliha** [comment]
Please assign me this issue.

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
is this issue is open
can i work on it

**Comment by Ankita297** [comment]
Can i work on this @sairish2001 @shrey27tri01 ?

**Comment by Ankita297** [comment]
Can i work on this @sairish2001 @shrey27tri01 ?

**Comment by sairish2001** [comment]
Issues for these are already created and implemented also
