### ISSUE TITLE
Adding Bayes Theorem Under Probability Section

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/makesmatheasy#609]
## **Is your feature request related to a problem? Please describe.**

I want to add Bayes theorem under probability section 

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by zhcet19** [comment]
@sairish2001 please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
