### ISSUE TITLE
Calculator is not showing up after clicking the icon

### ISSUE THREAD

**Issue by Alenjojo** [sairish2001/makesmatheasy#613]
## **Describe the bug**

When i click the ""icons/keys.svg"" the calculator is not popping up

## **Possible solution**

I assume the respective function is not getting called after clicking it

I'll try my best to fix it, if you assign me with this issue

**Comment by sairish2001** [comment]
Actually this bug is occurring due to one PR when it got merged, Now this issue is resolved.
