### ISSUE TITLE
Adding a section for 3 d geometry 

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#621]
I would like to add a 3d geometry section which will consist :-

1. - Distance from the Origin
2. - Distance between 2 point
3. - Division of a line joining 2 points
4. - Projection in 3D Space
5. - Direction cosines and direction Ratios of a Line in Cartesian Plane
6. - Direction cosine of line joining two given points
7. - Projection of line segment joining 2 points, on another line
8. - Angle between 2 lines in 3 Dimensional Space
9. - Projection of a plane area on 3 coordinate planes
10. - Area of a triangle:
11. - Concept of Plane in 3 Dimensional Geometry
12. - Normal Form of a Plane
13. - Intercept form
14. - Planes passing through 3 given points
15. - Angle between 2 planes
16. - Two sides of a plane
17. - Position of origin
18. - Two Intersecting plane

**Comment by bitaashna** [comment]
@sairish2001 Please assign me the above mentioned issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
