### ISSUE TITLE
Adding Applicatioon of Derivative section 

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#622]
I would like to add a section which will consist of application of derivative such as:-
Rate of Change of a Quantity
Increasing and Decreasing Functions
Monotonicity
Point of Inflection

**Comment by bitaashna** [comment]
@sairish2001 Please assign me the above mentioned issue.

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
