### ISSUE TITLE
Adding Coordinate Geometry Formulas and theorems

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#623]
Adding the following in this section:-

- Distance Formula: To Calculate Distance Between Two Points
- Midpoint Theorem: To Find Mid-point of a Line Connecting Two Points
- Angle Formula: To Find The Angle Between Two Lines
- Section Formula: To Find a Point Which Divides a Line into m:n Ratio
- Area of a Triangle in Cartesian Plane

**Comment by bitaashna** [comment]
@sairish2001 Please assign me the above mentioned issue!

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
