### ISSUE TITLE
Serious Bug in website

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#624]
## **Describe the bug**

-some links are again not clickable

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/112751480-e9f27680-8feb-11eb-8a5a-0f491960a3bf.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 April, 2021

**Comment by shrey27tri01** [comment]
@abhijeet141 Can you pause your work on this? There are other issues that need to be resolved before we can work on this. You can work on other issues meanwhile :)

**Comment by abhijeet141** [comment]
> @abhijeet141 Can you pause your work on this? There are other issues that need to be resolved before we can work on this. You can work on other issues meanwhile :)

Okay

**Comment by sairish2001** [comment]
@abhijeet141 Bugs are resolved now. You can move to next issues .Thanks
