### ISSUE TITLE
Adding Vector Algebra Section

### ISSUE THREAD

**Issue by bitaashna** [sairish2001/makesmatheasy#625]
Adding Vector Algebra Section which will consist of:

- Magnitude of a Vector
- Unit Vector
- Operations on Vectors
- Scalar Triple Product
- Vector Multiplication: Cross and Dot Product
- Components of Vectors (Horizontal & Vertical)

**Comment by bitaashna** [comment]
@sairish2001 Please assign it to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
