### ISSUE TITLE
Minor UI Changes

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#640]
## **Describe the bug**

- Fav button can be seen misplaced and enlarged

## **Possible solution**

- Making required updated to index.html over this section

## **Screenshots**
![Attention - Minor UI changes](https://user-images.githubusercontent.com/55992140/112777792-b4d43b80-9060-11eb-8f48-2fb678d4a979.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
There are some Major bugs in website due to one of the merged PR, which is causing this issue, now it is resolved
