### ISSUE TITLE
Currency Calculator working 

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#642]
## **Describe the bug**

- Currency Converter working over negative values

## **Possible solution**

- Make checks using if else statements and handling NaN conditions to

## **Screenshots**
![Attention - Currency coverter working on negative values](https://user-images.githubusercontent.com/55992140/112778700-b6066800-9062-11eb-91a5-b97112ea4ca6.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this task to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
