### ISSUE TITLE
Enhancing functionality of Simple interest and compound interest calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#643]
## **Is your feature request related to a problem? Please describe.**

- Adding features like compounded annually, half yearly or quaterly to the functionality of CI and SI calculator

## **Describe the solution you'd like**

- Will describe a function to handle this situation

For now there is no such functionality available
![Attention - CI and SI compounded](https://user-images.githubusercontent.com/55992140/112778925-3e850880-9063-11eb-94ce-89a9a34e65c7.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
