### ISSUE TITLE
Trapezium working of input fields

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#644]
There is no function for calculation of input fields for Trapezium under Graphs and Shapes and I would like to add that. kindly assign this to me undet GSSoC so that I can start working on it.

![Capture](https://user-images.githubusercontent.com/70858557/112791820-ead4e800-907f-11eb-877d-b096de721d5a.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
