### ISSUE TITLE
Bug in grey code converter.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#647]
## **Describe the bug**
The grey code converter is showing results also when a decimal number is entered instead of a binary number. Instead It should show a warning.

Please assign this to me.

![Screenshot (196)](https://user-images.githubusercontent.com/66053534/112800831-cc75e900-908d-11eb-8f01-10f9d4f2d06a.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
