### ISSUE TITLE
Bug in LCM/HCF/Factors.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#649]
## **Describe the bug**
If a letter is entered along with numbers then too it shows output and it shows the common factor is 1 instead of showing a warning.
Please assign this to me.

![Screenshot (199)](https://user-images.githubusercontent.com/66053534/112804710-588a0f80-9092-11eb-930d-ed76cc9b4c2f.png)
![Screenshot (200)](https://user-images.githubusercontent.com/66053534/112804718-5b850000-9092-11eb-9b35-89f3e545840c.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
