### ISSUE TITLE
Bug in joint probability calculator when number of favourable outcome is 0

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#651]
## **Describe the bug**
When the number of favourable outcomes is 0 it shows an error but the probability can be 0 so the output should be 0 not an error.
Please assign this to me.

![Screenshot (201)](https://user-images.githubusercontent.com/66053534/112818646-62673f00-90a1-11eb-98c7-ed7a76254d05.png)

**Comment by kanishka8276** [comment]
@sairish2001 Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
