### ISSUE TITLE
1s and 2s compliment calculator button is not working

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#653]
## **Describe the bug**

- 1s and 2s compliment calculator button is not working 
## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by sairish2001** [comment]
There are some Major bugs in website due to one of the merged PR, which is causing this issue, now it is resolved
