### ISSUE TITLE
Profit Loss over negative values

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#656]
## **Describe the bug**

- Profit/ Loss over a negative value is not permitted but this condtion is not taken care in the calculator

## **Possible solution**

- Provding required checks

## **Screenshots**
![Attention - Profit Loss negative values](https://user-images.githubusercontent.com/55992140/112876705-7469d180-90e3-11eb-820b-006b5834f8d5.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
