### ISSUE TITLE
Logo redesign

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#658]
## Proposal

Sir @sairish2001,
 The initial logo design is self-explanatory and has visual appeal but If you may allow me I would like to present a few logo designs for MakesMathEasy with an effort for more precise and professional look.

Thankyou

**Comment by sairish2001** [comment]
We don't have such plan of changing the Logo. But if you want you can give a try.

Do you want to?

**Comment by SarthakKeshari** [comment]
Yes sir I want to give a try to it. You make take your final decision after my logo presentation.

**Comment by SarthakKeshari** [comment]
Sir @sairish2001,
     I have worked out a logo keeping in mind the project title "**MakesMathEasy**" and tagline "Your answers just a click away".

I am attaching HD copy of the logo for reference but for the website I have the saved the same logo with a webfile format.
I would be glad to have your acceptance.

![MakesMathEasy logo](https://user-images.githubusercontent.com/55992140/113211573-46c38a80-9293-11eb-84d4-4898f35fd502.png)

Thankyou.

**Comment by SarthakKeshari** [comment]
@sairish2001 Sir,
     Kindly provide me with your valuable remarks over the logo

**Comment by sairish2001** [comment]
It looks good, but the previous one looks more trendy.

I respect your Contribution.

**Comment by SarthakKeshari** [comment]
Ok sir
