### ISSUE TITLE
Tagline

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#659]
## Proposal

Sir @sairish2001,
 Working on this project, I wish to know would you prefer a short and crisp tagline for MakesMathEasy webapp. If yes, I would like to present a handful of taglines, you may select the one you like the most.

Thankyou

**Comment by sairish2001** [comment]
Go ahead

**Comment by SarthakKeshari** [comment]
Thankyou Sir

**Comment by SarthakKeshari** [comment]
Sir I am putting up 14 taglines which I thought would best fit MakesMathEasy. I wish to know your choice and after I get to know the tagline chosen by you. I will create a pull request documenting the tagline and a short article as a description to tagline

![Taglines](https://user-images.githubusercontent.com/55992140/112929810-c38d2200-9136-11eb-8ccc-f804c6d345ad.PNG)

**Comment by sairish2001** [comment]
Either 
**Unfolding the complex to real**
or
**Your answers just a click away**

your suggestion?

**Comment by SarthakKeshari** [comment]
Sir @sairish2001,
     Both the selected taglines have there significance but I would give more weightage to "**Your answers just a click away**". 
Reason - The tagline lights up the idea of quick behaviour 'just a click' and 'Your answer' emphasis on the user's side of the webapp which shows the tagline to be a silent conversation with users. As well as a whole it talks about handedness of the webapp being servable to users on their finger tips.

Thankyou

**Comment by sairish2001** [comment]
Go ahead with this tagline
i.e.
Your answers just a click away

**Comment by SarthakKeshari** [comment]
Sure sir. I will do this in a formatted manner. I will prepare a proper document explaining the details of the tagline so that its description throws light over the content and aim of this project.

**Comment by sairish2001** [comment]
Go ahead with PR
add tagline in Readme
