### ISSUE TITLE
Calculate CP/SP if profit%/loss% is given

### ISSUE THREAD

**Issue by somya51p** [sairish2001/makesmatheasy#661]
## **Is your feature request related to a problem? Please describe.**

Adding option to calculate CP or SP if either profit or loss percent is given.

## **Describe the solution you'd like**

This addition would improvise the Profit and loss section calculations. 

I wish to contribute to this issue. Please assign me the same under GSSOC'21.

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)

**Comment by Amit366** [comment]
@sairish2001 can I work??

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST

**Comment by Amit366** [comment]
@sairish2001 I have done the project. But one problem i.e, the javascript is not returning the final value. Can u help?

**Comment by Amit366** [comment]
![Screenshot (183)](https://user-images.githubusercontent.com/60662775/113923531-416fbe00-9806-11eb-8300-b92272206ccb.png)
![Screenshot (182)](https://user-images.githubusercontent.com/60662775/113923551-47659f00-9806-11eb-8010-2284cd8eebc9.png)

**Comment by sairish2001** [comment]
What's the output it showing?

**Comment by Amit366** [comment]
@sairish2001 it's not showing anything

**Comment by sairish2001** [comment]
be make sure the id's are unique, in the whole page.

Check whether any other element is having id='sp' or 'cp'

**Comment by sairish2001** [comment]
try to use div tag instead of p

may be the black color of text in p tag is not showing

**Comment by Amit366** [comment]
Ok

**Comment by Amit366** [comment]
@sairish2001 I think the result is not coming to the HTML part from js.

**Comment by Amit366** [comment]
I tried changing the p tag but no result

**Comment by Amit366** [comment]
@sairish2001 should I send the PR?? So that you can check.

**Comment by sairish2001** [comment]
Okay
