### ISSUE TITLE
To Add a calculator which can add 2 numbers , where both the numbers can be from any number system(i.e, binary/decimal/octal/hexadecimal)

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#668]
## **Is your feature request related to a problem? Please describe.**

No problem
I would just like To Add a calculator which can add 2 numbers , where both the numbers can be from any number system(i.e, binary/decimal/octal/hexadecimal)

 for example- the calculator can perform actions like -
3+2=5
11+10=101, etc

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
