### ISSUE TITLE
To add a calculator which can perform Binary subtraction using 1's and 2's compliment and also display the formula for the same right next to it !

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#669]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
is this issue is open
can i work on it

**Comment by AB-san** [comment]
> is this issue is open
> can i work on it

yes i hv asked @sairish2001  and i m still working on it , as promised it will be over by 14th of this week
