### ISSUE TITLE
To add a calculator which can perform subtraction of 2 octal numbers using 7's and 8's compliment and also display the formula for the same right next to it !

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#670]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
is this issue is open
can i work on it

**Comment by sairish2001** [comment]
@AB-san any update?

**Comment by AB-san** [comment]
> @AB-san any update?

yes @sairish2001  work in progress, as promised , it will be over by 14th of this month
