### ISSUE TITLE
Bug in conversion calculator

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#679]
Unit Conversion Calculator is not visible when units are clicked. I would like to resolve this
Please assign this issue to me.

**Comment by sairish2001** [comment]
Not only unit conversation, all the modals are not visible

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)

**Comment by RaveenaBhasin** [comment]
@sairish2001 I have created the PR. Please review it
