### ISSUE TITLE
Adding power(exponent) calculator under general maths section

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/makesmatheasy#684]
## **Is your feature request related to a problem? Please describe.**

- I want to add a calculator that will calculate power taking two numbers as input .
## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by zhcet19** [comment]
@sairish2001  please assign me this issue

**Comment by sairish2001** [comment]
Actually, I want this to add in the calculator.

**Comment by sairish2001** [comment]
For that you have to add few blocks in the calculator

**Comment by zhcet19** [comment]
OK i will add few blocks in calculator for exponentent functionality. You can assign it to me

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 (11:59 PM IST)
