### ISSUE TITLE
Bug in Bayes Theorem calculator.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#689]
## **Describe the bug**
Wrong implementation of Bayes Theorem.
P(A|B) and P(B|A) don't always add up to 1 but in the current implementation it's always adding up to 1.
Also, to calculate P(A|B) and P(B|A) we need P(A and B) which cannot be determined, this need to be entered by the user.
![Screenshot (208)](https://user-images.githubusercontent.com/66053534/112999855-ecd89d00-918c-11eb-9412-d52b4fa06a2f.png)
![Screenshot (209)](https://user-images.githubusercontent.com/66053534/112999869-efd38d80-918c-11eb-92c7-9cfe75536292.png)

@sairish2001 Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
