### ISSUE TITLE
While giving input in bcd any number which is not 0 or 1 it is show in result 0 while there should be a valid error message given

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#691]
## **Describe the bug**

While giving input in bcd any number which is not 0 or 1 it is show in result 0 while there should be a valid error message given

## **Possible solution**

- adding if else for that

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/67696867/113007701-0fba7f80-9194-11eb-8c4c-1bf9b023e391.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 (11:59 PM IST)
