### ISSUE TITLE
Primality Test over negative values

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#692]
## **Describe the bug**

- Negative values should not be not considered in primality test

## **Possible solution**

- Putting the appropriate check to determine the correct measures

## **Screenshots**

![Attention - Primality on negative values](https://user-images.githubusercontent.com/55992140/113008659-d9c9cb00-9194-11eb-87e6-7ff0305ac59e.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
