### ISSUE TITLE
Enhancing functionality of Profit Loss Calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#693]
## **Is your feature request related to a problem? Please describe.**

- In selling price and cost price calculation discount will also play a major role. Adding discount as an optional functionality.

## **Describe the solution you'd like**

- Adding the discount as an optional functionality to the existing function 

Current look and state of Profit-Loss Calculator
![FUNCTIONALITY - Add discount as an option field to profit loss calculator](https://user-images.githubusercontent.com/55992140/113009749-de42b380-9195-11eb-919e-dec6892092ad.PNG)

**Comment by SarthakKeshari** [comment]
Kindly aasign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
