### ISSUE TITLE
Trapezium image label missing

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#694]
## **Describe the bug**

- Trapezium has no label for **c** and **d** which is needed for calculation, I would like to add the same. Also I would like to change the present image as it is barely visible in the dark mode. Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- 
![Capture](https://user-images.githubusercontent.com/70858557/113014084-eef52880-9199-11eb-822d-e5efc8025fc4.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
