### ISSUE TITLE
Congruency and Similarilty Section doubt

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#696]
Sir @sairish2001 ,
    I saw BYJU'S images being used in Congruence and Similarity section. May I create these images and replace the one taken from BYJU'S?

![Attention - Congruency property BYJU'S images](https://user-images.githubusercontent.com/55992140/113016068-bfdfb680-919b-11eb-8da8-a49db4ea01c8.PNG)

Thankyou

**Comment by sairish2001** [comment]
Go ahead
Deadline 4 April,2021 (11:59 PM IST)
