### ISSUE TITLE
To add a convertor to convert decimal to 2421 code

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#707]
## **Describe the solution you'd like**

- To add a convertor to convert decimal to 2421 code

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
This code is not widely used

**Comment by abhijeet141** [comment]
Yes sir i agree that it is not widely used but i thought that we should have all convertors in website

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 (11:59 PM IST)
