### ISSUE TITLE
Bug in decimal/binary converter.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#712]
## **Describe the bug**
Decimal binary converter is showing wrong answers for the all binary to decimal conversions.
Please assign this to me.

![Screenshot (216)](https://user-images.githubusercontent.com/66053534/113092050-e12bbb80-920a-11eb-8aef-fa7039066e42.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 (11:59 PM IST)
