### ISSUE TITLE
Invalid expression is not working

### ISSUE THREAD

**Issue by janvi01** [sairish2001/makesmatheasy#713]
## **Describe the bug**

when the expression is invalid or can't be calculated, nothing shows.

<img width="1092" alt="Screenshot 2021-03-31 at 10 45 00 AM" src="https://user-images.githubusercontent.com/34344234/113094351-1e924800-920f-11eb-8cc1-0c92b29ecaa5.png">

## **Possible solution**

I would like to fix or add alert saying invalid expression.

**Comment by sairish2001** [comment]
If you can then try changing the color of text to red; when the expression is invalid rather than showing any warnings

**Comment by janvi01** [comment]
Yes sure

**Comment by janvi01** [comment]
i would change the color of text to red, and
add an i button (information circle) displaying invalid expression when clicked on button on the left side of text area.

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 (11:59 PM IST)

**Comment by janvi01** [comment]
I have changed the color to red when expression is invalid.

Ref:
<img width="1092" alt="Screenshot 2021-04-01 at 3 00 05 PM" src="https://user-images.githubusercontent.com/34344234/113274325-347d3700-92fb-11eb-8c60-de04938336d1.png">

But still if user clicks on equal to sign to get answer, an i button displays like this

<img width="1092" alt="Screenshot 2021-04-01 at 3 00 30 PM" src="https://user-images.githubusercontent.com/34344234/113274489-61c9e500-92fb-11eb-9255-2b636bdf20b8.png">

On clicking i button 
<img width="1092" alt="Screenshot 2021-04-01 at 3 00 59 PM" src="https://user-images.githubusercontent.com/34344234/113274546-71e1c480-92fb-11eb-8057-7abd8a50cd46.png">

if after entering any input, the expression gets valid, the i button disappears and color also changes back to initial color.

**Comment by janvi01** [comment]
Please review if any changes needed,
or I should make a pr?

**Comment by janvi01** [comment]
@sairish2001

**Comment by sairish2001** [comment]
Will after expression gets vaild, the i button  hides or remains there?

**Comment by janvi01** [comment]
It disappears and color also changes back to initial color.

**Comment by sairish2001** [comment]
create PR
