### ISSUE TITLE
Bug in median calculator

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#717]
## **Describe the bug**

- The function is unable to calculate the median due to some bug. I would like work on this issue. Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- 
![Capture](https://user-images.githubusercontent.com/70858557/113106304-3cb47400-9220-11eb-88cc-69e5c7d1ad05.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
