### ISSUE TITLE
Identities and Properties of Complex Numbers 

### ISSUE THREAD

**Issue by SandeepKrSuman** [sairish2001/makesmatheasy#718]
## **Is your feature request related to a problem? Please describe.**

- I want to add the identities and properties of complex numbers. 

- If seems relevant, assign this issue to me under gssoc21 

## Screenshots

- Before: 
![Screenshot (265)](https://user-images.githubusercontent.com/54541515/113109766-ed704280-9223-11eb-99ee-a1eb06c3d09c.png)

- After: 
![Screenshot (266)](https://user-images.githubusercontent.com/54541515/113109823-f9f49b00-9223-11eb-9022-0277ad75eecb.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
