### ISSUE TITLE
To enhance the UI of BCD/Decimal convertor and BCD code addition

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#719]
![image](https://user-images.githubusercontent.com/67696867/113106572-8b620e00-9220-11eb-9418-d7a2d3f8b2a3.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST

**Comment by satyampgt4** [comment]
is this issue still open?if open can i work on this issue?

**Comment by abhijeet141** [comment]
Hi @satyampgt4 i am still working on this issue there is some delay because my exams are going on
