### ISSUE TITLE
adding some Boolean algebra rules

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#721]
There are **four** more laws under Boolean algebra which is missing here. I would like to add the same. Kindly assign this to me under GSSoC.

![Capture](https://user-images.githubusercontent.com/70858557/113108699-e5fc6980-9222-11eb-896a-980f24aaf3c1.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
