### ISSUE TITLE
adding steps for calculation of Interest(simple and compound)

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#722]
## **Is your feature request related to a problem? Please describe.**

- Interest(simple and compound) under General math simply calculates the value of Simple and Compound Interest, I would show the steps for the calculation, for both of them. Kindly assign this to me under GSSoC.

![Capture](https://user-images.githubusercontent.com/70858557/113110663-f31a5800-9224-11eb-8532-5d425a7e9f9e.PNG)

## **Describe the solution you'd like**

-

**Comment by sairish2001** [comment]
Kindly use LaTeX text where it requires in steps

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST

**Comment by madihamallick** [comment]
> Kindly use LaTeX text where it requires in steps

Okay
