### ISSUE TITLE
To enhance the UI of Boolean Algebra section

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#723]
## **Describe the solution you'd like**

-To write all the properties in latex
![image](https://user-images.githubusercontent.com/67696867/113111924-450fad80-9226-11eb-874b-3e8f022ab4f6.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Use LaTeX for only formulas, not for headings

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
