### ISSUE TITLE
Bug in Bitwise operator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#724]
## **Describe the bug**

- In bitwise operator under hexadecimal number system i am not able to take input in alphabets
## **Screenshots**

- 
![image](https://user-images.githubusercontent.com/67696867/113131554-fe787e00-923a-11eb-9ab8-eecf80e27df7.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it from 3rd April. I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST

**Comment by anjali7786** [comment]
@sairish2001 kindly assign this issue to me under GSSOC'21

**Comment by satyampgt4** [comment]
is this issue still open? can i work on this issue?

as deadline is over

**Comment by shonali2600** [comment]
@sairish2001 can I work on this issue?
