### ISSUE TITLE
To add operator of NOT in bitwise operator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#729]
## **Describe the solution you'd like**

- I would like to add NOT operator under the section bitwise operator

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it from 3rd April. I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST

**Comment by satyampgt4** [comment]
is this issue still open? can i work on this issue?

as deadline is over

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 April,2021 11:59 PM IST
