### ISSUE TITLE
Letter Character acceptance by ascending/descending 

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#730]
## **Describe the bug**

- Invalid acceptance of letters along with numbers

## **Possible solution**

- Using appropriate checks to prompt the user and make the calculator work on correct input

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Attention - mathematical operation working over letters asc and desc](https://user-images.githubusercontent.com/55992140/113142524-9af54d00-9248-11eb-8fbf-1ab129582152.PNG)

**Comment by SarthakKeshari** [comment]
Please assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
