### ISSUE TITLE
Factorial Calculator working

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#731]
## **Describe the bug**

- Factorial calculator is working over negative values and this is not possible as per the gamma function rules.
- Factorial can be found using gamma function and gamma function is not defined for negative integer.
so, Factorial is not defined for negative integer 

## **Possible solution**

- Restricting negative values input from user and providing appropriate prompt

## **Screenshots**

![Attention - Factorial working over negative values](https://user-images.githubusercontent.com/55992140/113144727-312a7280-924b-11eb-9d4d-19b424432b03.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
