### ISSUE TITLE
Bug in Geometric Mean calculator

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#732]
## **Describe the bug**

-the GM of a and c when a>0 and c>0 is sqrt(ac) but when a<0 and c<0 then GM = -sqrt(ac) but in the calculator when i am taking both as negative number then also it is calculating with the same formula sqrt(a,c)

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/113144892-6afb7900-924b-11eb-8d50-f2f12cd08b34.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it from 3rd April. I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
