### ISSUE TITLE
Permutation Combination working over floating values

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#733]
## **Describe the bug**

- Permutation Combination calculator working over floating values needs to be restricted since combination/permutation of objects or entities can't be fractional.
- Example - Number of items can't be 100.11111

## **Possible solution**

- Putting appropriate checks and prompting the user in case of incorrect input

## **Screenshots**

![image](https://user-images.githubusercontent.com/55992140/113145111-a9913380-924b-11eb-9dd0-4b3bd7355c7b.png)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
