### ISSUE TITLE
Mean, Median and Mode improper working

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#734]
## **Describe the bug**

- Mean, Median and Mode not working over negative values needs to be rectified for correct results.

## **Possible solution**

- Improving the existing function to gain the required functionality.

## **Screenshots**

![Attention - Mean, Median and Mode not working over negative values](https://user-images.githubusercontent.com/55992140/113146847-caf31f00-924d-11eb-958c-a7361b811222.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
