### ISSUE TITLE
adding steps under Mean Calculator

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#749]
## **Is your feature request related to a problem? Please describe.**

- Under the Arithmetic, Geometric and Harmonic mean calculation under Mean Calculation I would like to add some more steps using LaTeX text for **better understanding**. Kindly assign this to me under GSSoC. 

## **Describe the solution you'd like**

![Capture](https://user-images.githubusercontent.com/70858557/113310977-6f489480-9326-11eb-9418-1f774e994d2f.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 7 April,2021 11:59 PM IST
