### ISSUE TITLE
Rank Calculator

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#753]
## Proposal

Rank of a Word in Dictionary

(A clear and concise description of what the proposal is.)

**Comment by sairish2001** [comment]
can you please elaborate

**Comment by satyampgt4** [comment]
**these are famous and standard problem in pnc
for example** 


> If all the letters of the word 'PRIME' are arranged in all possible ways and written out in alphabetical(dictionary) order, then find the rank of the given word.

**Comment by sairish2001** [comment]
Go ahead
Deadline 7 April,2021 11:59 PM IST
