### ISSUE TITLE
Data Unit Converter

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#760]
## **Describe the bug**

- Data Unit converter is accepting negative data values and this is wrong since data cannot be negative

## **Possible solution**

- Putting appropriate check to crub this issue and also prompting the user when entering negative values.

## **Screenshots**

![Attention - Data unit converter working over negative values](https://user-images.githubusercontent.com/55992140/113355979-37aa0e80-935f-11eb-8b3c-073f0162195e.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 6 April,2021 (11:59 PM IST)
