### ISSUE TITLE
Time Unit Converter working

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#761]
## **Describe the bug**

- Time Unit Converter working over negative values. Since time is never negative so this error needs to be handled

## **Possible solution**

- Approriate checks over entered values needs to added in order to resolve this issue;

## **Screenshots**

![Attention - Time unit converter working over negative values](https://user-images.githubusercontent.com/55992140/113356417-d6cf0600-935f-11eb-80a3-91427c428919.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 7 April,2021 (11:59 PM IST)
