### ISSUE TITLE
Mass Unit Converter working

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#762]
## **Describe the bug**

- Mass can never be negative but the current calculator works over negative values too.

## **Possible solution**

- Checking for negative input and prompting the user obout the incorrect input given

## **Screenshots**
![Attention - Mass unit converter working over negative values](https://user-images.githubusercontent.com/55992140/113357015-d5520d80-9360-11eb-9507-46af0c14f8dd.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 7 April,2021 11:59 PM IST
