### ISSUE TITLE
bug in logarithmic calculator

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#764]
WHen we type base = 0 the msg displayed is pls enter a positive number. But better msg can be base cannot be 0 as considering 0 as not a positive no. is  not apt.
![image](https://user-images.githubusercontent.com/60147732/113369803-d5153a80-937f-11eb-8c39-123efea3d85a.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
@sairish2001 Attached a PR Have a look!
