### ISSUE TITLE
bug in p/b/h trigo

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#765]
IF entered a negative value in any of fields the abrupt answers are coming up. The lengths of sides cannot be negative
![image](https://user-images.githubusercontent.com/60147732/113370021-6edce780-9380-11eb-9bf2-ec54d612b306.png)
![image](https://user-images.githubusercontent.com/60147732/113370040-7ac8a980-9380-11eb-941a-9f39f0c43c56.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 April,2021 (11:59 PM IST)
