### ISSUE TITLE
Output formatting error in equation reduction

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#768]
## **Describe the bug**

- The output shows mis formatted answer on reducing equation.

## **Possible solution**

- Making correction to the printing statement(s)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Attention - Output formatting error on reduction of equation](https://user-images.githubusercontent.com/55992140/113396408-2130a100-93b9-11eb-8110-972da274f569.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by SarthakKeshari** [comment]
Sir @sairish2001,
       I found a bug that I can rectify. I am attaching the rectified image. If you approve of this kindly assign this issue to me.
 
![RECTIFIED - Output formatting error on reduction of equation](https://user-images.githubusercontent.com/55992140/113410734-c0fa2900-93d1-11eb-88de-9415b5797926.PNG)

**Comment by sairish2001** [comment]
Great!
Go ahead
Deadline 7 April,2021 11:59 PM IST
