### ISSUE TITLE
adding steps for calculation of EMI

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#775]
EMI calculator under General math simply calculates the value, I would show the steps for the calculation. Kindly assign this to me under GSSoC.
![Capture](https://user-images.githubusercontent.com/70858557/113398984-14ae4780-93bd-11eb-88b8-9755aeece360.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 7 April,2021 11:59 PM IST
