### ISSUE TITLE
Geometric Progression over letter characters

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#776]
## **Describe the bug**

- Working of Geometric Progression over letter characters needs to be rectified since only numeral values are acceptable

## **Possible solution**

- Restricting acceptance of letter characters.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Attention - Working of GP over letter characters](https://user-images.githubusercontent.com/55992140/113400562-9e5f1480-93bf-11eb-933b-4e9cc2a1fa61.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 7 April,2021 11:59 PM IST
