### ISSUE TITLE
Appropriate prompt in AP

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#777]
## **Describe the bug**

- Arithmetic Progression Calculator does not give any prompt to user over blank input rathar show NaN which is not a good way to make the calculator user interactive

## **Possible solution**

- Making appropriate alteration in the existing function and adding a prompt for user over blank input

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Attention - Appropriate prompt over blank input by user in AP](https://user-images.githubusercontent.com/55992140/113400998-555b9000-93c0-11eb-88f1-8207a338fdbd.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 8 April,2021 11:59 PM IST
