### ISSUE TITLE
Appropriate prompt in GP

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#778]
## **Describe the bug**

- Geometric Progression Calculator does not give any prompt to user over blank input rathar shows formula for calculation.

## **Possible solution**

- Making alteration in the existing function to handle the error

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Attention - Appropriate prompt over blank input by user in GP](https://user-images.githubusercontent.com/55992140/113401122-85a32e80-93c0-11eb-9e19-362b54a7ea55.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 7 April,2021 11:59 PM IST
