### ISSUE TITLE
Show steps for calculation of 15's and 16's complement

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#794]
## **Is your feature request related to a problem? Please describe.**

- Showing steps for calculation of 15's and 16's complement calculation

## **Describe the solution you'd like**

- Adding required functionality to code base

![Attention - Show Steps for 15s and 16s complement calculation](https://user-images.githubusercontent.com/55992140/113446563-a47fe000-9415-11eb-8f1a-495ffe4ef8fd.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 9 April,2021 11:59 PM IST
