### ISSUE TITLE
Adding calculator for set operations

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#795]
## **Is your feature request related to a problem? Please describe.**

- Adding calculator for set operations like union, intersection, etc.

## **Describe the solution you'd like**

- Making appropriate amendments in index.html and logicjavascript.js in order to add required functionality to the set calculator

Current state
![ADD - Calculator to set operation](https://user-images.githubusercontent.com/55992140/113447371-5b309000-9417-11eb-85c4-fb14e87f4268.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 9 April,2021 11:59 PM IST

**Comment by satyampgt4** [comment]
is this issue still open? can i work on this issue?

as deadline is over

**Comment by SarthakKeshari** [comment]
@sairish2001 , 
Sir kindly assign all my issues to other contributors, since due to some odds I wasn't able to accomplish my duty and won't be able to accomplish my duty for next 10 days.

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 April,2021 11:59 PM IST
