### ISSUE TITLE
Inappropriate promt in LCM/HCF/Factors

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#796]
## **Describe the bug**

- In case of entering negative numbers "Enter numbers only" prompt is displayed instead of "Only positive values allowed"

## **Possible solution**

- Adding appropriate check over negative numbers to avoid faulty prompt

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Attention - Inappropriate prompt given for negative values entered in LCM-HCF-Factors](https://user-images.githubusercontent.com/55992140/113448530-a21f8500-9419-11eb-8f5a-0dc11e7e5e65.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 9 April,2021 11:59 PM IST

**Comment by khareyash05** [comment]
@sairish2001is this issue still open?

**Comment by satyampgt4** [comment]
is this issue still open? can i work on this issue?

as deadline is over
