### ISSUE TITLE
show steps and formula for profit and loss part

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#803]
## **Is your feature request related to a problem? Please describe.**

The calculation of profit does not show any **formula** for profit/loss calculation or profit/loss percentage calculation, I would like to add the same. Also I would like to add some steps. Kindly assign this issue to me under GSSoC.

## **Describe the solution you'd like**

-
![Capture](https://user-images.githubusercontent.com/70858557/113471435-d75bbf80-9479-11eb-896b-e7946240ae91.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 9 April,2021 11:59 PM IST
