### ISSUE TITLE
adding decimal to gray code converter and vice versa

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#804]
Under Binary Calculations, the **Grey Code Converter** calculates grey code to binary and vice-versa, I would also like to add decimal to grey and vice-versa here itself. Kindly assign this to me under GSSoC.

![Capture](https://user-images.githubusercontent.com/70858557/113471650-5ef5fe00-947b-11eb-88bd-fc3db986c08e.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 April,2021 11:59 PM IST
