### ISSUE TITLE
Improve SI and CI calculator

### ISSUE THREAD

**Issue by SarthakKeshari** [sairish2001/makesmatheasy#805]
## **Is your feature request related to a problem? Please describe.**

- Adding the amount formula and amount calculation answer to the current presentation of SI and CI calculator

## **Describe the solution you'd like**

- Adding the required lines of code to the appropriate available function

![Attention - Add final amount to the answer of Simple and compound interest](https://user-images.githubusercontent.com/55992140/113471762-40dccd80-947c-11eb-932b-0d561d4937f1.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
You mean, you will show steps?

**Comment by SarthakKeshari** [comment]
Sir @sairish2001 ,
I will add one more step for showing Final Amount after SI and CI calculation

**Comment by sairish2001** [comment]
Go ahead
Deadline 9 April,2021 11:59 PM IST
