### ISSUE TITLE
Problem in UI of boolean algebra

### ISSUE THREAD

**Issue by RoliGautam** [sairish2001/makesmatheasy#811]
## **Is your feature request related to a problem? Please describe.**
When we open a topic of the BOOLEAN ALGEBRA, the summary of all topics are align to left, which is not looking good and quite disapointed.

## **Describe the solution you'd like**
I can solve this problem and make it in middle , which will looks good.

I am attaching a screenshot of that issue.. 
Review it, It is not looking good , but if we make it in center , it will more confortable and attractive.

<img width="952" alt="Screenshot 2021-04-03 191920" src="https://user-images.githubusercontent.com/72242893/113480559-76041280-94b2-11eb-9597-ca5a1feeb0f9.png">

Even in all the other section, the summary of topics are in center , which is looking good.
Review here that look...
<img width="960" alt="Screenshot 2021-04-03 193058" src="https://user-images.githubusercontent.com/72242893/113480687-3f7ac780-94b3-11eb-9339-96b113c345bb.png">

I can solve this problem . Can you please assign me for this. 
Thank you!!

**Comment by RoliGautam** [comment]
@sairish2001 please assign me!

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 April,2021 11:59 PM IST

**Comment by RoliGautam** [comment]
@sairish2001 Thank you and I will do it within deadline!

**Comment by RoliGautam** [comment]
Hello sir ..
@sairish2001 Can you please have a look of the solution of this issue? Is it okay ?

<img width="854" alt="Screenshot 2021-04-06 222100" src="https://user-images.githubusercontent.com/72242893/113748852-9805cb00-9726-11eb-8cc2-3b76a5124b20.png">

**Comment by sairish2001** [comment]
refer this [Katex Support Table](https://katex.org/docs/support_table.html) to write Math Text

**Comment by RoliGautam** [comment]
ok sir, but.. is this look not good for this?

**Comment by sairish2001** [comment]
are you familiar with Bootstrap?

**Comment by RoliGautam** [comment]
yes, I know and also use it when I make my projects

**Comment by sairish2001** [comment]
So I would suggest you to use

grid system

```
<div class='row'>
    <div class='col-md-4'>
    
     </div>
</div>
```

So that it would show 3 identities in a single row, and 1 identity in smaller screens

**Comment by RoliGautam** [comment]
ok , sure I will work using it

**Comment by RoliGautam** [comment]
@sairish2001 There is also a bug , when we change website in white mode , the font of the properties not changed in black . Only headings(Annulment, Identity Law etc.)  color change into black. Can I solve this also?

**Comment by sairish2001** [comment]
![img](https://user-images.githubusercontent.com/60106112/114065405-42f9be80-98b8-11eb-81e6-aa3bd8407ce1.jpg)
image is just for illustration purpose


use Bootstrap to arrange like this

**Comment by RoliGautam** [comment]
So.. Is it ok or need something ?

**Comment by sairish2001** [comment]
> refer this [Katex Support Table](https://katex.org/docs/support_table.html) to write Math Text

Use LaTex text for formulas

**Comment by RoliGautam** [comment]
ok

**Comment by RoliGautam** [comment]
Hello.. 
Check it please @sairish2001 
How is it now??

<img width="926" alt="Screenshot 2021-04-09 135844" src="https://user-images.githubusercontent.com/72242893/114152331-c7d9ec00-993b-11eb-8ab5-2cdafaa60cde.png">

**Comment by sairish2001** [comment]
Go ahead with PR

**Comment by RoliGautam** [comment]
Sure..Thank you
