### ISSUE TITLE
Add new operation on sets

### ISSUE THREAD

**Issue by RoliGautam** [sairish2001/makesmatheasy#812]
## **Is your feature request related to a problem? Please describe.**

I want to add a new operation in sets. I have read this section in this website and there is only four operation as: Union, Intersection, Difference and complement. But there is also an another operation exist in sets which is "symmetric difference of sets", So I want to add this new one operation in this section. 
Can you please assign me for this ? I can do it perfectly.

Thank you!

**Comment by RoliGautam** [comment]
@sairish2001 Can you please assign me?

**Comment by sairish2001** [comment]
Are your talking about Calculator?

**Comment by RoliGautam** [comment]
No sir
