### ISSUE TITLE
Add some logics and topics in Sets, Relation and Functions

### ISSUE THREAD

**Issue by RoliGautam** [sairish2001/makesmatheasy#813]
## **Is your feature request related to a problem? Please describe.**
I want to add the explanation of types of function, which is not available in website.

Here , in your website there is only name of that function and one line description which is not enough to understand, so I want to add this logic and explanation in detail.
<img width="954" alt="Screenshot 2021-04-03 200325" src="https://user-images.githubusercontent.com/72242893/113481996-39d4b000-94ba-11eb-9feb-37db4768d8de.png">

Please assign me for this problem .
Thank you!

**Comment by RoliGautam** [comment]
@sairish2001 please assign me!

**Comment by sairish2001** [comment]
Sorry, but no issues related to Documentation will be accepted.

You can move onto the Calculator, if you want to.
