### ISSUE TITLE
Suggestion  for calculator for calculating the volumes and surface areas of the 3d shapes

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/MakesMathEasy#83]
A calculator for 3d shapes. It Will calculate volumes and surface areas of the shapes. Similar to 
the calculator for shape.
I would like to do this. Please assign this to me.
#GsSOC'21

**Comment by sairish2001** [comment]
Great!
Feel free to ask your doubt,if any
Deadline 16 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
Any update? @kanishka8276

**Comment by kanishka8276** [comment]
Yes I am working on it. I have created the template for the calculator. Now I am working on the functions.

**Comment by kanishka8276** [comment]
@sairish2001 Can you please extend the deadline.
There are so many functions to be worked upon, So it's taking time.
Sorry for the delay!

**Comment by sairish2001** [comment]
Deadline extended 18 March,2021 (11:59 PM IST)

**Comment by kanishka8276** [comment]
Thank you for considering!

**Comment by kanishka8276** [comment]
@sairish2001  I have completed the template part of the 3-D shape calculator, and I am struggling in creating the function from the past 2 days but the output is not as expected. When I use .innerHTML to display the output, it's unable to show it in Katex format and instead shows it with all the slashes and square brackets. I have referred to the functions which were made for shapes but couldn't debug it.
In the worst case, Is it possible that I just create a PR for the template part and get it merged as I have devoted a lot of time for it and then create another issue for the function of 3-D shape and then you can assign it to some other participant.
Otherwise I am working on it and trying my best to do it  but it's first time I am working with katex.

**Comment by sairish2001** [comment]
Oh! it's quite easy to render Text using LaTex. Yeah if you are getting slashes in the output, it's okay. Just call at the end of processing, basically at the end of,inside your function
 `renderMathInElement(document.getElementById(____))`

**Comment by kanishka8276** [comment]
> Oh! it's quite easy to render Text. Yeah if you are getting slashes in the output, it's okay. Just call at the end of processing, basically at the end of,inside your function
> `renderMathInElement(document.getElementById(____))`

I have already done that. Still I am getting those slashes and brackets
