### ISSUE TITLE
create squareroot calculator

### ISSUE THREAD

**Issue by Muskan-creator** [sairish2001/makesmatheasy#834]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
Please assign me this issue @sairish2001

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by sairish2001** [comment]
will you show steps for it?

**Comment by Muskan-creator** [comment]
I can create a square root calculator under general math section.

**Comment by sairish2001** [comment]
Square root is already there in Calculator

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST

**Comment by satyampgt4** [comment]
is this issue still open? can i work on this issue?

as deadline is over

**Comment by Amit366** [comment]
@sairish2001 can I work??

**Comment by Samridhi-98** [comment]
@sairish2001  I would like to work on it please assign it to me.

**Comment by Ankita297** [comment]
@sairish2001 @shrey27tri01 can i work on this ?

**Comment by sairish2001** [comment]
@Ankita297 will you add steps to it?
