### ISSUE TITLE
bug in LCM|HCF|factor calculator

### ISSUE THREAD

**Issue by Muskan-creator** [sairish2001/makesmatheasy#835]
## **Describe the bug**
![image](https://user-images.githubusercontent.com/59757988/113537768-2f6c0080-95f7-11eb-918e-f6b54cb8d102.png)

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
Can i work on this issue @sairish2001

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by sairish2001** [comment]
@Muskan-creator Can you please elaborate this issue

**Comment by Muskan-creator** [comment]
![image](https://user-images.githubusercontent.com/59757988/113657918-a0292080-96bc-11eb-8eca-00e62bf1d54c.png)
LCM is not working

**Comment by sairish2001** [comment]
LCM is working, but how will you find a LCM of 1 number?

**Comment by Muskan-creator** [comment]
In this it is written should be more than 1 
so I think that greater than 1.It should be written like more than 1 value is required
sorry for misunderstanding

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 April,2021 11:59 PM IST
