### ISSUE TITLE
Adding e (expontenial) in calculator

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/makesmatheasy#838]
## **Is your feature request related to a problem? Please describe.**

- Currently there is no button to enter value of e in calculator.I want to add that

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by zhcet19** [comment]
@sairish2001 please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 April,2021 11:59 PM IST

add two exponentials
- **e** 
- **exp(**
