### ISSUE TITLE
Any base to any base converter

### ISSUE THREAD

**Issue by geniusbharti** [sairish2001/makesmatheasy#843]
## **Is your feature request related to a problem? Please describe.**

- Missing any base to any base converter.

## **Describe the solution you'd like**

- A convertor inside the Basic converter feature that includes any base to any base conversion.

**Comment by geniusbharti** [comment]
I would like to work on this issue.

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST

**Comment by geniusbharti** [comment]
@sairish2001 Okay.

> Go ahead
> Deadline 14 April,2021 11:59 PM IST
