### ISSUE TITLE
Bug in factor calculator in general maths

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#846]
## **Describe the bug**

-When the user inputs a number, sometimes the correct result is not displayed.
 for example:- for 99 ,its showing only 11. Correct result should be 3,3,11
## **Possible solution**

- I will do some correction in code, so that correct answer will be displayed.
![prime factors](https://user-images.githubusercontent.com/75009990/113682854-34a57a00-96e1-11eb-8e38-b8a0b4675bef.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST

**Comment by ShrutiOmer** [comment]
Thankyou for assigning
