### ISSUE TITLE
Bug in addition operation of fraction in general maths

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#848]
## **Describe the bug**

- In working procedure of addition of two fractions , the variable 'e' is not replaced by its value.

## **Screenshots**

![addition](https://user-images.githubusercontent.com/75009990/113697399-c5378680-96f0-11eb-993d-5ae08e6db169.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST
