### ISSUE TITLE
Modify Trapezium working.

### ISSUE THREAD

**Issue by janvi01** [sairish2001/makesmatheasy#849]
## **Is your feature request related to a problem? Please describe.**

- In trapezium under calculator for shapes, it asks user to input height as well as all sides .

## **Describe the solution you'd like**

-if user inputs all sides , we can find height using heron's formula and then equate accordingly.

I would like to add working of finding height and then accordingly using it to find area, perimeter.

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST

**Comment by janvi01** [comment]
I have added.
Please have a look

<img width="715" alt="Screenshot 2021-04-07 at 11 50 27 AM" src="https://user-images.githubusercontent.com/34344234/113820209-020a8880-9798-11eb-9644-fd95bbf94b0c.png">
<img width="715" alt="Screenshot 2021-04-07 at 11 51 02 AM" src="https://user-images.githubusercontent.com/34344234/113820220-059e0f80-9798-11eb-8173-58ad8856336e.png">
<img width="715" alt="Screenshot 2021-04-07 at 11 52 09 AM" src="https://user-images.githubusercontent.com/34344234/113820224-06cf3c80-9798-11eb-8445-b852cb4500d7.png">

i have added reference image also.

**Comment by janvi01** [comment]
Is it okay? @sairish2001

**Comment by sairish2001** [comment]
put image at top of the modal, as it is in other modals

**Comment by janvi01** [comment]
Image is already there at the top,

<img width="715" alt="Screenshot 2021-04-07 at 1 06 38 PM" src="https://user-images.githubusercontent.com/34344234/113828556-28cdbc80-97a2-11eb-99f2-cf80bad1089c.png">

should i replace it or add (then there will be 2 image)?

**Comment by janvi01** [comment]
@sairish2001

**Comment by sairish2001** [comment]
Remove your image and go ahead with PR
