### ISSUE TITLE
Adding T-Ratios for many angles in sequence

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#850]
## **Is your feature request related to a problem? Please describe.**

- The problem is that the values of trigonometric ratios are not well organized and also some values of some functions are missing too as you can see below:

![values](https://user-images.githubusercontent.com/73488906/113705170-be157600-96fa-11eb-9468-f95daaff0a39.png)

- One cannot find the values easily if the arrangement is not done properly and what if one might wants to see the value sin(22.5)? 
  It is not there right now and above, in the heading it is written "Values of some T-Ratios for Angles 18, 36, 15, 22.5, 67.5"!
- Degrees are not in one particular order, it's like 18,36,15... 
  So how one can check the list if it's not ordered in any manner (i.e. ascending or descending)?

- Kindly assign this issue to me under GSSoC.

## **Describe the solution you'd like**

- I would like to make the process of searching easily. 
- Degree of any function should be arranged in one particular order.

You can see below:

![trigo](https://user-images.githubusercontent.com/73488906/113704957-7262cc80-96fa-11eb-8695-0334fdf8a944.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 (11:59 PM IST)
