### ISSUE TITLE
UI of favourite formulas

### ISSUE THREAD

**Issue by satcasm** [sairish2001/makesmatheasy#855]
After clicking on the ```favorite``` button, the favorite formulas begin displayed are not rendering properly. 
The right-side border of the ```li``` is hiding behind the scroll bar.
Would like to fix it under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/113754335-bff82d00-972c-11eb-8bbc-8f7fd789dffc.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST
