### ISSUE TITLE
Number facts which are shorter in length overflows out of its area.

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#856]
![math bug](https://user-images.githubusercontent.com/57946528/113819119-7e03d100-9796-11eb-85d6-c4f89bc89216.png)

Here it is easily visible that some content is out of its area, and it also happens with most of the content. I would like to solve this issue as a GSSOC Participant.

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 April,2021 11:59 PM IST
