### ISSUE TITLE
[GSSOC'21] Hover effect to calculator

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#857]
## **Is your feature request related to a problem? Please describe.**

While clicking on any number or operator in the calculator, if it hovers it will give a feel of clicking it and would look more interactive.

## **Describe the solution you'd like**

I would like to add the hover effect to its keys.

**Comment by shonali2600** [comment]
@sairish2001 sir, please try to assign me this issue, if this issue is valid.

**Comment by shonali2600** [comment]
Please look into this issue, I think this feature should be added to the calculator as will have a good user experience.

**Comment by sairish2001** [comment]
Since the hover effect does not works well in mobile devices, so that's the reason
