### ISSUE TITLE
Bug in Division of Fractions

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#859]
## **Describe the bug**
The division of Fractions under the General Math part solves for the undefined fractions as well, I would like to add a prompt to the user when they enter any undefined fraction.
![Capture1](https://user-images.githubusercontent.com/70858557/113820394-46962400-9798-11eb-972a-f5bcb50d6f5d.PNG)
![Capture2](https://user-images.githubusercontent.com/70858557/113820398-47c75100-9798-11eb-82f4-ae52389b0872.PNG)

I would like to resolve this issue. Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 April,2021 11:59 PM IST
