### ISSUE TITLE
Calculation part of EMI calculator

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#860]
## **Describe the bug**

Whenever we enter any values like 0.9, 0.3, etc (as the value of year which is later converted to months for calculations) it shows an error, whereas the calculation works perfectly with other values greater than 0. I would like to resolve this, Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![3a](https://user-images.githubusercontent.com/70858557/113821155-59f5bf00-9799-11eb-8cad-1e41b9b063bd.PNG)
![3b](https://user-images.githubusercontent.com/70858557/113821159-5bbf8280-9799-11eb-9a68-c524dfdb9c2b.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 April,2021 11:59 PM IST
