### ISSUE TITLE
Conversion of Improper to Mixed Fraction

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#861]
## **Describe the bug**

When we enter any fraction having denominator as 0, eg: 5/0 it should simply prompt as the value of fraction is undefined, instead it converts it to mixed. Also while converting it should simply print infinity rather it display it in mixed fraction form. I would like to resolve this, Kindly assign this to me under GSSoC. 

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![Inked2_LI](https://user-images.githubusercontent.com/70858557/113821870-4eef5e80-979a-11eb-8e53-096517c8fe1b.jpg)

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 April,2021 11:59 PM IST
