### ISSUE TITLE
Adding various sets formula

### ISSUE THREAD

**Issue by Maitryee-Choudhary** [sairish2001/makesmatheasy#867]
## **Is your feature request related to a problem? Please describe.**

- I will be adding various formulas based on set theory.

## **Describe the solution you'd like**

- The formula like for group of 2 sets:
-  n(P U Q) = n(P) + (n(Q) – n (P ⋂ Q)
- n(P−Q)=n(P∩Q)−n(Q) and so on.

hey @sairish2001 would you please assign this issue to me

**Comment by sairish2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST
