### ISSUE TITLE
add alert while use different base other than selected

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy#871]
## **Is your feature request related to a problem? Please describe.**

add alert while use different base other than selected

ex input un decimal while selected base is binary

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Go ahead
Deadline 12 April, 2021 (11:59 PM IST)

**Comment by satyampgt4** [comment]
actually xor operator is already present
