### ISSUE TITLE
Add Disjoint in Operations on Sets

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#880]
## Proposal

Sets can be combined in many different ways so as to produce new sets.

I want to add "Disjoint Sets" in `Operation on Sets` category.

![disjointset](https://user-images.githubusercontent.com/73488906/113980154-c5a45e80-9863-11eb-9db5-0edf73a6b497.png)

Kindly assign this to me under GSSoC.

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST
