### ISSUE TITLE
Adding calculator to find hyperbolic trigonometric ratios.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#882]
I would like to add a calculator to find hyperbolic trigonometric ratios.
Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST

**Comment by Ankita297** [comment]
@sairish2001 Can i work on this ?

**Comment by Ankita297** [comment]
@sairish2001 Can i work on this ?

**Comment by Ankita297** [comment]
@shrey27tri01 can i work on this ?
