### ISSUE TITLE
Add about permutations and combinations

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#884]
## **Is your feature request related to a problem? Please describe.**

- Problem: A calculator for permutation and combination exists but what if one don't know how to use, when to use, for what purpose it is made, which type of calculations can be done?

## **Describe the solution you'd like**

- In order to be understandable, information should be complete, concise, clear and in organized methodology that is easy for the reader.
- Firstly, I will provide three types of permutation description with definition, assumption and formula.
- Secondly, I will explain about combination with info as above.
- Lastly, will see the relation between permutation and combination.

You can see my work:

![pandc](https://user-images.githubusercontent.com/73488906/114019700-598a2080-988c-11eb-9944-8012e9a543ad.png)

I have done a bit of above and will complete it.

Kindly assign this to me under GSSoC'21.

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST
