### ISSUE TITLE
UI enhancement in circle calc in conic section.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#885]
## **Is your feature request related to a problem? Please describe.**
There are contents in the last column which are not visible and the scroll bar is at the end of the page due to which a user has to scroll all the way to the bottom to scroll.

## **Describe the solution you'd like**
A scrollbar after each table will be better.
Please assign this to me.

![Screenshot (221)](https://user-images.githubusercontent.com/66053534/114023160-25b0fa00-9890-11eb-9f73-5a3424f379af.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST
