### ISSUE TITLE
Bug in Decimal-grey code conveter

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#887]
## **Describe the bug**
If there is no input N00 is displayed. Whereas there should be no output.
Please assign this to me.
![Screenshot (223)](https://user-images.githubusercontent.com/66053534/114031769-50538080-9899-11eb-86ba-98ebda620ebb.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST
