### ISSUE TITLE
Duplicate option in Ops for 1 complex number.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#888]
Exponential form and euler representation are same thing. But they are given as 2 different options in  Ops for 1 complex number calculator. One of the option should be removed.
Please assign this to me.

![Screenshot (224)](https://user-images.githubusercontent.com/66053534/114032922-6f064700-989a-11eb-9dae-ec2d2329b621.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST
