### ISSUE TITLE
Display a message if user not marked anything favourite when clicks on Favourite button.

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#890]
## **Is your feature request related to a problem? Please describe.**

-When the user click on favourite and nothing is still marked favourite ,the message should display "nothing marked as favourite".

## **Describe the solution you'd like**

- I will add a message which display nothing in favourites

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST

**Comment by ShrutiOmer** [comment]
Thank you for assigning
