### ISSUE TITLE
Bug in P/B/H calculator

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#891]
## **Describe the bug**

- After entering right dimensions for triangle still showing right angle triangle dimension not possible.

## **Screenshots**

- A right angle can have dimensions 4,3 and 5 as hypotenuse. Still showing not possible. 
![favourite](https://user-images.githubusercontent.com/75009990/114039241-379a9900-98a0-11eb-8ae1-9935ec16c93b.png)

**Comment by supriyagahoi** [comment]
Hi, I want to work on this issue. I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : supriya gahoi
Discord Tag: #2406

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST

**Comment by ShrutiOmer** [comment]
Sir I have created this issue, you have assigned to someone else. Please assign it to me.

**Comment by sairish2001** [comment]
@ShrutiOmer Creating an issue and asking for assignment is two different things.

You should ask for assignment also.

**Comment by ShrutiOmer** [comment]
Okk, I will take care of that.
