### ISSUE TITLE
Modify AP, GP part and add more content.

### ISSUE THREAD

**Issue by janvi01** [sairish2001/makesmatheasy#892]
## **Is your feature request related to a problem? Please describe.**

Under Linear algebra dropdown, sum of nth term of AP, GP are there.

## **Describe the solution you'd like**

- I would like to add 'Sequence and series' option which would contain AP, GP part 
- Add some more functionalities like get value of nth term, formulae list related to sequence and series.

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST

**Comment by janvi01** [comment]
So i have added option "Sequence & Series"
- Added Formula list under that.
- Added method of finding nth term in both GP and AP part.


<img width="1375" alt="Screenshot 2021-04-10 at 2 44 59 PM" src="https://user-images.githubusercontent.com/34344234/114264959-9fb9be00-9a0b-11eb-83be-65cdc86cbe55.png">

**Comment by janvi01** [comment]
Is it Okay? @sairish2001  Please review

**Comment by janvi01** [comment]
@sairish2001

**Comment by khareyash05** [comment]
@janvi01 Create a PR citing these changes

**Comment by Ankita297** [comment]
@shrey27tri01 can i work on this ?

**Comment by Ankita297** [comment]
@sairish2001 Can i work on this ?

**Comment by sairish2001** [comment]
> So i have added option "Sequence & Series"
> - Added Formula list under that.
> - Added method of finding nth term in both GP and AP part.
> 
> 
> <img width="1375" alt="Screenshot 2021-04-10 at 2 44 59 PM" src="https://user-images.githubusercontent.com/34344234/114264959-9fb9be00-9a0b-11eb-83be-65cdc86cbe55.png">
> 
> 

@janvi01 please create a PR

**Comment by Ankita297** [comment]
@sairish2001 @shrey27tri01 can i work on this ?

**Comment by sairish2001** [comment]
> @sairish2001 @shrey27tri01 can i work on this ?

Go ahead
