### ISSUE TITLE
Pressure convertor is not visible in basic converter

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#893]
## **Describe the bug**

- Pressure Converter is added but not visible

## **Screenshots**
![image](https://user-images.githubusercontent.com/75009990/114046261-53a13900-98a6-11eb-9907-a820e08a7740.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST

**Comment by ShrutiOmer** [comment]
Thank you for assigning
