### ISSUE TITLE
To make Binary/Decimal/Hexadecimal/Octal convertor in one section 

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#898]
I want to make all binary/hexadecimal/decimal/octal convertor in one section

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it from 3rd April. I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST

It's already implemented, but are scattered and have different options for different operations, kindly merge into single option.

**Comment by abhijeet141** [comment]
> Go ahead
> Deadline 14 April,2021 11:59 PM IST
> 
> It's already implemented, but are scattered and have different options for different operations, kindly merge into single option.

Okay sir :)

**Comment by sairish2001** [comment]
![#843](https://github.com/sairish2001/makesmatheasy/issues/843)
this issue is similar to urs.

**Comment by abhijeet141** [comment]
> [#843](https://github.com/sairish2001/makesmatheasy/issues/843)
> this issue is similar to urs.

Yes i did'nt notice that 🙂
