### ISSUE TITLE
Element overlapping side-navbar

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/MakesMathEasy#9]
Graph's Menu bar is overlapping the main-nav bar.
![PicsArt_03-04-06 37 06](https://user-images.githubusercontent.com/60106112/109968739-1a126680-7d19-11eb-9849-10a2412277bb.jpg)

Solution:
Try increasing z-index of side-nav
---
Graph is implemented in
- Plot Graph
- Integration
- Differentiation
- Laplace

You can test from any of the following

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by RituCs** [comment]
Please assign this issue.

**Comment by sayna3311** [comment]
I would love to work on this issue. Please assign this to me?

**Comment by sairish2001** [comment]
@sayna3311 Sorry! First come first serve. Be active to our issues. New issues will be available soon.

**Comment by sairish2001** [comment]
@RituCs Feel free to ask doubts, if any

**Comment by sairish2001** [comment]
Any Update? @RituCs

**Comment by sairish2001** [comment]
Deadline 11 March, 2021 (11:59 PM)

**Comment by mohammedjameel24** [comment]
assign it to me gssoc21

**Comment by sairish2001** [comment]
Today is the last date @RituCs
11 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
> I would love to work on this issue. Please assign this to me?

Do you want to contribute?

**Comment by sayna3311** [comment]
> > I would love to work on this issue. Please assign this to me?
> 
> Do you want to contribute?

Yes, I want to! :)

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 14 March,2021 (11:59 PM IST)

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.

**Comment by sairish2001** [comment]
@rk05-lenavo Do you want to work on this issue?

**Comment by rk05-lenavo** [comment]
@sairish2001 Yes sir. Sure

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 21 March,2021 (11:59 PM IST)

**Comment by anjali7786** [comment]
Hi..I would like to work on this issue under GSSOC'21. Kindly assign me this issue.

**Comment by sairish2001** [comment]
@anjali7786 Go ahead
Feel free to ask your doubts, if any
Deadline 24 March,2021 (11:59 PM IST)
