### ISSUE TITLE
Adding the logo of Makes Math easy on the home page

### ISSUE THREAD

**Issue by gritika18** [sairish2001/makesmatheasy#90]
When we open the site it looks blank and empty. I was thinking of addling the logo of Makes Math Easy at the top center position of home page. This will fill the space making it look somewhat like Google.

**Comment by vanshikapandey** [comment]
I am interested in working in this issue please assign it to me ma'am.

**Comment by gritika18** [comment]
I'm not the Project admin. I'm a GSSOC participant. I've created this issue here so that the mentor will look upon it and if they find it relevant then he'll assign it to me.

**Comment by shrey27tri01** [comment]
@gritika18 You can go ahead with the issue :)
But before creating the pull request, please show us the changes you intend to make through screenshots or any other medium as per your convenience :smile:

**Comment by ambivert-sam** [comment]
@gritika18 can I enhance it? Will you please assign it to me?

**Comment by gritika18** [comment]
![Screenshot](https://user-images.githubusercontent.com/76582250/111783208-fd149080-88df-11eb-83f5-44cdc7a9bfdb.png)
@shrey27tri01

**Comment by gritika18** [comment]
@ambivert-sam I'm not the project admin. I'm a participant of GSSOC'21. The issue has already been assigned to me by the mentor. You can look for another issue or create a new issue.

**Comment by gritika18** [comment]
@shrey27tri01 Any changes you want or anything else regarding the logo? Please let me know whether you are satisfied with the changes or not. I'll make a PR then. Thankyou
