### ISSUE TITLE
Adding more type of 3D shapes

### ISSUE THREAD

**Issue by supriyagahoi** [sairish2001/makesmatheasy#900]
In graphs and shapes their is section of Calculator of 3D shape  -There is only 5type of shapes are avilable for calculation.
I want to add more type of 3D shape  calculator in Graphs and Shapes .

**Comment by supriyagahoi** [comment]
Hi, I want to work on this feature . I am a part of GSSoC'21.
Kindly assign this work to me!
Discord Username : supriya gahoi
Discord Tag: #2406

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 April,2021 11:59 PM IST
