### ISSUE TITLE
message display when any operation is not allowed on matrix.

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#907]
## **Is your feature request related to a problem? Please describe.**
When user provides the size of matrix and is not allowed for some operations, then there a message should be displayed informing the user that you cannot perform addition or subtraction on matrix with the given inputs.

![mult](https://user-images.githubusercontent.com/57946528/114187193-59aa1f00-9965-11eb-9fd1-3dacb4f8c820.png)

## **Describe the solution you'd like**
I would like to add a message to be displayed whenever any of the operation cannot be performed on the matrix.

**Comment by sairish2001** [comment]
![img](https://user-images.githubusercontent.com/60106112/114214568-16aa7480-9982-11eb-80d5-6fbabe1f4ea6.jpg)
It working properly
![Screenshot_20210409-222123_Chrome.jpg](https://user-images.githubusercontent.com/60106112/114214633-2924ae00-9982-11eb-95de-9fac2cc8de5d.jpg)

**Comment by shonali2600** [comment]
@sairish2001 , like in my input case, it's not possible to add two matrices, it just gives the multiplication option from the dropdown but doesn't tell anything about addition or subtraction. So the user might get confused about why is he not getting the addition option on the matrix.
So I want is to display a proper message to inform where the user is going wrong.

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
