### ISSUE TITLE
steps for volume and surface of solid of revolution about an axis 

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#910]
Hi! I would like to add steps for volume and surface of solid of revolution about an axis 
with graphs and diagrams using latex

**Comment by sairish2001** [comment]
Means a Calculator?

**Comment by khareyash05** [comment]
No! @sairish2001  It actually can't be expressed by a calculator its a theory part and i will mention the steps with diagrams and explanations for each step

**Comment by khareyash05** [comment]
@sairish2001 Should i work on  this?
