### ISSUE TITLE
In about section some content is hard to read due to color issue in Light Mode

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#911]
## Proposal

I would like to design a card for this About section so that it will be easily visible and easy to read irrespective of the theme chosen, additionally, it will look much more attractive.

**Comment by shonali2600** [comment]
Please assign this issue to me, I would like to work on this as a gssoc participant.

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by shonali2600** [comment]
@sairish2001 you closed this issue however my pull request has not been merged till now, kindly let me know was this mistakenly closed, or there was any other reason?
