### ISSUE TITLE
Bug in conversion of Improper to Mixed Fraction

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#913]
## **Describe the bug**

wrong answer is displayed when both numerator and denominator values are same. I would like to work on this issue. Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![Capture](https://user-images.githubusercontent.com/70858557/114195478-1dc78780-996e-11eb-87a0-13752ac1821b.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
