### ISSUE TITLE
Bug in Operation of fractions

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#918]
## **Describe the bug**

The **multiplication, subtraction and addition of Fractions** under the General Math part solves for the undefined fractions as well, I would like to add a prompt to the user when they enter any undefined fraction. Kindly assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![Capture1](https://user-images.githubusercontent.com/70858557/113820394-46962400-9798-11eb-972a-f5bcb50d6f5d.PNG)
![Capture2](https://user-images.githubusercontent.com/70858557/113820398-47c75100-9798-11eb-82f4-ae52389b0872.PNG)

![b1](https://user-images.githubusercontent.com/70858557/114208360-0216ae00-997b-11eb-8b10-364c22b0b801.PNG)
![b2](https://user-images.githubusercontent.com/70858557/114208366-03e07180-997b-11eb-8d5c-9e07f48bf1fc.PNG)
![b3](https://user-images.githubusercontent.com/70858557/114208368-03e07180-997b-11eb-8433-32339df371cd.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
