### ISSUE TITLE
Bug in hemisphere option in 3D shapes calculator

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#921]
## **Describe the bug**
Hemisphere option is not showing the output when the radius is entered.
Please assign this to me.

![Screenshot (228)](https://user-images.githubusercontent.com/66053534/114211712-99313500-997e-11eb-9bad-1be0f680a3b2.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
