### ISSUE TITLE
Bug in Hollow sphere option in 3D shapes calculator.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#922]
## **Describe the bug**
Hollow hemisphere option doesn't show any output even when both the radiuses are entered.
Please assign this to me.

![Screenshot (229)](https://user-images.githubusercontent.com/66053534/114212336-57ed5500-997f-11eb-94f4-f171faa13753.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
