### ISSUE TITLE
Bug in searchbar

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy#925]
## **Describe the bug**
If there are more than 1 suggestions for an input the user cannot select 2nd and third option as numfacts covers them . They are visible but can not be selected.

Please assign this to me.

![Screenshot (231)](https://user-images.githubusercontent.com/66053534/114214130-8ff59780-9981-11eb-865a-63041bed1862.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
