### ISSUE TITLE
None of the calculators are giving output 

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#929]
## **Describe the bug**

-After providing input none of the calculator are giving output 

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/114243188-ca732a80-99a9-11eb-84ac-032525c835c8.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue. I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 April,2021 11:59 PM IST
