### ISSUE TITLE
Bug in profit/loss calculator

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#930]
The profit loss calculator not showing any result when data is entered.
I would like to solve this issue. Please assign this issue to me.
![Screenshot (1710)](https://user-images.githubusercontent.com/73697080/114255156-45037080-99d1-11eb-9279-e25411a91676.png)

**Comment by abhijeet141** [comment]
@RaveenaBhasin I have already created the same issue #929 there is a small error and after rectifying it all the calculators will start working
