### ISSUE TITLE
big favourite size in operation on sets and misalign

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#933]
the favourite button in operation of sets is too big and is causing misalignment of  tabs because of this buttons aren't working
![image](https://user-images.githubusercontent.com/60147732/114257643-0379c200-99df-11eb-8e2e-cd37223ddbdd.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
