### ISSUE TITLE
Move 9's 10's complement in the same button as it is for the other complements!

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#935]
![image](https://user-images.githubusercontent.com/71064674/114258662-c7962b00-99e5-11eb-8b43-88832fa02189.png)

1)Rename 1's 2's complement -> (R-1)'s and R's complement 
2) Move 9's 10's complement into button- (R-1)'s and R's complement 

As well as update the same for  readme file 
![image](https://user-images.githubusercontent.com/71064674/114258741-6a4ea980-99e6-11eb-919c-c0747356a42a.png)

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
