### ISSUE TITLE
Bug in button  'Cost and selling prices'

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#938]
1) Fix 'Cost and selling prices' -> button isnt working !!

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by khareyash05** [comment]
@AB-san i have already created the same issue #933 . Kindly close the issue

**Comment by AB-san** [comment]
> @AB-san i have already created the same issue #933 . Kindly close the issue

Okay I have changed my issue now its different from yours

**Comment by khareyash05** [comment]
@sairish2001  I had already created the same issue well before the same #934 #933 and was waiting for you to assign me@
@AB-san as per the open source rules of GSSOC, You should wait for the assignment and then create a PR

**Comment by sairish2001** [comment]
@khareyash05 
Sorry my mistake!, You can continue, as I reverted the PR

@AB-san as I already told, you should wait for assignment before making PR, and I noticed he created the issue for the same.

**Comment by khareyash05** [comment]
@sairish2001 Thats' ok and Thanx

**Comment by AB-san** [comment]
> @khareyash05 
> Sorry my mistake!, You can continue, as I reverted the PR
> 
> @AB-san as I already told, you should wait for assignment before making PR, and I noticed he created the issue for the same before you.
> 

I am really sorry I sent the pr before getting assigned 
But my issue is different from @khareyash05

**Comment by AB-san** [comment]
> @khareyash05 
> Sorry my mistake!, You can continue, as I reverted the PR
> 
> @AB-san as I already told, you should wait for assignment before making PR, and I noticed he created the issue for the same before you.
> 

In my issue , as I have mentioned , I fixed the unresponsive button of

**Comment by khareyash05** [comment]
@AB-san I am sorry  but in the process u did solve my issue

**Comment by AB-san** [comment]
> @AB-san I am sorry  but in the process u did solve my issue 
> MOdified the colour of fav buttons as i mentioned in #934 

Oh sorry 
Actually I couldn't understand issue #934 at that time so I made issue on it .

**Comment by AB-san** [comment]
> 
> 1) Fix 'Cost and selling prices' -> button isnt working !!
> 
> ![image](https://user-images.githubusercontent.com/71064674/114259559-6756b780-99ec-11eb-973d-78ae155116ad.png)
> 
> 

@sairish2001 please check this issue... now it's not related to any of the already opened issue 
So, I am reopening this issue please assign me this one 

And I am really sorry for all those confusion , this won't happen again!!

**Comment by sairish2001** [comment]
So in this issue you will change the colors of heart?

**Comment by AB-san** [comment]
> So in this issue you will change the colors of heart?

No that one is issue #934 
here I will make the cost and selling price button responsive ... as youcan see its not working !!

**Comment by sairish2001** [comment]
Go ahead
