### ISSUE TITLE
Sidenav under the linear algebra, icon disturbs all other options

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#939]
## **Describe the bug**

under the linear algebra there is a big heart which disturbs the all other options, and some useless content(styling code) is displaying below it.

## **Possible solution**

I will resolve this issue

## **Screenshots**

![mathe](https://user-images.githubusercontent.com/57946528/114260162-ba326e00-99f0-11eb-939a-39a566e24aa7.png)

**Comment by shonali2600** [comment]
I would like to work on this issue, please assign it to me

**Comment by sairish2001** [comment]
This issue is already created by someone else
