### ISSUE TITLE
Pressure unit convertor missing

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#942]
The pressure unit convertor is missing i.e. it is not visible in the unit convertor section. 
I would like to resolve the issue. Please assign this issue to me.
![Screenshot (1721)](https://user-images.githubusercontent.com/73697080/114261975-04205180-99fb-11eb-9144-6ee21ee39cdd.png)

**Comment by ShrutiOmer** [comment]
This issue already created #893 and been rectified by me through pr #936 .
