### ISSUE TITLE
Pressure and Time  are shown in division of fractions 

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#943]
## **Describe the bug**

- In Division of fractions under operation of fraction shows pressure and time which is irrelevant.

## **Screenshots**
![image](https://user-images.githubusercontent.com/75009990/114262003-1dc19900-99fb-11eb-993a-adae007f0b6d.png)

**Comment by ShrutiOmer** [comment]
Please assign this issue to me. I am a Gssoc Participant.

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
