### ISSUE TITLE
GST Calculator

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy#944]
## Proposal
I want to make a GST Calculator under general math , which calculates GST(CGST/SGST) from selected GST rate.

**Comment by ShrutiOmer** [comment]
Please assign this issue to me, I am a Gssoc participant.

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by ShrutiOmer** [comment]
Thankyou for assigning.
