### ISSUE TITLE
Bug in Geometric Mean

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#945]
## **Describe the bug**

Geometric mean cannot be calculated for negative numbers.

## **Possible solution**

 I would like to display warning message when user enter any one negative value. Kindly assign this to me under GSSoc.

## **Screenshots**

![1](https://user-images.githubusercontent.com/70858557/114264257-74cd6b00-9a07-11eb-9f37-6156e0e4b419.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

Show appropriate message, that negative numbers are not allowed.... something like that

**Comment by madihamallick** [comment]
> Go ahead
> Deadline 15 April,2021 11:59 PM IST
> 
> Show appropriate message, that negative numbers are not allowed.... something like that

Okay
