### ISSUE TITLE
Modify binary/decimal converter , to convert fractional part!

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#946]
![image](https://user-images.githubusercontent.com/71064674/114264869-14402d00-9a0b-11eb-8737-38dc59716cb2.png)

Expected output->  -101.1
I would like to modify the converter so that it can also calculate fractional part

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
