### ISSUE TITLE
Modify octal/hexadecimal converter to calculate for fractional part also 

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#947]
![image](https://user-images.githubusercontent.com/71064674/114264934-7e58d200-9a0b-11eb-81d4-6904889d57a9.png)

Expected output-> -7.C

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by AB-san** [comment]
I am still working on it !! it will be over by today
