### ISSUE TITLE
Modify Binary/Decimal/Hexadecimal so that it can be calculated for fractional part

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#948]
Modify Binary/Decimal/Hexadecimal so that it can be calculated for fractional part 

## **Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/67696867/114265242-5f5b3f80-9a0d-11eb-971c-bc442e8ce4ba.png)
Its result should be c.8 and now it is displaying only c

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue. I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
this issue is already created by someone

**Comment by abhijeet141** [comment]
Okay
