### ISSUE TITLE
Modify octal/binary converter to calculate for fractional part also

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#949]
![Screenshot_20210411-175609.png](https://user-images.githubusercontent.com/71064674/114304158-5347ae80-9aef-11eb-88ff-5a422e32699e.png)

Answer must be 10.101

Modify octal/hexadecimal converter to calculate for fractional part also

**Comment by AB-san** [comment]
Please assign me thiss issue

**Comment by sairish2001** [comment]
You created this issue twice

**Comment by AB-san** [comment]
> You created this issue twice

Sorry my bad , I meant octal/binary converter!!

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 April,2021 11:59 PM IST

**Comment by AB-san** [comment]
I am still on it !! it will be over by today
