### ISSUE TITLE
Scroll calculator automatically on toggle down

### ISSUE THREAD

**Issue by SanskrutiRP** [sairish2001/MakesMathEasy#95]
## **Describe the bug**

-Whenever we open calculator it remains open even if we have selected another functionality.
Suppose we have opened calculator and then we open integration tab. Then calculator must be closed but it needs to tab on calculator button to close.

## **Possible solution**

- Making calculator responsive. i.e. when another feature is opened it must be closed automatically. And whenever asked must open on specific location it needs to scroll down to find calculator.

## **Screenshots**
![gssoc_math](https://user-images.githubusercontent.com/67673060/110752068-c351e300-826a-11eb-81ba-f20145392316.PNG)

-

**Comment by sairish2001** [comment]
Actually, I don't want it to close automatically, when other functions toggles, because sometimes while doing some other calculations, if user wants to do some basic Calculations at a same time ,then it would create a problem if we close the other opened Calculators.

**Comment by SanskrutiRP** [comment]
You are right👍.
Then I think we can place calculator at fixed location on screen.
Because we need to scroll down to find calculator.

**Comment by sairish2001** [comment]
If you want, then you can make some changes like:
Whenever the calculator toggles down, automatically scroll the screen to the calculator

**Comment by SanskrutiRP** [comment]
Yes. It's better. Thank you!

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 16 March,2021 (11:59 PM IST)

**Comment by SanskrutiRP** [comment]
Thank You!!

**Comment by SanskrutiRP** [comment]
Hey due to some network issue I am unable to do my PR today.
Can I get extension till tomorrow?

**Comment by sairish2001** [comment]
Deadline extended 18 March,2021 (11:59 PM IST)

**Comment by Sukriti-sood** [comment]
@sairish2001 Is this isssue open for work.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 25 March,2021 (11:59 PM IST)
