### ISSUE TITLE
Modify the workflow - Add superlinter in the workflow

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#957]
## Proposal
Modify the workflow by using superlinter to reduce the work of maintainers

PROBLEM - I have noticed quite a few times , sometimes a pr with open HTML tags gets merged and its quite understandable because its too hard  for both the contributor and mentors to find those some small bugs - for example - one unclosed div tag may lead to a number of unresponsive buttons. 
This is not only with HTML but also it happens for js files too , for example - one unclosed curly braces lead unresponsive calculators and converters. (NOTE- I am not targeting anybody , this small errors can happen with anyone)

SOLUTION- This above mentioned problem can be solved by modifying the workflow i.e, every time someone pushes his/her code , the code must pass through a set of automatic tests with the help of CI/CD tools in order to make sure the code is bug-free. 

Now about Superlinter (benefits)- 
1)First of all its totally free.
2)Prevent broken code from being uploaded to the default branch (Usually master or main)
3)Help establish coding best practices across multiple languages
4)Build guidelines for code layout and format
5)Automate the process to help streamline code reviews

And superlinter also supports linters for HTML , CSS, Javascript and LATEX which is widely used in this project .

**Comment by AB-san** [comment]
I would love to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

Great! This really help us

**Comment by AB-san** [comment]
> Go ahead
> Deadline 15 April,2021 11:59 PM IST
> 
> Great! This really help us

Sure 
Actually I am new with GitHub actions so can I please get more time for this particular issue.
