### ISSUE TITLE
Add github action to automatically close the issue after it is merged

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#958]
## Proposal

Github actions can be used to reduce your work @sairish2001 of closing each pr after it gets merged

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by AB-san** [comment]
Actually this issue is taking a lot more time than I expected , can i please get a extension of dates for this issue

**Comment by Ankita297** [comment]
Can i work on this @sairish2001 @shrey27tri01 ?

**Comment by AB-san** [comment]
> Can i work on this @sairish2001 @shrey27tri01 ?

Hello @Ankita297 actually I am still working on it!!!

**Comment by sairish2001** [comment]
Deadline extended 20 April,2021

**Comment by AB-san** [comment]
> Deadline extended 20 April,2021

Thanks a lot
