### ISSUE TITLE
Add auto-message after pr is merged

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#959]
## Proposal

![image](https://user-images.githubusercontent.com/71064674/114288539-89087b00-9a8e-11eb-9dd2-1f168be70dd5.png)

If mentors  want a bot  to automatically send this message after each pr is merged then I can implement this using github actions which can save the precious time of the maintainers
@sairish2001 @shrey27tri01

**Comment by AB-san** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Add some good wording to appreciate their Contribution

Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by AB-san** [comment]
> Add some good wording to appreciate their Contribution
> 
> Go ahead
> Deadline 15 April,2021 11:59 PM IST

Sure , Got it

**Comment by AB-san** [comment]
> Add some good wording to appreciate their Contribution
> 
> Go ahead
> Deadline 15 April,2021 11:59 PM IST

Thank you @user_name for taking out your valuable time in order to contribute to our project. Looking forward for more such amazing contributions :)

**Comment by AB-san** [comment]
> > Add some good wording to appreciate their Contribution
> > Go ahead
> > Deadline 15 April,2021 11:59 PM IST
> 
> Thank you @user_name for taking out your valuable time in order to contribute to our project. Looking forward for more such amazing contributions :)

@sairish2001 Done with the program part. Please approve the message , let me know if you are ok with this message or you want a better one

**Comment by sairish2001** [comment]
> > Add some good wording to appreciate their Contribution
> > 
> > Go ahead
> > Deadline 15 April,2021 11:59 PM IST
> 
> Thank you @user_name for taking out your valuable time in order to contribute to our project. Looking forward for more such amazing contributions :)


Go ahead
