### ISSUE TITLE
Conclusions from set operations

### ISSUE THREAD

**Issue by mehabhalodiya** [sairish2001/makesmatheasy#963]
## Proposal

The set operations are already listed, but what identity/property it holds?
That information is not there.

### Solution:

-  I will add list of all.
- Below is some of them:

![conclusion](https://user-images.githubusercontent.com/73488906/114293893-abfb5500-9ab7-11eb-9283-31e6da71148e.png)

Kindly assign this to me under GSSoC'21.

**Comment by mehabhalodiya** [comment]
@sairish2001 Can I work further on this?

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
