### ISSUE TITLE
Working of Trapezium

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#966]
## **Describe the bug**
There is bug in the calculation part of Trapezium. I would like to work on this issue. Area or height can never be 0. Also when the value within root becomes negative it shows NaN. Please assign this to me under GSSoC.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![2](https://user-images.githubusercontent.com/70858557/114296362-9fcbc380-9ac8-11eb-9c55-06e404e8b4de.PNG)
![1](https://user-images.githubusercontent.com/70858557/114296361-9e9a9680-9ac8-11eb-8002-c758963e742c.PNG)

- If applicable, add screenshots to help explain your problem.

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST
