### ISSUE TITLE
Number facts overlaps with the search bar

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#975]
## **Describe the bug**

The number facts is overlapping with the search bar.

## **Possible solution**

I will align it to the correct place so that this problem will be rectified.

## **Screenshots**
![over](https://user-images.githubusercontent.com/57946528/114304968-8d1ab400-9af3-11eb-82bb-3cace8ad712f.png)

**Comment by shonali2600** [comment]
PLease assign me this issue as a gssoc participant.

**Comment by apekshamanchanda** [comment]
Sure, you can work on this
Deadline : 15 April 2021
