### ISSUE TITLE
Some heart icons are different from others

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#976]
## **Describe the bug**

In linear ALgebra section, some hearts colors are different from all others.

## **Possible solution**

I would make it same as all others.

## **Screenshots**
![heart](https://user-images.githubusercontent.com/57946528/114305129-77f25500-9af4-11eb-828a-bf110e602b92.png)

**Comment by shonali2600** [comment]
Please assign me this issue as a gssoc participant

**Comment by apekshamanchanda** [comment]
Sure, you can work on this
Deadline: 15 April 2021
