### ISSUE TITLE
Favorites should be displayed at the center

### ISSUE THREAD

**Issue by shonali2600** [sairish2001/makesmatheasy#977]
## Proposal

On clicking favorites, list of favorites appears at right side of the page. It should be at the center of page.

![fav](https://user-images.githubusercontent.com/57946528/114305318-4ded6280-9af5-11eb-9c88-9cff2c8d7f7c.png)

**Comment by shonali2600** [comment]
Please assign me this, I would like to work on this.

**Comment by sairish2001** [comment]
No, this is in it's right position
