### ISSUE TITLE
UI on home page

### ISSUE THREAD

**Issue by satcasm** [sairish2001/makesmatheasy#984]
At present if you click on ```favourite``` and ```calculator``` simultaneously both are present on the screen, which doesn't looks so good.
Would like to make the necessary changes , such that both things can't be opened simultaneously.
Please assign this to me under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/114311143-36b96f80-9b0b-11eb-9eec-296ab4e0186c.png)

**Comment by apekshamanchanda** [comment]
Sure, Go ahead
Deadline: 15 April 2021

**Comment by sairish2001** [comment]
@satcasm 
Don't hinder this UI, remain it as it is

if you want, then the searchbar and facts panel is overlapping, fix it
