### ISSUE TITLE
Adding calculator for triangular pyramid

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy#986]
I would like to add a calculator for finding different parameters of the triangular pyramid.
Please assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 April,2021 11:59 PM IST

**Comment by RaveenaBhasin** [comment]
I have made the PR #1006 . Kindly review it @sairish2001
