### ISSUE TITLE
Add auto message when someone creates a new issue for the first time

### ISSUE THREAD

**Issue by abhijeet141** [sairish2001/makesmatheasy#988]
## **Describe the solution you'd like**

- Using github action when someone will create a new issue for the first time a welcome bot will deploy a message which will say "Hello @github_user Thank you for opening an issue. Our team will review this issue and will assign it to you

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 April,2021 11:59 PM IST

**Comment by Ankita297** [comment]
@sairish2001  this issue is resolved .

**Comment by abhijeet141** [comment]
Yes this issue is resolved but i would like to change the bot to this 
![image](https://user-images.githubusercontent.com/67696867/115832490-9596b700-a430-11eb-9b5e-93981a46a62f.png)

**Comment by Ankita297** [comment]
@abhijeet141  the github action that has been added also does the same work .
![Add auto label of gssoc on PR opened · Issue #1339 · sairish2001_makesmatheasy - Google Chrome 23-04-2021 12_41_35](https://user-images.githubusercontent.com/67833077/115833080-4735e800-a431-11eb-8f85-49e7a1a947a8.png)

**Comment by abhijeet141** [comment]
@Ankita297 Yes i know it does the same work but i would like to change it to the welcome bot
