### ISSUE TITLE
Add a inverse of matrix finding tool.

### ISSUE THREAD

**Issue by vmk8826** [sairish2001/MakesMathEasy#99]
## Proposal
There is a matrix operator but not a determinant solver. There should be a way to find determinant and inverse
![determinant](https://user-images.githubusercontent.com/68069180/110777648-5c8ef280-8287-11eb-9dec-c7cd63b42005.jpg)
 matrix too.

**Comment by vmk8826** [comment]
please assign it to me I am a GSoC 2021 aspirant.

**Comment by sairish2001** [comment]
It's already there in
- Matrix
- Single Matrix
- Input Fields
- Determinant (up to 5x5)

**Comment by sairish2001** [comment]
In future I am planning to add more operations for the matrix, if I place all functions in the sidenav, then the list becames so long

**Comment by vmk8826** [comment]
oh okay but I guess the tool for finding the inverse of a matrix is not there. Can I work on that

**Comment by vmk8826** [comment]
can youreview above suggestion please

**Comment by vmk8826** [comment]
can you please checkout above suggestion

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 15 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
![image](https://user-images.githubusercontent.com/60106112/111075071-36c64f80-850c-11eb-99cb-7f71032f86a0.png)

Do add inverse of matrix option in between these options rather than in sidenav

**Comment by vmk8826** [comment]
okay
