### ISSUE TITLE
Bug in square pyramid option in 3D shapes calculator.

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#996]
## **Describe the bug**

I would like to work on this issue. Please assign this to me

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![2](https://user-images.githubusercontent.com/70858557/114345048-9d2ba580-9b7e-11eb-8fa9-a3bc9fb2a23f.PNG)

**Comment by RaveenaBhasin** [comment]
@madihamallick This issue has arisen while resolving some conflicts. I have rectified this in PR #1006. You can close this issue the issue is resolved now.

**Comment by sairish2001** [comment]
This issue is different @RaveenaBhasin
