### ISSUE TITLE
Adding Excess 3 code to binary convertor

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy#997]
Now the calculator calculates excess 3 to decimal and vice versa. I would like to add **excess 3 to binary and vice versa** here. Please assign this to me under GSSoC.

![3](https://user-images.githubusercontent.com/70858557/114345949-445d0c80-9b80-11eb-8e88-6ad3f0025a5d.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST
