### ISSUE TITLE
Unwanted text in lilght mode

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy#999]
## **Describe the bug**

- A clear and concise description of what the bug is.
- unwanted text(11) above the calculator in light mode
![missue](https://user-images.githubusercontent.com/61223163/114350947-8ccbf880-9b87-11eb-99d0-3d4f679c5ca0.PNG)

I want to work on this issue
## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST
